### ISSUE TITLE
手机端显示问题：归档文章日历只能显示到 6 月

### ISSUE THREAD

**Issue by pleuvoir** [blinkfox/hexo-theme-matery#10]
![_20181007231657](https://user-images.githubusercontent.com/24202939/46583304-634a2780-ca87-11e8-9510-12e5c4b6ad7e.jpg)

**Comment by blinkfox** [comment]
@pleuvoir 貌似这个没有其它好的办法处理，主要是手机端的宽度不够，而生成的日历图又必须得足够宽才行。

**Comment by pleuvoir** [comment]
> @pleuvoir 貌似这个没有其它好的办法处理，主要是手机端的宽度不够，而生成的日历图又必须得足够宽才行。

好的，谢谢
