### ISSUE TITLE
功能请求：每篇文章都能自定义转载规则

### ISSUE THREAD

**Issue by HarborZeng** [blinkfox/hexo-theme-matery#102]
现在的文章末尾是“转载请注明”，没有任何协议说明，希望@blinkfox 您可以在下一版中加入这样的功能。

比如：
- 禁止转载
- “知识共享”（CC协议）
- 全文付费转载
- 引流免费转载
- 其他自定义情况

**Comment by blinkfox** [comment]
哎，最近天天加班，没时间呢，你有精力的话帮我搞搞吧

**Comment by HarborZeng** [comment]
> 哎，最近天天加班，没时间呢，你有精力的话帮我搞搞吧

哈哈哈，辛苦。其实我最近也挺忙，毕设催得紧，文章还没写完。等忙完这阵子，可以弄弄这个功能。
