### ISSUE TITLE
prism line-number problem: prism插件行号问题定位

### ISSUE THREAD

**Issue by tabris233** [blinkfox/hexo-theme-matery#103]
[hexo-prism-plugin](https://github.com/ele828/hexo-prism-plugin) 插件的`line-number`功能在`matery`主题中显示有问题,如下:
![深度截图_选择区域_20190423133944](https://user-images.githubusercontent.com/29500388/56557385-5fb66200-65cd-11e9-996c-1c2934e98fb2.png)

翻了[hexo-prism-plugin](https://github.com/ele828/hexo-prism-plugin)的代码和`prism`本身发现并没有问题

**最后定位到为题在于**`<span aria-hidden="true" class="line-numbers-rows"></span>`的位置, 将这个标签`margin-left: 20px;`就能显示出`行号`了

我尝试这改了改`matery.css`文件,但效果并不是很理想,(请原谅我不会前端qaq)

![深度截图_选择区域_20190423134017](https://user-images.githubusercontent.com/29500388/56557527-fa16a580-65cd-11e9-899e-b4b41843f762.png)

只好麻烦前端大大了,qaq.

**Comment by mlch911** [comment]
> 我大概看了下，你改下主题样式文件 `/source/css/matery.css`，在 95 行位置的 `pre` 样式中 `padding`样式，改成下面这样就行：
> 
> ```css
> pre {
>     padding: 1.5rem 1.5rem 1.5rem 3.3rem !important;
>     margin: 1rem 0 !important;
>     background: #272822;
>     overflow: auto;
>     border-radius: 0.35rem;
>     tab-size: 4;
> }
> ```
> 
> 如果样式不合适，你可以再调整下。开启行号之后，行号的位置和代码的行可能没对齐，你可以注释掉 `code` 中的 `font-size` 的设置：
> 
> ```css
> code {
>     padding: 1px 5px;
>     font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace;
>     /* font-size: 0.91rem; */
>     color: #e96900;
>     background-color: #f8f8f8;
>     border-radius: 2px;
> }
> ```

改了pre后没有问题，但如果开启了代码折行，行号并不会折行
![image](https://user-images.githubusercontent.com/26565394/57070012-c0017e00-6d08-11e9-8cb8-8107205bef21.png)

**Comment by blinkfox** [comment]
这种就没啥好办法了，只能把折行去掉

**Comment by mlch911** [comment]
> 这种就没啥好办法了，只能把折行去掉

好吧
