### ISSUE TITLE
请问如何设置文章响应出现的时间

### ISSUE THREAD

**Issue by sshwy** [blinkfox/hexo-theme-matery#104]
滑动页面的时侯，后面的文章才显示出来，如果滑动太快，就感觉文章响应太慢。能否控制文章响应出现的延时呢（比如修改一下js，css）

**Comment by blinkfox** [comment]
你指的应该是 `AOS` 插件的对应卡片的显示时间，这个可以改 js 来调整哈，你可以看看 [aos](https://michalsnik.github.io/aos/) 的插件，然后改改 `matery.js` 文件即可。

**Comment by sshwy** [comment]
谢谢啦！问题已解决
