### ISSUE TITLE
博文末尾的文章卡片上的summary显示问题

### ISSUE THREAD

**Issue by zengchang94622** [blinkfox/hexo-theme-matery#106]
您好，我的博文末尾现在显示如下：
![image](https://user-images.githubusercontent.com/35031709/56951858-d4f8d880-6b73-11e9-9b46-e2fe4567fa8b.png)

现在显示的是正文中的公式，没有显示summary的内容，请问有没有什么办法修改呢？
谢谢～

**Comment by blinkfox** [comment]
应该是bug，`prev-next.ejs` 中没有增加 `summary` 的判断显示，你可以参考 `index.ejs` 中的改改。

**Comment by zengchang94622** [comment]
Thanks! 找您说的我改好了o(￣▽￣)ｄ

**Comment by zengchang94622** [comment]
@blinkfox Thanks! 找您说的我改好了o(￣▽￣)ｄ
