### ISSUE TITLE
navbar is broken

### ISSUE THREAD

**Issue by rikusen0335** [blinkfox/hexo-theme-matery#108]
I'm so happy to use this awesome them, thank you for making this!
Well, my issue is navbar is broken, but not completely.
See this GIF to know what's happening:
https://gyazo.com/3c11d59418986bc79cb22ae210fac3b5

Is this bug or bad my environment?

Ubuntu 18.04.2 LTS on Windows 10
hexo 3.8.0

**Comment by blinkfox** [comment]
Do you mean that Logo is not vertically centered?

You try to modify the 5th line of the theme `/layout/_partial/header.ejs` file and remove `class="waves-effect waves-light"`.

The changed code looks like this:

```html
<a href="<%- url_for() %>">
```

**Comment by blinkfox** [comment]
I don't know if you have solved the problem, you have not responded, I will close this issue.
