### ISSUE TITLE
1.0.3版本categories 和tags显示异常

### ISSUE THREAD

**Issue by githubzaibao** [blinkfox/hexo-theme-matery#113]
1.0.3版本。categories 和tags 主页面不显示分类和标签
![image](https://user-images.githubusercontent.com/18572669/57500565-6b688f00-7316-11e9-85aa-0860056e8983.png)，但是子分类页面正常显示 
![image](https://user-images.githubusercontent.com/18572669/57500594-820ee600-7316-11e9-8f76-c35fecfa1681.png)

**Comment by blinkfox** [comment]
应该是你 `categories` 和 `tags` 目录中的 `index.md` 文件没写对，你看我文档中的写法，前后需要加`---`

**Comment by githubzaibao** [comment]
![image](https://user-images.githubusercontent.com/18572669/57505779-467f1680-732c-11e9-9864-2b9c1e349368.png)
 不是z这样子么

**Comment by blinkfox** [comment]
嗯，是这样的，还有这个问题吗？

**Comment by githubzaibao** [comment]
是的，我看了生成的categories/index.html的文件 
![image](https://user-images.githubusercontent.com/18572669/57506778-724fcb80-732f-11e9-9e0d-2acb87ae42a4.png) 这样子了的，并没有分类的信息

**Comment by githubzaibao** [comment]
<div class="row">
    <div id="main-content" class="col s12 m12 l9">
        
<div id="artDetail">
    <div class="card">
        <div class="card-content article-info">
            <div class="row tag-cate">
                <div class="col s7">
                    
                          <div class="article-tag">
                            <span class="chip bg-color">无标签</span>
                          </div>
                    
                </div>
                <div class="col s5 right-align">

**Comment by githubzaibao** [comment]
找到问题了，非常感谢，文件没有保存导致没有生效
