### ISSUE TITLE
文章内的代码块显示的时候，如果单行文本过长，会溢出显示，很不美观

### ISSUE THREAD

**Issue by whoami1231** [blinkfox/hexo-theme-matery#114]

**Comment by blinkfox** [comment]
有图吗？不太了解你说的什么意思

**Comment by whoami1231** [comment]
![PHM5TC`1O)O RHXCZNFJTCM](https://user-images.githubusercontent.com/40268529/58075952-8b803400-7bdb-11e9-9925-510f42fee115.png)

**Comment by whoami1231** [comment]
在群里解决了，是hexo的默认代码块样式不太适合这个主题的原因
