### ISSUE TITLE
“开始阅读”按钮跳转锚点时，滚动效果不生效

### ISSUE THREAD

**Issue by GavinTao1219** [blinkfox/hexo-theme-matery#116]
首页的“开始阅读”按钮指向锚点#indexCard，点击按钮可以跳转到指定锚点，但是没有滚动效果，是一下子就直接跳过去的。

在博客里面，toc每章节的锚点跳转有滚动效果，就唯独首页的“开始阅读”那个按钮没有滚动效果。

我看作者的首页上是有滚动效果的。我对于前端代码不太熟悉，麻烦作者大神稍微给我讲一下这个问题该怎么debug，谢谢！

**Comment by blinkfox** [comment]
`#indexCard` 是利用的浏览器的锚点机制去查找的，查找 id 为`indexCard`的 html 元素，并跳转到此元素，在 `index.ejs`文件中就有这个元素，你的没跳转，应该是没有生成相关的内容引起的吧，你自己试试。

**Comment by GavinTao1219** [comment]
不是的，大神。。。可能是我没表述清楚。。。
我遇到的状况是，能够跳转，但是跳转的时候没有滚动的特效，是一下子就蹦过去了。我没弄明白是哪段JavaScript负责这个跳转时的滚动特效

**Comment by blinkfox** [comment]
浏览器的锚点跳转本来就是这样的

**Comment by GavinTao1219** [comment]
我看你的主页https://blinkfox.github.io，点击“开始阅读”那个按钮，就有滚动的特效，请问这个是怎么实现的啊？

**Comment by blinkfox** [comment]
一样的代码

**Comment by mylovesaber** [comment]
老哥你解决这问题没有？我也遇到了，重新建了个文件夹初始化了个新的hexo然后git clone了主题，设置成作者主题，没有动任何其他的信息，照样没有首页点开始阅读就滚动跳转效果而是闪现过去的，群里问了也都说不知道没遇到过

**Comment by GavinTao1219** [comment]
@mylovesaber 解决了，我是直接在index-cover.ejs结尾<script>里面加了一个滚动过去的js方法，代码如下：

```javascript
$(document).ready(function(){
    $( "a.scrollLink" ).click(function( event ) {  
        event.preventDefault();  
        $("html, body").animate({ scrollTop: $($(this).attr("href")).offset().top }, 500);  
    });  
});
```

然后在第68行，调用一下，就可以了
```html
<a href="#indexCard" class="waves-effect waves-light btn scrollLink">
```

**Comment by mylovesaber** [comment]
> @mylovesaber 解决了，我是直接在index-cover.ejs结尾<script>里面加了一个滚动过去的js方法，代码如下：
> 
> ```js
> $(document).ready(function(){
>     $( "a.scrollLink" ).click(function( event ) {  
>         event.preventDefault();  
>         $("html, body").animate({ scrollTop: $($(this).attr("href")).offset().top }, 500);  
>     });  
> });
> ```
> 
> 然后在第68行，调用一下，就可以了
> 
> ```
> <a href="#indexCard" class="waves-effect waves-light btn scrollLink">
> ```

感谢，问题解决了
