### ISSUE TITLE
网站logo与头像不一致的情况下会有问题

### ISSUE THREAD

**Issue by TroyIrvo** [blinkfox/hexo-theme-matery#117]
在使用的过程中发现网站logo与favicon两个图标不一样的时候会有图片切换动作。并且切换成手机效果展示。侧滑的头像也有这种问题。

**Comment by blinkfox** [comment]
我不太懂你的样式，这两个是各自独立渲染的，也不会相互影响

**Comment by TroyIrvo** [comment]
@blinkfox 如果有时间，你可以访问一下我的这个网站，我就是把这两个图标换了不是同一个。在打开网页的时候就会有图片切换的动作。然后被其中一个图片覆盖。  https://muzilove.cn/

**Comment by TroyIrvo** [comment]
`<img src="/favicon.png" data-original="/medias/logo.png" class="logo-img circle responsive-img">`
对比你的网站代码。我发现好像是渲染的时候多了data-original 这个属性。但是我看源header.ejs文件里面并没有这个属性值。不知道怎么弄上去的。

**Comment by blinkfox** [comment]
这个 JS 是你自己写的吗？就是因为这段 js 引起的吧

![Snip20190609_1](https://user-images.githubusercontent.com/4027734/59157704-c4783e00-8ae1-11e9-809f-dff409bf7075.png)

**Comment by TroyIrvo** [comment]
@blinkfox 不是我自己写的噢。我就直接git clone下来的。只改了config配置文件。没有改过其它东西。

**Comment by TroyIrvo** [comment]
我发现打包以后的确有这段js。但是我源文件一个个看愣是没有发现。。 @blinkfox (((φ(◎ロ◎;)φ)))

**Comment by TroyIrvo** [comment]
感谢@blinkfox,我重新下载主题就可以了。
