### ISSUE TITLE
字体颜色

### ISSUE THREAD

**Issue by mylovesaber** [blinkfox/hexo-theme-matery#118]
请教下比如你的博客首页中间和左上角的闪烁之狐字体颜色在哪里可以调整啊？我看F:\blog\themes\hexo-theme-matery\source\css\matery.css里面有不少可以改颜色的地方，但具体是什么地方可以调整啊？

**Comment by mylovesaber** [comment]
我把半透明的单色遮盖去掉了，感觉好看不少，结果白色字体在背景图的衬托下经常基本处于不可见状态。。想改成别的颜色，老哥可否告知下呢？感谢

**Comment by blinkfox** [comment]
@mylovesaber 这个就你需要自己在 `matery.css` 中单独对这些你修改的地方“加或者改”样式了。
