### ISSUE TITLE
关于文章特色图的路径问题

### ISSUE THREAD

**Issue by XiaoSenLuo** [blinkfox/hexo-theme-matery#12]
在添加img属性时，使用相对路径有些问题，图片位于博客根目录source/images/，添加属性img：images/，在首页图片显示没问题，但是在归档页，图片不显示。如果使用绝对路径，即http：//路径，则首页，归档页图片显示都没问题。有解决的办法吗？能改进一下吗？

**Comment by blinkfox** [comment]
@XiaoSenLuo 好，有空我看看

**Comment by blinkfox** [comment]
@XiaoSenLuo 我试了下，在`img`值的前面需要加一个斜杠就行了，写成这样：

```yml
img: /images/xxx/xxx.jpg
```
