### ISSUE TITLE
加載音樂模塊的問題

### ISSUE THREAD

**Issue by Guwalgiyakuan** [blinkfox/hexo-theme-matery#122]
首先感謝@ blinkfox製作的精美主題。
剛安裝完主題沒有修改 musics.json 文件內容的時候是可以加載出音樂模塊的。
後來自己改了 musics.json 內容後就加載不出來播放器了，看之前的 issues 也有提這個問題。後來幾番修改內容發現
{
	"name": "I m Free",
	"artist": "Terry Dexter",
	"url": "/medias/music/music2.mp3",
	"cover": "/medias/music/cover2.png"
},
段落裏雙引號""中間的的內容有如果包含單引號就加載不出來播放器
例如 "name": "I'm Free", 這樣就失效了。

以上爲個人發現的問題，不知道在別人的配置裏是否能重現。

**Comment by blinkfox** [comment]
@Guwalgiyakuan 应该是 hexo 通过 `site.data` 解析 JSON 文件的问题。

**Comment by Guwalgiyakuan** [comment]
@blinkfox 是否有改正方法？还是说目前只能避免使用 `'` 来避开这个错误？

**Comment by blinkfox** [comment]
@Guwalgiyakuan 避开吧，这个是 hexo 本身解析 JSON 文件的问题了

**Comment by Guwalgiyakuan** [comment]
Thanks
