### ISSUE TITLE
文章日历显示为英文

### ISSUE THREAD

**Issue by L1cardo** [blinkfox/hexo-theme-matery#126]
我已经设置了博客语言为 ‘zh-CN’ ，但是文章日历还是英文的，其他地方都变成了中文，只有文章日历是英文

![3745E4BE-ED8D-4716-93C9-4DC2B462A859](https://user-images.githubusercontent.com/33802186/60555236-53d5e180-9d6e-11e9-912d-82bf09a3db3e.png)

**Comment by blinkfox** [comment]
我不晓得你怎么设置的，没法排查你的问题。你需要在根 `_config.yml` 文件中将 `language` 的值设置成 `zh-CN`。

```yaml
language: zh-CN
```

**Comment by L1cardo** [comment]
我已经将language设置成了 zh-CN
并且也没有对主题的其他地方进行改动，只是改了配置文件。
我也尝试了多次的卸载重装，还是这样的，其他地方都是中文正常显示，只有文章日历显示英文。

**Comment by blinkfox** [comment]
你的项目源码能发一份，我看看吗？

**Comment by L1cardo** [comment]
[项目地址](https://github.com/L1cardo/l1cardo.github.io)
谢谢大佬百忙之中抽空时间，谢谢！

**Comment by blinkfox** [comment]
这个不是源码吧，这是编译之后的，我看编译之后的就已经是英文的了

**Comment by L1cardo** [comment]
嗯嗯 好的，那我中午回去给你发源码
