### ISSUE TITLE
你好，gitalk评论未找到相关问题

### ISSUE THREAD

**Issue by czbcxy** [blinkfox/hexo-theme-matery#127]
今天在使用您的主题搭建博客时遇到了一个难题，gitalk评论时总是报错，百度了没有找到一个号的答案，“未找到相关的 Issues 进行评论 请联系 @czbcxy 初始化创建”，希望得到指点，谢谢。

**Comment by blinkfox** [comment]
需要在正式的页面中访问下就行了，就会自动初始化。

**Comment by jaredtech** [comment]
建议在_config 文件中给一个gitalk等评论相关的配置例子。最开始不会配置去网上随意搜了一个配置gitalk的文章，弄了半天评论不了。我最开始时这样配置的
`gitalk:
  enable: true
  owner: 'jaredtech'
  repo: 'jaredtech.github.io'
  oauth:
    clientId: '***'
    clientSecret: '***'
  admin: jaredtech
`
报了个“toLowerCase" on null 之类的问题。
搞了半天，最后尝试去掉单引号才OK了...

**Comment by blinkfox** [comment]
这个没再继续回复的话，就要关闭掉这个 `issue` 了。

**Comment by doutv** [comment]
> 建议在_config 文件中给一个gitalk等评论相关的配置例子。最开始不会配置去网上随意搜了一个配置gitalk的文章，弄了半天评论不了。我最开始时这样配置的
> 
> ```
>   enable: true
>   owner: 'jaredtech'
>   repo: 'jaredtech.github.io'
>   oauth:
>     clientId: '***'
>     clientSecret: '***'
>   admin: jaredtech
> ```
> 
> 报了个“toLowerCase" on null 之类的问题。
> 搞了半天，最后尝试去掉单引号才OK了...

建议在README或者_config.yml里面加一个配置示例
