### ISSUE TITLE
文章末尾推荐列表样式问题

### ISSUE THREAD

**Issue by sherlonWang** [blinkfox/hexo-theme-matery#128]
滑到文章末尾推荐文章时，列表上的本篇tag跑到最右面去了，如下图：
![](https://i.loli.net/2019/07/14/5d2b3a1a0efbd62817.png)

**Comment by blinkfox** [comment]
没遇到过你这种情况呢。。。

**Comment by sherlonWang** [comment]
![image](https://user-images.githubusercontent.com/44674881/61212346-91eee000-a734-11e9-98a8-f074f2864ebf.png)
是不是由于这篇文章在推荐列表出现2次，某个ID重复了导致的样式问题？

**Comment by sherlonWang** [comment]
![image](https://user-images.githubusercontent.com/44674881/61214138-ac778800-a739-11e9-96b6-97fc6d98fe21.png)
好像不是重复的问题，我重新上传了篇文章还是会出现这种情况😶
## 浏览器版本：Google Chrome 75.0.3770.90（正式版本） （64 位）

**Comment by blinkfox** [comment]
@sherlonWang 肯定是样式问题，不晓得你改啥了，你把博客链接发给我，我看看

**Comment by sherlonWang** [comment]
@blinkfox  https://www.sherlon.wang/

**Comment by sherlonWang** [comment]
@blinkfox 哎忘更新了，更新了一下就可以啦😷
