### ISSUE TITLE
关于一点小缺陷

### ISSUE THREAD

**Issue by Yof3ng** [blinkfox/hexo-theme-matery#13]
social link在页面头部引用的缺陷（翻页时出现）

![](https://i.loli.net/2018/10/14/5bc2dbd3406a5.png)

![](https://i.loli.net/2018/10/14/5bc2da051400f.png)

修改措施：

将bg-cover.ejs里面的第24行

`<% if (is_home()) { %>`

改为

`<% if (is_home() && page.current === 1) { %>`

即可

-------------

新版本首页底部出现一白条，十分难受

![](https://i.loli.net/2018/10/14/5bc2ddcc51640.png)

希望作者大佬慢慢完善，加油鸭嘻嘻嘻

**Comment by Yof3ng** [comment]
star已点亮！

**Comment by blinkfox** [comment]
@Yof3ng 谢谢指出问题，`page.current === 1`的已经加了，关于底部出现空白的，是故意留的，你想改成满屏的话，可以直接修改`index.ejs`中第四行 banner 的高度为`100vh`即可：

```css
.index-cover {
    height: 100vh;
}
```

**Comment by Yof3ng** [comment]
好的谢谢
