### ISSUE TITLE
代码高亮不显示

### ISSUE THREAD

**Issue by godweiyang** [blinkfox/hexo-theme-matery#130]
![image](https://user-images.githubusercontent.com/18682256/61549836-9f350300-aa83-11e9-80f1-21b78423cc60.png)

如图，刚开始是可以显示高亮的，现在突然全不行了，卸了重装插件也没用，卸了用自带的highlight也不能高亮了。

**Comment by godweiyang** [comment]
而且头文件会自动不显示出来。。。

**Comment by blinkfox** [comment]
代码需要加上编程语言的名称

**Comment by godweiyang** [comment]
> 代码需要加上编程语言的名称

您好，是加了的。现在我解决了，原来是跟mathjax插件冲突了。我mathjax没有用原来默认的插件，换的是kramed，然后改了那两个正则表达式，然后就和就这个代码高亮冲突了。我尝试了还是用原来默认的mathjax插件marked那个，然后改他的那两行正则表达式，然后就mathjax和代码高亮全能用了。
还是非常感谢您，主题做得也非常好，文档写的也非常详细！

**Comment by blinkfox** [comment]
好，解决了就行。
