### ISSUE TITLE
你好，_data文件报错的问题

### ISSUE THREAD

**Issue by blankmiss** [blinkfox/hexo-theme-matery#132]
每当我把_data这个文件夹放在blankmiss.github.io/source/_data/
里
 hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: EACCES: permission denied, scandir '/data/data/com.termux/files/home/blankmiss.github.io/source/_data'
而且在source这个目录下连一个空文件夹也不能添加
也不能跟换主题图片

**Comment by blankmiss** [comment]
说错了是_data在这个目录blankmiss.github.io/source/_data/

**Comment by blankmiss** [comment]
不知道为什么我连在source/_posts/写文章 在hexo g 后就会报错
报错信息 如下 hexo g
INFO  Start processing
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/data/data/com.termux/files/home/blankmiss.github.io/source/_posts/中文测试.md'
Emitted 'error' event at:
    at /data/data/com.termux/files/home/blankmiss.github.io/node_modules/graceful-fs/graceful-fs.js:207:14
    at /data/data/com.termux/files/home/blankmiss.github.io/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/data/data/com.termux/files/home/blankmiss.github.io/source/_posts/中文测试.md'

**Comment by blinkfox** [comment]
@blankmiss 我看错误信息，应该是你执行 `hexo g` 时，没有访问这个文件夹的权限引起的。

**Comment by blankmiss** [comment]
那么我得怎么样解决这个问题呢，themes下主题图片的问题我已经解决了，只是苦于不能加那两个json

**Comment by blinkfox** [comment]
@blankmiss 这个问题现在还存在吗？

**Comment by blinkfox** [comment]
@blankmiss  这个 `issue` 你没有再后续回复的话，我就关闭这个 `issue` 了。
