### ISSUE TITLE
Uncaught ReferenceError: searchFunc is not defined

### ISSUE THREAD

**Issue by nekojan** [blinkfox/hexo-theme-matery#134]
I receive this error after I deploy the site to the server. All is fine when running on localhost.

It seems search.js isn't loaded. The path looks fine. Any suggestion?

<img width="440" alt="Screen Shot 2019-08-09 at 4 00 07 AM" src="https://user-images.githubusercontent.com/6083567/62767552-91f3ae80-ba5a-11e9-917c-a5f0901be31f.png">
<img width="533" alt="Screen Shot 2019-08-09 at 4 09 50 AM" src="https://user-images.githubusercontent.com/6083567/62768048-9a001e00-ba5b-11e9-85ba-1c3cf615dad8.png">
<img width="179" alt="Screen Shot 2019-08-09 at 4 01 09 AM" src="https://user-images.githubusercontent.com/6083567/62767554-91f3ae80-ba5a-11e9-8aac-645eeb9576cb.png">

**Comment by blinkfox** [comment]
@nekojan 要看你的 `public` 的目录下有没有 `search.xml` 文件，没有的话，说明就有问题。

**Comment by nekojan** [comment]
Yes, there's `search.xml`

<img width="205" alt="Screen Shot 2019-08-09 at 10 23 31 AM" src="https://user-images.githubusercontent.com/6083567/62790021-ce8dcd00-ba8f-11e9-8134-5216dee06a33.png">

**Comment by nekojan** [comment]
It works now. I reinstall hexo-generator-search and add `content` field under the `search` field in `_config.yml`

```
search:
  path: search.xml
  field: post
  content: true
```
