### ISSUE TITLE
hexo s 本地预览正常，hexo d部署到page没有图片，样式

### ISSUE THREAD

**Issue by FM-FE** [blinkfox/hexo-theme-matery#135]

**Comment by FM-FE** [comment]
![image](https://user-images.githubusercontent.com/45055889/62933601-28c2c100-bdf5-11e9-99d7-f3c304fc081a.png)
网上查到，需要设置root为/blog，但是设置之后，本地预览也不正常了

**Comment by blinkfox** [comment]
@FM-FE 没弄过你这种配置，不晓得。你试试 `root: /blog`，`url: https://fm-fe.github.io`试试。

**Comment by FM-FE** [comment]
我解决这个问题了
只修改项目为fm-fe.github.io
这样，博客地址就是一级目录，不需要配置root
