### ISSUE TITLE
如何更换首页背景图？

### ISSUE THREAD

**Issue by FM-FE** [blinkfox/hexo-theme-matery#136]
![cover(1)](https://user-images.githubusercontent.com/45055889/62998057-e5bc2880-be9c-11e9-9992-e6303f9de059.jpg)

就是这一张

**Comment by FM-FE** [comment]
我尝试把medis目录下的cover.jpg删掉换成其他同名的图片
但是，并不管用

**Comment by blinkfox** [comment]
应该有缓存吧，你 `hexo clean` 一下呢

**Comment by FM-FE** [comment]
哦，我找到问题了，medias/cover.jpg，这一张不是封面，不知道是什么作用
封面图片的存储路径在，medias/banner/
下面的七张图片，每天换一张

其实，说明文档里写过，但我之前完全没接触过前端，太菜了，没理解banner是啥

谢谢您
