### ISSUE TITLE
主题seo方面的一些问题

### ISSUE THREAD

**Issue by walersix** [blinkfox/hexo-theme-matery#14]
您好：
今天使用主题遇到了这些问题，跟您反馈一下
1、首页标题，`titile` 对seo是特别重要的，首页logo位置的文字我看您调用的是`title` 使用后发现用seo写标题的话，
![](https://ws1.sinaimg.cn/large/005xcdLbly1fw81bezx1dj309903e74y.jpg)
这里也会出现很多字的，十分不美观的，测试发现修改 `themes/hexo-theme-matery/layout/_partial/header.ejs `
 ![](https://ws1.sinaimg.cn/large/005xcdLbly1fw81c2o5w9j30jb02xt8p.jpg)
这个文件更改调用可以解决，您可以了解一下

2、永久链接问题，我设置的是 `:category/:id` 这样的，解析之后发现页面的链接变成了`http://127.0.0.1:4000/jiaocheng/cjn8s34jx0000astyk11m72z4 ` 这样，也可以访问，但是页面是没有`.html`后缀，于是我修改成 `:category/:id.html`这样才没问题，请教一下，这是什么原因a?

3、单独文章页面我发现`head`里面调用的是首页的`tatle` `description` `keywords` 这对seo来说是特别严重的，拿您的博客来说![](https://ws1.sinaimg.cn/large/005xcdLbly1fw80wts22fj30zs0niacm.jpg)  可以看到百度收录了三条，不同的链接标题描述抓取的都是一样的，关键词搜索很难有排名的，希望可以增加一个可以修改各个页面tdk选项的功能或者文章页面的tdk不要跟主页一样都行的，非常感谢，主题很棒！

**Comment by blinkfox** [comment]
@walersix 多谢你的建议，后续会修正。关于你说的第二个疑问，你的永久链接格式后面需要再加一个`/`吧，即：

```yml
permalink: :category/:id/
```

**Comment by walersix** [comment]
> @walersix多谢你的建议，后续会修正关于你说的第二个疑问，你的永久链接格式后面需要再加一个。`/`吧，即：
> 
> ```yaml
> 永久链接 :: category /：id /
> ```

好的，谢谢啦

**Comment by blinkfox** [comment]
@walersix 你好，你提的SEO问题我已修复。
