### ISSUE TITLE
 TOC 的相关问题和视图建议

### ISSUE THREAD

**Issue by TigerChain** [blinkfox/hexo-theme-matery#141]
首先此主题非常棒已经使用感谢作者，想咨询一下能否在单个文章中设置 TOC 的那部分显示比如设置 h2 的显示，其它不显示，不想在全局中去修改，全局一改都改变了，再一个能否添加一个文章列表视图功能，现在是宫格视图，能否给一个按钮一健切换「建议」

**Comment by blinkfox** [comment]
目前可以为单个文章设置是否启用 `TOC`，但是不能做到你说的为每篇文章的部分显示设置，这种太个性化了，而且 TOC 本来就是用标题来控制的，你不想显示那些标题，你就不做成标题就行了啊。
文章列表视图功能，目前没有计划再改了，因为这个改动比较大。

**Comment by TigerChain** [comment]
> 目前可以为单个文章设置是否启用 `TOC`，但是不能做到你说的为每篇文章的部分显示设置，这种太个性化了，而且 TOC 本来就是用标题来控制的，你不想显示那些标题，你就不做成标题就行了啊。
> 文章列表视图功能，目前没有计划再改了，因为这个改动比较大。

ok ths
