### ISSUE TITLE
黑白网页

### ISSUE THREAD

**Issue by icespite** [blinkfox/hexo-theme-matery#142]
您好，请问该如何制作一个文章，使得打开后整个网页变为黑白色，我试着跳过md文件渲染，直接修改public里面的HTML，但是失败了，而且clean之后整个public文件消失，而将html直接放在source文件夹下面的_post文件夹，显示不正确，烦请您能给予回复，谢谢。

**Comment by blinkfox** [comment]
你描述的情况我不太懂，有效果图吗？你想要达到效果的话，得自己在 `ejs` 文件里面去改了。

**Comment by icespite** [comment]
您好，我想要达到打开一个文章之后变成悼念的黑白色的样子，但是一直不会弄




------------------ 原始邮件 ------------------
发件人: "blinkfox"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 中午11:00
收件人: "blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com>;
抄送: "Icepan"<1430707904@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [blinkfox/hexo-theme-matery] 黑白网页 (#142)




你描述的情况我不太懂，有效果图吗？你想要达到效果的话，得自己在 ejs 文件里面去改了。

**Comment by icespite** [comment]
![image](https://user-images.githubusercontent.com/50160905/63564065-1fc0b500-c596-11e9-83d7-e96dbc37663f.png)

**Comment by icespite** [comment]
仅仅这一个博客修改为这个样式就可以

**Comment by blinkfox** [comment]
要做成这样的话，得去改各个地方的样式，但是也做不到仅为一个博客生效的场景。

**Comment by blinkfox** [comment]
这个需求应该是不会去实现的，我打算关闭这个 `issue` 了。
