### ISSUE TITLE
benner不能正常显示

### ISSUE THREAD

**Issue by chen1749144759** [blinkfox/hexo-theme-matery#148]
页面benner只能显示出一张图片,需要在哪里配置一下吗? [我的页面地址](http://chenzeshi.xyz/)

**Comment by blinkfox** [comment]
@chen1749144759 本来就只有一页，你可以把文章设置为封面显示，才会在 `banner` 中显示，具体的你看看文档吧。

**Comment by chen1749144759** [comment]
谢谢大佬 已完成

在 2019年9月3日，上午12:09，blinkfox <notifications@github.com<mailto:notifications@github.com>> 写道：


@chen1749144759<https://github.com/chen1749144759> 本来就只有一页，你可以把文章设置为封面显示，才会在 banner 中显示，具体的你看看文档吧。
