### ISSUE TITLE
建议将留言板改为可配置

### ISSUE THREAD

**Issue by EscapeLife** [blinkfox/hexo-theme-matery#153]
> 建议将留言板改为可配置的功能，因为很多人并不需要这个功能，感谢！

**Comment by EscapeLife** [comment]
@blinkfox 麻烦有时间的话，看看👀  感谢感谢👍

**Comment by blinkfox** [comment]
嗯，好，有空我看看

**Comment by blinkfox** [comment]
@EscapeLife 话说留言板这个不需要的话，让他去掉菜单里面的链接就行了吧，而且删掉 `contact` 页就行。

**Comment by blinkfox** [comment]
把这个在文档里面写出来是可选的就行了吧。

**Comment by blinkfox** [comment]
我改了下文档，把留言板功能写成“可选的”了，把菜单默认注释了，写明如果要激活此功能，需要取消注释
