### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by liuzhihangs** [blinkfox/hexo-theme-matery#161]
- 个别文章没有tag, 或者summary 比较短的时候会比别的少一部分, 从而导致下面的会向上提高, 整体的排版就会出现高低不平.
- 有没有推荐的图片大小, 还有js放在github 感觉加载比较慢, 有推荐处理方式么
- 今天发现更新内容很多..  👍

**Comment by L1cardo** [comment]
你说的排版高低问题有图片吗？  我没碰到过哎。

**Comment by liuzhihangs** [comment]
@L1cardo 

develop 提交的 daovoice 应该是和 top互相冲突
![image](https://user-images.githubusercontent.com/26057042/64968146-42639680-d8d4-11e9-91ba-4c454f56d14b.png)



![image](https://user-images.githubusercontent.com/26057042/64967787-b3ef1500-d8d3-11e9-91fe-5b9afdaf02c7.png)

![image](https://user-images.githubusercontent.com/26057042/64967874-cf5a2000-d8d3-11e9-94eb-e9cc81c4333d.png)

**Comment by blinkfox** [comment]
@liuzhihangs 瀑布流布局就是这样的，高低错落。

**Comment by L1cardo** [comment]
@liuzhihangs  daovoice可以在后台调整位置，你自己看一下

**Comment by blinkfox** [comment]
这个还有什么问题吗？没有的话，就关闭掉这个 `issue` 吧
