### ISSUE TITLE
是否考虑增加文章目录？

### ISSUE THREAD

**Issue by gorkys** [blinkfox/hexo-theme-matery#17]
第一眼看到你这个主题就觉得很喜欢，看了一遍demo。
觉得可以在访问文章的右侧加上一个文章的目录这样更方便阅读。

**Comment by blinkfox** [comment]
@gorkys 你说的是`TOC`功能吧，是有的，可以在主题配置中，自己配置是否激活这个功能，示例`demo`中并未开启这个。

**Comment by gorkys** [comment]
`TOC`的位置应该是在文章的开头吧。我还没有部署好，一会儿我再看看。不知道 是不是像segmentfault的那种目录。

**Comment by gorkys** [comment]
已经搭建好了，开启了是想要的功能。这个issue可以关闭了。
