### ISSUE TITLE
linux下由于系统问题这个主题没法启动

### ISSUE THREAD

**Issue by whoami1231** [blinkfox/hexo-theme-matery#171]
由于本套主题采用了jquery重型库，所以hexo启动的时候会出现字符溢出的错误

**Comment by whoami1231** [comment]
![](https://s2.ax1x.com/2019/09/17/noSJRU.png)

**Comment by Five-great** [comment]
你这个是权限问题 请用 git base z执行命令 不要cmd

**Comment by whoami1231** [comment]
啊,我这个系统是deepin的，不是window,更没有git bash

**Comment by blinkfox** [comment]
@whoami1231 我有空看看

**Comment by blinkfox** [comment]
@whoami1231 我用 `deepin` 和 `ubuntu` 都试了，没发现你这样的问题。

**Comment by harvies** [comment]
> 由于本套主题采用了jquery重型库，所以hexo启动的时候会出现字符溢出的错误

$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -p
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
老哥试试 我的ArchLinux没问题
![DeepinScreenshot_select-area_20190927233740](https://user-images.githubusercontent.com/16585330/65782310-f7713b00-e17f-11e9-83ca-a42e8f7445ff.png)

**Comment by whoami1231** [comment]
> > 由于本套主题采用了jquery重型库，所以hexo启动的时候会出现字符溢出的错误
> 
> $ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
> $ sudo sysctl -p
> https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
> 老哥试试 我的ArchLinux没问题
> ![DeepinScreenshot_select-area_20190927233740](https://user-images.githubusercontent.com/16585330/65782310-f7713b00-e17f-11e9-83ca-a42e8f7445ff.png)

谢啦老哥，问题解决了
