### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by L1cardo** [blinkfox/hexo-theme-matery#173]
想知道这里的高度是哪个控制的？找了半天没找到
![截屏2019-09-18下午1 33 25](https://user-images.githubusercontent.com/33802186/65114411-43eaa700-da19-11e9-9f9c-d6466721f9a7.png)

**Comment by blinkfox** [comment]
`matery.css` 文件中对 `index-cover` 的 class 设置了样式高度为 `100vh`

**Comment by L1cardo** [comment]
嗯嗯  谢谢了！
