### ISSUE TITLE
valine 评论排版问题

### ISSUE THREAD

**Issue by shenqizhi** [blinkfox/hexo-theme-matery#177]
如图
![image](https://user-images.githubusercontent.com/32361081/65214561-08191580-dadd-11e9-874c-8274dd772e4c.png)

请问大佬，怎么解决。css 是在哪里的，感谢

**Comment by blinkfox** [comment]
后续解决，你先看看这个 [issue](https://github.com/blinkfox/hexo-theme-matery/issues/97)，其他人有解决方案。

**Comment by shenqizhi** [comment]
还是不行，无论`public`还是修改博客根目录下面css，js的都不行。是我哪里搞错了吗，请大佬略指一二。还有，如我上图所示，评论左边的间隙不够，用加大的字体就显示不全，建议加宽，这个我在`valine.ejs`修改了就生效，真奇怪。。。。。

**Comment by L1cardo** [comment]
@shenqizhi 这个问题修复了，关闭了吧
