### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by L1cardo** [blinkfox/hexo-theme-matery#179]
这几天提交的代码太多了，导致出现了一个小问题。最新的`master`分支也存在。
由于新添加的功能以及改写的代码太多，我没有任何头绪

当浏览器窗口缩小到一定宽度时，在浏览器窗口会出现白条。
发现原来浏览器窗口比整个`html`还大，博主有什么头绪吗？
![截屏2019-09-19下午5 21 27](https://user-images.githubusercontent.com/33802186/65232044-137f3780-db03-11e9-8ae8-4ffb6ff176e0.png)

**Comment by blinkfox** [comment]
找到具体的原因，修改呗！

**Comment by L1cardo** [comment]
我找了两天，都不知道该怎么解决..... :cry:

**Comment by L1cardo** [comment]
应该是这个的原因，但是我不知道这个的宽度是哪里控制的，能讲一下吗？
![截屏2019-09-21下午12 44 28](https://user-images.githubusercontent.com/33802186/65368211-cf11aa00-dc70-11e9-8817-f7a6b8ea407e.png)
