### ISSUE TITLE
请教一下关于加密功能的问题

### ISSUE THREAD

**Issue by FadingWinds** [blinkfox/hexo-theme-matery#180]
Blinkfox你好，首先非常感谢制作出了如此精美的hexo主题！
有两个关于加密功能的问题想请问一下：
1. 可不可以做到对某一类别进行加密，达到只要输入了类别的密码就可以访问这个类别下所有的文章的效果？如果可以的话麻烦告知一下修改思路_(:з)∠)_谢谢！
2. 输入密码的对话框要怎样自定义呢？比如我想设置密码输入错误后不跳转回主页而是停留在当前页面。

另外还有一个不知道是不是bug的小问题，我激活了音乐播放器自动播放的功能，但是直接访问主页并不会自动播放音乐，从别的页面返回到主页就可以，试了几个设备都是这样……

**Comment by blinkfox** [comment]
`hexo` 是静态页面，目前的密码解决方案只是基于浏览器 `prompt` 的阻断功能来做的，并非真正的安全，只能防君子，防不了小人。要真正安全，静态页面目前是做不到的。
所以，第一个和第二个问题，目前都不行。
音乐播放器那个由于使用的别人的播放器插件，返回首页不能自动播放的话，那就没法了。

**Comment by FadingWinds** [comment]
好的，非常感谢~
