### ISSUE TITLE
首页轮播图可以关闭吗

### ISSUE THREAD

**Issue by harvies** [blinkfox/hexo-theme-matery#190]

**Comment by L1cardo** [comment]
![截屏2019-09-27下午8 56 55](https://user-images.githubusercontent.com/33802186/65770774-5e372a00-e169-11e9-9d90-0b7bebf11635.png)

**Comment by harvies** [comment]
全部改为false还是会显示

**Comment by EscapeLife** [comment]
@harvies 情况下缓存试试看

**Comment by harvies** [comment]
> @harvies 情况下缓存试试看

还是不行，我看代码是没有做开关
我自己改了代码是可以隐藏了，不过样式有点丑
![image](https://user-images.githubusercontent.com/16585330/65828764-0ddadc00-e2d1-11e9-9e0b-ccb9c6c7f7a0.png)
![image](https://user-images.githubusercontent.com/16585330/65828782-2f3bc800-e2d1-11e9-98b9-19f4185791d8.png)

**Comment by L1cardo** [comment]
我想知道你说的轮播是什么意思。上面的设置为false就不会显示轮播，我亲测没问题

**Comment by blinkfox** [comment]
为了简单处理，所以是没关闭播放效果的，只是没有“轮”而已的，看到的效果差别不多，就是拖拽页面时会有些空白而已，影响不大。

**Comment by harvies** [comment]
> 为了简单处理，所以是没关闭播放效果的，只是没有“轮”而已的，看到的效果差别不多，就是拖拽页面时会有些空白而已，影响不大。

好的，谢谢

**Comment by TajangSec** [comment]
> 为了简单处理，所以是没关闭播放效果的，只是没有“轮”而已的，看到的效果差别不多，就是拖拽页面时会有些空白而已，影响不大。

请问这个拖拽空白怎么取消，很影响体验

**Comment by TajangSec** [comment]
> 为了简单处理，所以是没关闭播放效果的，只是没有“轮”而已的，看到的效果差别不多，就是拖拽页面时会有些空白而已，影响不大。

请问这个拖拽空白怎么取消，很影响体验，我等两年了，还是无法解决
