### ISSUE TITLE
valine不舒服，来必力太慢，大佬有准备添加畅言的支持吗哈哈

### ISSUE THREAD

**Issue by Mculover666** [blinkfox/hexo-theme-matery#192]

**Comment by L1cardo** [comment]
畅言添加很简单，5分钟就能搞定。但是你去看看网络上对于畅言的评价，而且畅言有广告。

**Comment by Mculover666** [comment]
> 畅言添加很简单，5分钟就能搞定。但是你去看看网络上对于畅言的评价，而且畅言有广告。

噢噢，明白了，看来这几个评论系统中还是选择gittalk了

**Comment by L1cardo** [comment]
@Mculover666 我这几天研究了一下，畅言需求多的话可以加进去，但是网络上对畅言的评价不好，而且也有广告。所以就不弄了吧。感觉可以关闭了。

**Comment by L1cardo** [comment]
valine还是很好用的

**Comment by L1H0n9Jun** [comment]
可以考虑一下 gitalk。

**Comment by Samven7** [comment]
为什么代码块分成两块了，一边显示行号，一边显示代码。

**Comment by Mculover666** [comment]
> 为什么代码块分成两块了，一边显示行号，一边显示代码。

是说我的博客吗？我也不太清楚呀，一直想解决一下这个问题
