### ISSUE TITLE
标题栏是否可以固定在上部，不随页面滚动

### ISSUE THREAD

**Issue by huanglm98** [blinkfox/hexo-theme-matery#195]
能否让标题栏固定呢，因为有时候随页面一起滑动不是很美观

**Comment by L1cardo** [comment]
没有明白你的意思，标题栏是一直在最上面啊

**Comment by deviljinc** [comment]
他的意思是让标题栏固定在网页最上面，
而不是跟随页面滑动的时候，固定在浏览器最上面。
简单点就是往下滑动的时候看不到标题栏，只有在最上面才有。

**Comment by L1cardo** [comment]
> 他的意思是让标题栏固定在网页最上面，
> 而不是跟随页面滑动的时候，固定在浏览器最上面。
> 简单点就是往下滑动的时候看不到标题栏，只有在最上面才有。

如果是你这个意思的话，就可以在下面文件画横线的地方加一个`style="position: absolute"`

![image](https://user-images.githubusercontent.com/33802186/66451872-ddddc680-ea90-11e9-8b7c-6f0ffb5573d3.png)

**Comment by blinkfox** [comment]
@huanglm98 标题栏是指菜单栏，还是指文章标题呢

**Comment by blinkfox** [comment]
这个 `issue` 没有后续回复的话，我将关闭这个 `issue` 了。
