### ISSUE TITLE
标题栏可否做成半透明及高斯迷糊化，颜值更高一点

### ISSUE THREAD

**Issue by WJingC** [blinkfox/hexo-theme-matery#203]
类似于billbill这种标题栏
![屏幕快照 2019-10-09 下午2 13 01](https://user-images.githubusercontent.com/26542000/66456044-1be1e700-ea9f-11e9-8ef6-55f10439a4a8.png)

**Comment by L1cardo** [comment]
@WJingC  大屏幕显示下的现在的首页很漂亮，没有必要做模糊，需要的话可以自己在相应的地方加属性`filter: blur(4px)`

![image](https://user-images.githubusercontent.com/33802186/66812352-521edb00-ef65-11e9-96e9-d2e3a9c48df8.png)
