### ISSUE TITLE
不蒜子网站统计使用hexo-helper-live2d插件后统计不显示

### ISSUE THREAD

**Issue by Abnesvir** [blinkfox/hexo-theme-matery#208]
问题可通过以下网站解决https://www.zengfanping.com/2018/12/12/hexo%E5%8D%9A%E5%AE%A2pure%E4%B8%BB%E9%A2%98%E8%A7%A3%E5%86%B3%E4%B8%8D%E8%92%9C%E5%AD%90%E8%AE%A1%E6%95%B0%E4%B8%8D%E6%98%BE%E7%A4%BA%E7%9A%84%E9%97%AE%E9%A2%98/index.html

**Comment by L1cardo** [comment]
licardo.cn  你看我的博客，我的正常显示

**Comment by EscapeLife** [comment]
正常+1
