### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by JackChenSmile** [blinkfox/hexo-theme-matery#22]
请问标签，分类，关于，搜索在那个文件里改？

**Comment by scutem** [comment]
自定义样式可以在 `hexo-theme-matery/layout/` 找到相应的文件更改。关于 的文字内容在 `hexo-theme-matery/_config.yml` 中更改

**Comment by blinkfox** [comment]
标签在`tags.ejs`页面里面，分类在`categories.ejs`页面里面，关于在`about.ejs`及几个子模块页面里面，你了解下`ejs`的语法规则就大概晓得了

**Comment by JackChenSmile** [comment]
thank you

**Comment by JackChenSmile** [comment]
thank you

**Comment by JackChenSmile** [comment]
thank you

**Comment by JackChenSmile** [comment]
thank you

**Comment by JackChenSmile** [comment]
thank you
