### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by ciweigg2** [blinkfox/hexo-theme-matery#223]
为什么图片点击预览显示不了
怎么添加相册图片没有说明呀

**Comment by Samven7** [comment]
为什么代码块分成两块了，一边显示行号，一边显示代码。

**Comment by L1cardo** [comment]
> 为什么图片点击预览显示不了
> 怎么添加相册图片没有说明呀

图片点击可以预览，不知道你说的是不是这个

**Comment by L1cardo** [comment]
> 为什么代码块分成两块了，一边显示行号，一边显示代码。

代码块显示没问题
![image](https://user-images.githubusercontent.com/33802186/67148478-9b0ec080-f2d2-11e9-870b-5ae309d8eb3a.png)

**Comment by ciweigg2** [comment]
> > 为什么图片点击预览显示不了
> > 怎么添加相册图片没有说明呀
> 
> 图片点击可以预览，不知道你说的是不是这个
> ![image](https://user-images.githubusercontent.com/33802186/67148482-a19d3800-f2d2-11e9-94b6-ab8169163b3d.png)

可以了 你的那个movies界面怎么使用的呀

**Comment by Samven7** [comment]
1. 你好我想问一下，我已经把网址那里的链接改为我想要的永久链接格式。但是文章下面那里的文章链接还是原来的（非常长），请问是在哪里修改呢？
2. 另外，请问博客页面的修改是在哪里？比如我想把显示logo的img标签注释掉，是修改哪个文件夹？

**Comment by blinkfox** [comment]
@Samven7 第一个问题，我试了下没你说的问题吧；
第二个问题，不晓得你说的是哪个博客页面，页面很多，想修改 LOGO 的话，直接替换些 LOGO 图片就行。具体的大多数代码都在主题的 `layout` 文件夹下。

**Comment by blinkfox** [comment]
这个 `issue` 没有后续疑问的话，我将关闭这个 `issue` 了
