### ISSUE TITLE
配置完成后提交到github page，收到不支持的提示

### ISSUE THREAD

**Issue by Hogeexxl** [blinkfox/hexo-theme-matery#225]
你好，配置完成后，push 到 github.io 分支，收到 github 的邮件：
> The page build completed successfully, but returned the following warning for the `master` branch:
>You are attempting to use a Jekyll theme, "hexo-theme-matery", which is not supported by GitHub Pages.

这个主题不适用 github page 吗？

**Comment by L1cardo** [comment]
我没看到你的任何一个github仓库里面的任何一个master分之下有github pages的内容。照着文档操作，自己乱搞，出现问题，叫别人怎么帮你？

**Comment by Hogeexxl** [comment]
抱歉，我刚才刚好尝试清空这个项目的仓库打算从头配置，所以你没看到

**Comment by Hogeexxl** [comment]
抱歉，我刚才刚好尝试清空这个项目的仓库打算从头配置，所以你没看到
而重新配置一次的结果依然还是说不支持，可以帮我看看问题出在哪吗？感谢
> The page build completed successfully, but returned the following warning for the master branch:
You are attempting to use a Jekyll theme, "hexo-theme-matery", which is not supported by GitHub Pages.

**Comment by L1cardo** [comment]
你确定你是照着文档做的吗？  我很好奇你是怎么上传到github上面的

**Comment by Hogeexxl** [comment]
我的确是按照文档上配置的
用的是 sourcetree

**Comment by L1cardo** [comment]
教程里面让你用source tree了嘛？

**Comment by Hogeexxl** [comment]
[你的教程](https://blinkfox.github.io/2018/09/28/qian-duan/hexo-bo-ke-zhu-ti-zhi-hexo-theme-matery-de-jie-shao/#toc-heading-3) 只提到怎么把主题clone到本地然后怎么配置呀，我也的确是用git clone下来的。用 source tree是在配置完成后推送到github上而已

**Comment by L1cardo** [comment]
https://licardo.cn/posts/36692/

**Comment by Hogeexxl** [comment]
成功了，非常感谢

**Comment by L1cardo** [comment]
可以关闭了
