### ISSUE TITLE
文章中使用`{{  }}`标记的内容显示不出来

### ISSUE THREAD

**Issue by lin-zone** [blinkfox/hexo-theme-matery#232]
我在文章中使用`{{ cookiecutter.name }}`或者 `{{` 和 `}}`都无法显示 {{}}里面的内容

**Comment by EscapeLife** [comment]
加模板？

**Comment by blinkfox** [comment]
@lin-zone 说明你的这个变量根本不存在，我用 `{{title}}`、`{{date}}` 都能显示的。

**Comment by blinkfox** [comment]
@lin-zone 你不再回复的话，我认为这个是没有问题的，将关闭这个 `issue` 了。
