### ISSUE TITLE
markdown插入代码中包含$ $语句的mathjax转义问题

### ISSUE THREAD

**Issue by atlaslc** [blinkfox/hexo-theme-matery#235]
插入的代码中包含这么一段`distribution=$(. /etc/os-release;echo $ID$VERSION_ID)`，在生成网页代码时被mathjax认为是公式转义了，配置中没有开启mathjax功能。

**Comment by blinkfox** [comment]
没发现有你说的这个问题。

**Comment by blinkfox** [comment]
@atlaslc 你不再回复的话，我认为没有这个问题了，将关闭这个 `issue`。
