### ISSUE TITLE
你好！想问下我的为何没有时间轴归档

### ISSUE THREAD

**Issue by simlelcf** [blinkfox/hexo-theme-matery#238]
我的网站是http://yubenliu.cn  麻烦帮看一下

**Comment by EscapeLife** [comment]
@simlelcf 先试下使用官网的默认配置，确认下是否为自己修改配置导致的

**Comment by EscapeLife** [comment]
@simlelcf 下面👇这个不是吗？解决了，就关了吧

- `https://yubenliu.cn/archives/`

**Comment by simlelcf** [comment]
好的多谢
