### ISSUE TITLE
最新版本的代码高亮未生效用，安装了prism插件，也修改了配置

### ISSUE THREAD

**Issue by EvanZhou666** [blinkfox/hexo-theme-matery#243]
https://evanzhou666.github.io/2019/11/16/java8/

**Comment by blinkfox** [comment]
我看你页面的代码高亮是生效了的，但是显示得有些奇怪，应该是你的 Markdown 的代码块儿写的有问题。你的 Markdown 源文件长什么样，我看看

**Comment by EvanZhou666** [comment]
&nbsp;


您好，我的代码类似于这样的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 晚上11:15
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"Mr.zhou"<1043056891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 最新版本的代码高亮未生效用，安装了prism插件，也修改了配置 (#243)




我看你页面的代码高亮是生效了的，但是显示得有些奇怪，应该是你的 Markdown 的代码块儿写的有问题。你的 Markdown 源文件长什么样，我看看

**Comment by blinkfox** [comment]
你这个代码，我看不出来这是啥，`&nbsp;`?

**Comment by EvanZhou666** [comment]
1、指向静态方法的方法引用
```java
Integer::parseInt 等价于 (String str) ->Integer.parseInt(str)
```
2、指向实例对象的方法引用 (你在引用一个对象的方法，而这个对象本身是Lambda的一个参数)
```java
List<String> list = Arrays.asList("a","b","c");
        list.sort(String::compareTo);   //等价于 (String str1,String str2)->str1.compareTo(str2);
```

**Comment by EvanZhou666** [comment]
`
1、指向静态方法的方法引用
```java
Integer::parseInt 等价于 (String str) ->Integer.parseInt(str)
```
2、指向实例对象的方法引用 (你在引用一个对象的方法，而这个对象本身是Lambda的一个参数)
```java
List<String> list = Arrays.asList("a","b","c");
        list.sort(String::compareTo);   //等价于 (String str1,String str2)->str1.compareTo(str2);
```
`

**Comment by blinkfox** [comment]
我试了下，没你说得这个问题，你需要在代码快的后面加上**编程语言的小写字母标识**，比如：

```
```java
```

生成的效果：

![Snip20191117_1](https://user-images.githubusercontent.com/4027734/69009897-0791e380-0995-11ea-925c-1bb8ab3db196.png)

**Comment by EvanZhou666** [comment]
https://s2.ax1x.com/2019/11/17/Ms6Pdx.png
我有加语言的小写字母的  代码截图如上

**Comment by blinkfox** [comment]
你把你的 Markdown 文件发给我。

**Comment by EvanZhou666** [comment]
我重新安装了环境，然后解决了这个问题。
