### ISSUE TITLE
行号Bug

### ISSUE THREAD

**Issue by ramsayi** [blinkfox/hexo-theme-matery#244]
原.md文件没有行号，generate之后就这样左边行号，右边代码了
之前也有这种行号Bug，重新部署还是一样
请问要怎么解决
![Screenshot_2019-11-17-20-46-37-416_com android chrome](https://user-images.githubusercontent.com/53110196/69007703-259f1a00-097c-11ea-8b38-f1eb7acbff6f.jpg)

**Comment by colorsakura** [comment]
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
把hexo的_config.yml的高亮部分修改就行了
