### ISSUE TITLE
标签云失效问题

### ISSUE THREAD

**Issue by f1reworkzzz** [blinkfox/hexo-theme-matery#247]
hexo4.0版本下在修复过后仍旧失效

**Comment by EscapeLife** [comment]
@f1reworkzzz 有报错信息吗？有的话，截个图看看？

**Comment by f1reworkzzz** [comment]
@EscapeLife 本地的情况是这个


![Error](https://user-images.githubusercontent.com/56197616/69439192-6a162580-0d81-11ea-9132-772a10f99949.png)

部署到博客之后就是404，我还把最新的commit也就是这个


![hexo](https://user-images.githubusercontent.com/56197616/69439277-9a5dc400-0d81-11ea-80a9-cf62394d9d90.png)


复制下来还是不行

**Comment by EscapeLife** [comment]
@f1reworkzzz 你把你本地修改的配置摘出来，然后重新clone项目，然后覆盖，应该可以解决。我这里是没有复现标签云失效问题。

**Comment by EscapeLife** [comment]
@f1reworkzzz @blinkfox Close？
