### ISSUE TITLE
音乐和视频不显示

### ISSUE THREAD

**Issue by imbacc** [blinkfox/hexo-theme-matery#248]
Uncaught SyntaxError: missing ) after argument list

Uncaught SyntaxError: Unexpected identifier

两个错误

**Comment by blinkfox** [comment]
应该是你哪里配置有问题吧，你把音乐的 JSON 地址发给我看看呢

**Comment by imbacc** [comment]
life's a movie 多了个 '  解决了

**Comment by blinkfox** [comment]
嗯，后续版本会修复这个问题

**Comment by blinkfox** [comment]
新版本此问题已经修复了。
