### ISSUE TITLE
博主 可以加个友情链接吗？

### ISSUE THREAD

**Issue by Sitoi** [blinkfox/hexo-theme-matery#249]
博客名字： Sitoi
博客地址： https://sitoi.cn/
博客头像： https://github.com/Sitoi.png
博客简介： 妄想通过成为 Spider-Man 来实现财富自由的程序猿

谢谢博主

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by blinkfox** [comment]
加了
