### ISSUE TITLE
感觉Archive页面有点杂乱

### ISSUE THREAD

**Issue by ixsim** [blinkfox/hexo-theme-matery#25]
我觉得Archive界面应该简单一点。
去掉文章的特色图和内容摘要，_甚至是分类啥的_。
只留文章标题。
不会js就简单修改了下，就不pull requests丢人了。
[就是类似这种效果的](https://o--o.win/archives/)

**Comment by blinkfox** [comment]
后续有空再重写做视觉设计吧

**Comment by chunlintang** [comment]
![image](https://user-images.githubusercontent.com/8286273/52686035-f1c73c00-2f86-11e9-9742-396b48adbe20.png)
编译报了个错，打开归档页面显示的和首页是一样的，没有归档文章。。。求问怎么回事。。。

**Comment by blinkfox** [comment]
`Archive`页面感觉现在的就很好，没想出更好的方式吧，很抱歉，我打算关闭掉这个`issue`了
