### ISSUE TITLE
it doesn't work when I add a song containing \'

### ISSUE THREAD

**Issue by lixiang6632** [blinkfox/hexo-theme-matery#250]
when the song's name contains  \', then the music player doesn't work. here is the JSON code,
[{
    "name": "That's Why You Go Away",
	"artist": "Michael Learns To Rock",
	"url": "http://211.152.148.14/amobile.music.tc.qq.com/C400000wPHV24B5qhT.m4a?guid=8559387086&vkey=9DB5CFF5FDDB78D0358662A5DB5C36FA540714442318F0C71F6696EE930BEA45374C3B114E2B9037910F235CB4F6C27A939AB79E8913EAD0&uin=3428&fromtag=66",
	"cover": "https://y.gtimg.cn/music/photo_new/T002R300x300M000001WWysh0vYFDZ.jpg?max_age=2592000"
}]

**Comment by blinkfox** [comment]
嗯，试了下确实有问题，后续会更正，你可以先把 `That's` 改成 `That is` 临时解决一下。

**Comment by blinkfox** [comment]
这个新版本已经改了，这个 `issue` 我就关了。
