### ISSUE TITLE
新建分类等页面都是404，怎么解决

### ISSUE THREAD

**Issue by AndrewAndrea** [blinkfox/hexo-theme-matery#253]
![image](https://user-images.githubusercontent.com/35560234/69476388-3f28e180-0e14-11ea-8477-0a7666abf661.png)
![image](https://user-images.githubusercontent.com/35560234/69476395-55cf3880-0e14-11ea-9253-d7da01a21bec.png)

找了一大推方法，都不管用

**Comment by blinkfox** [comment]
我看为啥是 `Nginx` 报的 404 呢，是不是 `Nginx` 哪里没配置好额

**Comment by AndrewAndrea** [comment]
找到问题了，是因为配置的 timezone 错误导致全部没有生成静态页面。

**Comment by AndrewAndrea** [comment]
busuanzi 那个显示 404 是什么原因

**Comment by guhailong18** [comment]
请问是如何解决的？我也遇到了同样的问题，在哪里修改配置？
