### ISSUE TITLE
hexo g 生成时候js报错

### ISSUE THREAD

**Issue by fwh666** [blinkfox/hexo-theme-matery#260]

**Comment by fwh666** [comment]
![image](https://user-images.githubusercontent.com/16403099/69731371-bf2caf80-1164-11ea-8c54-c2271e1e89ec.png)

**Comment by blinkfox** [comment]
应该需要安装一下 `word-count` 插件，后续版本修复下这个问题，加一个判断。

```bash
npm i --save hexo-wordcount
```

**Comment by fwh666** [comment]
OK, 已解决
