### ISSUE TITLE
网站主页插入音乐，不能播放

### ISSUE THREAD

**Issue by fei0511** [blinkfox/hexo-theme-matery#261]
在网站主页插入音乐，不能播放。
这是我的musics.json文件
[{
    "name": "1",
    "artist": "Christine Welch",
    "url": "https://github.com/fei0511/test/blob/master/lough.mp3",
    "cover": "https://github.com/fei0511/test/blob/master/lough.jpg"
}]

希望您能给解答一下。谢谢啦

**Comment by blinkfox** [comment]
@fei0511 你放在 Github 上，你就要拿到这个资源的二进制 URL，而不是文件在 Github 的 Git 地址的 URL。你把 mp3 和 jpg 改成下面的链接方式就行了。

<https://raw.githubusercontent.com/fei0511/test/master/lough.mp3>
<https://github.com/fei0511/test/blob/master/lough.jpg?raw=true>
