### ISSUE TITLE
请问离开博客页面后就显示崩溃了 回到页面就好了 请问是在哪里设置的

### ISSUE THREAD

**Issue by qinzeduomoxiong** [blinkfox/hexo-theme-matery#263]
![image](https://user-images.githubusercontent.com/44266255/69810099-1b0b3d00-1226-11ea-9007-fe4c50783adc.png)

**Comment by qinzeduomoxiong** [comment]
回到页面就能正常显示芹泽的博客

**Comment by BrambleXu** [comment]
这个不是官方的功能，而是godweiyang自定义的，下面是修改的地址。
[layout.ejs#L21](https://github.com/godweiyang/hexo-matery-modified/blob/04e847ef106b92316b9237e5bf2d5fac75db9203/themes/matery/layout/layout.ejs#L21)
