### ISSUE TITLE
文章链接由于过长，不换行问题

### ISSUE THREAD

**Issue by hzpcactus** [blinkfox/hexo-theme-matery#265]
![TIM截图20191129162452](https://user-images.githubusercontent.com/50914382/69854740-ce2a7380-12c4-11ea-928b-b6578caa6be8.png)

**Comment by blinkfox** [comment]
没发现有你说的这个问题。

**Comment by EscapeLife** [comment]
没发现 + 1

**Comment by hzpcactus** [comment]
但是我的所有界面的链接都像这种不换行，枯了。。
您去我博客看一下，同样的效果hzpcactus.github.io


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Escape"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 上午10:50
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"仙人掌上的刺猬"<1416860873@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 文章链接由于过长，不换行问题 (#265)




没发现 + 1

**Comment by hzpcactus** [comment]
我自己在css中加个
.reprint__type&nbsp;.reprint-info{
&nbsp;&nbsp;&nbsp;&nbsp;word-wrap:&nbsp;break-word;
}
就好使了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Escape"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 上午10:50
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"仙人掌上的刺猬"<1416860873@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 文章链接由于过长，不换行问题 (#265)




没发现 + 1

**Comment by blinkfox** [comment]
这个 issue 就先关了，如果后续还有人出现，再强制解决。

**Comment by shy-share** [comment]
我也有同样的问题，这个链接太长了，还不换行

**Comment by hzpcactus** [comment]
> 我也有同样的问题，这个链接太长了，还不换行

在css中自行改动
