### ISSUE TITLE
您好，怎么让上面的菜单还有我的技能这些变成中文的？

### ISSUE THREAD

**Issue by BaiMingxu** [blinkfox/hexo-theme-matery#27]

**Comment by ciey** [comment]
修改主题下面_config.yml

**Comment by blinkfox** [comment]
@BaiMingxu 菜单配置在主题的`_config.yml`文件中第一项配置就是，默认是英文的，你改成中文就行。
其他英文是国际化方面的，修改根`_config.yml`文件中的`language`的值为:`language: zh-CN`，或者主题文件中的`languages/zh-CN.yml`文件中欧有对应的文字可以修改。

**Comment by BaiMingxu** [comment]
谢谢，十分感谢
