### ISSUE TITLE
新建的post页面没有h1标记，不利于SEO，看有没有好的解决方案？

### ISSUE THREAD

**Issue by kezunlin** [blinkfox/hexo-theme-matery#273]

**Comment by blinkfox** [comment]
`<h1 />` 标签其实就是文章标题，SEO 是做了的，每页的 `keywords` 会根据文章的标题去生成，而且你想自定制修改文章的 `keywords`，也可以在 `FrontMatter` 里面加上 `keywords` 属性写自己的值也行。

**Comment by kezunlin** [comment]
页面的keywords目前是post title+blog title，这个的确有。但是页面h1确实没有，放在markdonw中间不利于TOC的展示，目前的post title是放在div里面的，没有h1标记

**Comment by blinkfox** [comment]
新版本 `v1.2.2` 已经将标题改成了 `h1`，没啥问题的话就关闭这个 `issue` 吧。

**Comment by kezunlin** [comment]
赞一个
