### ISSUE TITLE
查看header里description的部分没有使用summary

### ISSUE THREAD

**Issue by BrambleXu** [blinkfox/hexo-theme-matery#275]
测试文章：https://bramblexu.org/2019/12/05/proper-json-format-of-double-quotations-for-curl-post-data/

![image](https://user-images.githubusercontent.com/10768193/70383271-3a386600-19ae-11ea-9ca1-b7dcd5498751.png)

我在每篇文章的fromt-matter里都写了summary，但是description的部分还是直接从文章开头截取了内容。希望能修改一下在生成description的时候，如果提供了summary的话，优先使用summary。

**Comment by blinkfox** [comment]
嗯，可以加一下。

**Comment by blinkfox** [comment]
新版本 `v1.2.2` 已经改了这个功能
