### ISSUE TITLE
大佬 请问这套主题哪里找呢

### ISSUE THREAD

**Issue by qinzeduomoxiong** [blinkfox/hexo-theme-matery#276]
![image](https://user-images.githubusercontent.com/44266255/70425986-38090100-1aad-11ea-8077-54c278677ca6.png)

**Comment by qinzeduomoxiong** [comment]
请问这个主题哪里找呢

**Comment by EscapeLife** [comment]
hexo + next

**Comment by blinkfox** [comment]
这个 `issue` 跟本项目不相关，我将闭关了哈。
