### ISSUE TITLE
电脑端评论部分, github 登录跳转 404

### ISSUE THREAD

**Issue by love-yukee** [blinkfox/hexo-theme-matery#277]
电脑端评论部分, github 登录跳转 404, 手机端正常

**Comment by blinkfox** [comment]
你应该没有配置 `Gitalk` 吧，或者就是配置有问题，我页面里面看你都没配置。

**Comment by blinkfox** [comment]
你长期没有再回复的话，我将关闭这个 issue 了。

**Comment by L0ittle** [comment]
楼主您好，我也遇到了相同的问题，gittalk在文章下面可以显示，但是菜单栏的contact报错404，请问您解决了吗

**Comment by blinkfox** [comment]
@L0ittle 我看你的网站中还没有集成，要在正式的环境中看效果才行。
