### ISSUE TITLE
建议在线聊天新增chatra支持

### ISSUE THREAD

**Issue by EscapeLife** [blinkfox/hexo-theme-matery#278]
- 记得DaoVoice、Tidio都是收费，后续无法使用了。建议在线聊天新增对chatra的支持，是否支持你们决定呗。https://chatra.io/

![image](https://user-images.githubusercontent.com/16237571/70877399-3f259700-1ff8-11ea-940a-9989dc2ee06c.png)

- 主要是，免费版本即可满足日常需求

![image](https://user-images.githubusercontent.com/16237571/70877412-4b115900-1ff8-11ea-87e7-457c86a053a8.png)

- 提供对应API支持

![image](https://user-images.githubusercontent.com/16237571/70877429-5fedec80-1ff8-11ea-8e38-acca47a4def1.png)

**Comment by blinkfox** [comment]
可以，后续考虑增加。

**Comment by EscapeLife** [comment]
添加之后或者加到Todo，关闭issues

**Comment by EscapeLife** [comment]
其实没有啥实际意义，我这里关闭了
