### ISSUE TITLE
希望添加支持子目录部署

### ISSUE THREAD

**Issue by harvies** [blinkfox/hexo-theme-matery#279]
很多地方没有新增url前缀

**Comment by xming1001** [comment]
同求，在githubpage里面加载不了css、js

**Comment by harvies** [comment]
之前有尝试修改代码，改后基本上支持子目录了，但是还是有很多路径有问题，希望作者能给个思路

**Comment by xming1001** [comment]
> 之前有尝试修改代码，改后基本上支持子目录了，但是还是有很多路径有问题，希望作者能给个思路

怎么改的，小弟也想试试

**Comment by harvies** [comment]
![image](https://user-images.githubusercontent.com/16585330/71552987-0e0a8500-2a42-11ea-98b3-3c74e689d89b.png)
在静态资源引入时加上url前缀
root在_config.yml配置
