### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by BaiMingxu** [blinkfox/hexo-theme-matery#28]
您好，经常博客框架已经加载ok，但是上面menu的文字一直不显示的问题？能修改字体么？怎么才能让他快点出来呀？

**Comment by blinkfox** [comment]
@BaiMingxu 有图吗？我看看大概是什么样子的问题

**Comment by BaiMingxu** [comment]
![111_](https://user-images.githubusercontent.com/22886455/48313151-355e8280-e5f3-11e8-883c-35a707d65dbd.png)
就像这样

**Comment by BaiMingxu** [comment]
我又发现了一个问题就是有时候按浏览器左上角刷新按钮上面的nav背景就不显示了，如下图
<img width="826" alt="_20181111204316" src="https://user-images.githubusercontent.com/22886455/48313193-cfbec600-e5f3-11e8-8889-1ee422e64dbd.png">
<img width="859" alt="_20181111204337" src="https://user-images.githubusercontent.com/22886455/48313194-cfbec600-e5f3-11e8-9a6b-2d98d2321ad8.png">

**Comment by BaiMingxu** [comment]
大佬这个是怎么写出来的？我才刚接触md，不怎么会，嘿嘿
<img width="576" alt="22" src="https://user-images.githubusercontent.com/22886455/48313303-34c6eb80-e5f5-11e8-8303-c06d1adcf66e.png">

**Comment by blinkfox** [comment]
1. 你的问题应该跟浏览器有关系吧，你用的什么浏览器额
2. `Markdown`的写法你去学习学习`Markdown`语法就行，那个Markdown的源文件就是主题根目录中的两个README.md，一个中文，一个英文的

**Comment by BaiMingxu** [comment]
非常感谢您，嗯嗯，字体加载那个是我的问题，能改字体么？
大佬刷新的那个问题是存在的。我在谷歌和火狐上测了一下，你把页面往下滑动一下在点击浏览器上的刷新按钮。就像这样往下滑动一下
<img width="892" alt="_20181112121206" src="https://user-images.githubusercontent.com/22886455/48326445-6632cc00-e674-11e8-9560-abbe40ed7a8e.png">

**Comment by blinkfox** [comment]
@BaiMingxu 刷新那个是没法弄的，因为你滚动条下滑滚动了一部分之后，浏览器记住了你的位置，你点刷新，他仍然会回到你刚才哪个位置的

**Comment by BaiMingxu** [comment]
嗷嗷，能让他每次刷新绿色背景不消失么？

**Comment by blinkfox** [comment]
我再`chrome`下刷新就是没消失的

**Comment by blinkfox** [comment]
关于页面会消失

**Comment by BaiMingxu** [comment]
大佬，移动端这侧边栏重叠怎么解决，我增加了menu就是这样了。
![22_](https://user-images.githubusercontent.com/22886455/48401954-50e99a80-e765-11e8-9aa5-49ffa6cd85f6.jpg)

**Comment by blinkfox** [comment]
没啥好的办法，要么加可滚动条，要么减少菜单的数量吧，或者你自己调整下没一行的高度，高度更小点儿就好了。
