### ISSUE TITLE
网站标题含有单引号后版权信息不显示标题

### ISSUE THREAD

**Issue by harvies** [blinkfox/hexo-theme-matery#280]
var url = document.location.href;
        newdiv.innerHTML += '<br />'
            + '<%- __("from")  %>: <%- config.title %><br />'
            + '<%- __("author")  %>: <%- config.author %><br />'
            + '<%- __("link")  %>: <a href="' + url + '">' + url + '</a><br />'
            + '<%- theme.copyright.description %>';

config.title 含有单引号

**Comment by blinkfox** [comment]
嗯，我提交改了，你可以直接改 `post-detail.ejs` 文件，将代码中的 `<%- config.title %>` 改为 `<%= config.title %>` 这种写法就行。

**Comment by harvies** [comment]
谢谢
