### ISSUE TITLE
插入图片的方式不支持 “![]()”

### ISSUE THREAD

**Issue by JonOnEarth** [blinkfox/hexo-theme-matery#286]
如题，用<img src= >这种插入是没问题的

**Comment by JonOnEarth** [comment]
发现原来是括号没有parser出来，现实出来的是`![1]/images/neuralnetwork1.png` 把括号给解析没了，求设置细节

**Comment by blinkfox** [comment]
你文章写的有问题吧，我看看你 Markdown 怎么写的

**Comment by JonOnEarth** [comment]
`![4](/images/neural network4.png)`
之前用过其他的主题，文章显示是没出问题；而且我发现文章里面带括号  `()`  的都解析没了

**Comment by blinkfox** [comment]
你图片中间为啥有空格呢

**Comment by JonOnEarth** [comment]
搞明白咋回事了... 
我设置了 `mathjax :true` ，导致把文字中的括号都解析没了。但不设置 `mathjax :true` ，公式又解析不了...
嗯，是的。图片名称也不能有空格...

之前用过其他主题，没有出现上述问题。不过我升级了hexo到4.2，之前是3.x，不知道有没有影响。
谢谢~
