### ISSUE TITLE
自己上传的图片问题

### ISSUE THREAD

**Issue by 373005226** [blinkfox/hexo-theme-matery#288]
您好，我把自己的图片上传到主题文件夹下面的图片文件夹下，但是为啥好像写的文章都没有使用到我上传的图片

**Comment by EscapeLife** [comment]
@373005226 咳咳

首先，你需要在如下图所示的地方添加图片

![image](https://user-images.githubusercontent.com/16237571/71950774-8a0b8680-3213-11ea-8ff6-d937507c5d9b.png)

其次，在配置文件中也需要添加进来

![image](https://user-images.githubusercontent.com/16237571/71950796-a4456480-3213-11ea-9cdf-91527b8cf0a0.png)

最后，双手合十，阿门 👐

**Comment by 373005226** [comment]
hhhhhhh，3Q，奥利给！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Escape"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 中午12:38
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"刘渊"<373005226@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 自己上传的图片问题 (#288)




@373005226 咳咳
 
首先，你需要在如下图所示的地方添加图片
 

 
其次，在配置文件中也需要添加进来
 

 
最后，双手合十，阿门 👐
