### ISSUE TITLE
toc目录显示在文章上方，而不是侧边栏

### ISSUE THREAD

**Issue by sdisk** [blinkfox/hexo-theme-matery#289]
![image](https://user-images.githubusercontent.com/20137068/71985783-30807780-3266-11ea-9f7a-7138d6ed6910.png)
这种情况有人遇到吗？是文章的目录有问题吗？

**Comment by blinkfox** [comment]
@sdisk 我看你博客里面没有这个问题吧，显示正常的

**Comment by sdisk** [comment]
![image](https://user-images.githubusercontent.com/20137068/72121422-ef878080-3395-11ea-9086-ebb1c21ff80c.png)

目录是浮在页面上的，为什么不在侧边栏呢？像下方这种
![image](https://user-images.githubusercontent.com/20137068/72121389-dda5dd80-3395-11ea-9ad1-93e6ee566292.png)

**Comment by sdisk** [comment]
![浮动目录](https://user-images.githubusercontent.com/20137068/72121520-3d9c8400-3396-11ea-935e-88c5694ddc0e.png)
目录是浮动在文章上方的，为什么不是在侧边栏，像下面这种
![toc正常目录](https://user-images.githubusercontent.com/20137068/72121579-691f6e80-3396-11ea-9ef0-9684d6cb736a.png)

**Comment by blinkfox** [comment]
我看你第一篇文章就是显示正常的，第二篇就有问题，应该是你哪里的写法不对引起的。

**Comment by sdisk** [comment]
md语法的问题，sorry

**Comment by ZbWeR** [comment]
> md语法的问题，sorry

你好，我也出现了这个问题，请问能具体说一下是哪里的语法问题吗？
正常来说目录显示在文章右侧，而我是显示在文章上方，会影响阅读
