### ISSUE TITLE
hexo-prism-plugin插件代码高亮不起作用

### ISSUE THREAD

**Issue by yuanzi222** [blinkfox/hexo-theme-matery#290]
hexo: 3.7.1
hexo-cli: 3.1.0
os: Windows_NT 6.1.7601 win32 x64
node: 12.14.0
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1

**Comment by blinkfox** [comment]
你要看看代码高亮的插件是否安装成功，配置是否正确
![1](https://user-images.githubusercontent.com/4027734/72038971-492c7400-32de-11ea-8c16-7716f8d234c8.png)

**Comment by yuanzi222** [comment]
确认配置没有问题就是根据您的配置,并且prism-tomorrow.css也已经加载
![image](https://user-images.githubusercontent.com/28979010/72039448-1f744c80-32e0-11ea-964f-5846f042b241.png)

**Comment by blinkfox** [comment]
那就是你的 Markdown 里面代码块没有写对应的编程语言引起的了

**Comment by yuanzi222** [comment]
正解,我傻了....

**Comment by yuanzi222** [comment]
多谢大佬
