### ISSUE TITLE
代码行数较多时显示有问题

### ISSUE THREAD

**Issue by duanego** [blinkfox/hexo-theme-matery#291]
代码行数500行左右，页面卡顿、显示有问题
https://iduane.wang:1301/2019/10/06/linux-mu-lu-wen-jian-cao-zuo-shi-li/

**Comment by blinkfox** [comment]
我点击看了下，没发现卡顿和显示有啥问题呢

**Comment by duanego** [comment]
我这边会出现代码加载不完全的情况

**Comment by fuxintong** [comment]
我的代码也显示不全  xml格式的代码 显示不全

**Comment by EscapeLife** [comment]
@duanego 链接地址挂了

**Comment by EscapeLife** [comment]
@blinkfox Close掉？这么长时间没反馈了

**Comment by blinkfox** [comment]
可以，那我先关了，后续如果还有问题，再开启这个 `issue` 即可。
