### ISSUE TITLE
markdown的todolist不能正常显示

### ISSUE THREAD

**Issue by misterdong** [blinkfox/hexo-theme-matery#3]
能不能帮忙看看这个是为什么，markdown的todolist的前面图标不显示呢，
![wx20180928-115055](https://user-images.githubusercontent.com/24272826/46187191-fc08d680-c314-11e8-8713-e4db562ae738.png)

**Comment by blinkfox** [comment]
@misterdong 已知晓，我会尽快修复。

**Comment by blinkfox** [comment]
@misterdong 已修复，更新或者下载最新的包吧。
