### ISSUE TITLE
搜索图标与github的图标重叠

### ISSUE THREAD

**Issue by nathaniel2020** [blinkfox/hexo-theme-matery#302]
这种情形下，搜索按钮无法使用，被github的图标遮住了

![image](https://user-images.githubusercontent.com/23420160/73418595-1c0c3800-4357-11ea-8c94-62f2313fbde1.png)

**Comment by blinkfox** [comment]
这是什么情况下才有的，我这边咋没这种情况呢

**Comment by EscapeLife** [comment]
@blinkfox 我来说说吧，这种情况是，在下拉页面之后，就会出现的，很久的一个问题。

- 刷新页面，搜索点击正常
- 下拉页面之后，点击搜索会被github的图标遮住，点击就会跳转到github页面了

**Comment by blinkfox** [comment]
我知道了，应该是菜单位置修改了引起的，我运行的版本，菜单是在中间的，不是往两边走的

**Comment by blinkfox** [comment]
把 `layout/_partial/header.ejs` 文件中第 `3` 行的 `head-container` 改成 `container` 就行。

**Comment by EscapeLife** [comment]
不合并到dev分支吗？

**Comment by nathaniel2020** [comment]
谢谢！修改成功了！
