### ISSUE TITLE
天气插件与logo重叠

### ISSUE THREAD

**Issue by axh2018** [blinkfox/hexo-theme-matery#303]
天气插件与logo重叠，本来我把天气栏放在左上角的位置，如图一，我把鼠标放上去，不会出天气的详细情况，而是指向主页。所以，我把天气栏放在了logo下面一点，如图二，这样说可以正常显示的。
有没有办法把天气插件放在左上角，且不与logo重叠。
![image](https://user-images.githubusercontent.com/58505743/73420157-8673a700-435c-11ea-8f78-6365ccbb3eeb.png)

![image](https://user-images.githubusercontent.com/58505743/73420241-ccc90600-435c-11ea-81e3-9916019dc6f8.png)

**Comment by blinkfox** [comment]
修改 logo 的`z-index`，或者将天气插件放在其他角落也行。

**Comment by axh2018** [comment]
这个logo的z-index在哪里改呢？或者能取消点击logo回到主页这个时间吗？谢谢！
