### ISSUE TITLE
首页 Banner 上面的遮罩层一直在变，如何关闭？

### ISSUE THREAD

**Issue by pleuvoir** [blinkfox/hexo-theme-matery#31]
非常喜欢这个主题，再次感谢。

**Comment by blinkfox** [comment]
@pleuvoir 修改或者删掉`/source/css/matery.css`中的`@keyframes rainbow`和`@-webkit-keyframes rainbow`这两个样式就行，这两是控制动态背景颜色切换的。

**Comment by pleuvoir** [comment]
> @pleuvoir 修改或者删掉`/source/css/matery.css`中的`@keyframes rainbow`和`@-webkit-keyframes rainbow`这两个样式就行，这两是控制动态背景颜色切换的。

已经改好了，谢谢。
