### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by jiuxiaxixi** [blinkfox/hexo-theme-matery#310]
![image](https://user-images.githubusercontent.com/13214300/73806612-ed81d780-4804-11ea-97da-dbdaa7ce51c3.png)
![image](https://user-images.githubusercontent.com/13214300/73806642-05595b80-4805-11ea-91c9-5cd468f4dcac.png)
GET http://localhost:4000/null/medias/featureimages/9.jpg

**Comment by jiuxiaxixi** [comment]
@blinkfox  是不是我什么地方不对呀

**Comment by blinkfox** [comment]
`null` 是什么。

**Comment by jiuxiaxixi** [comment]
> `null` 是什么。

我也不知道 所以重新安装了
