### ISSUE TITLE
我想删除主页的这个地方

### ISSUE THREAD

**Issue by jiuxiaxixi** [blinkfox/hexo-theme-matery#311]
![image](https://user-images.githubusercontent.com/13214300/73808065-8dd9fb00-4809-11ea-9c8e-5fbce235b4e8.png)
@blinkfox 请问有办法么

**Comment by EscapeLife** [comment]
@jiuxiaxixi 配置中不填写对应信息，就会自动隐藏的。

https://github.com/blinkfox/hexo-theme-matery/blob/7f436ac51028e339f50c4afa347ed8ce4bee0d3c/_config.yml#L129

**Comment by jiuxiaxixi** [comment]
谢谢大佬！！

Escape <notifications@github.com>于2020年2月6日 周四上午9:40写道：

**Comment by jiuxiaxixi** [comment]
我想删除的是下面的那一条白色的

**Comment by blinkfox** [comment]
@jiuxiaxixi 你把 `dream.enable`、`music.enable`、`video.enable`、`recommend.enable` 都设置为 `false` 即可。

**Comment by jiuxiaxixi** [comment]
非常感谢！！！

闪烁之狐 (blinkfox) <notifications@github.com> 于2020年2月10日周一 下午12:32写道：

**Comment by jiuxiaxixi** [comment]
已经解决了 开心

**Comment by SekiBetu** [comment]
> @jiuxiaxixi 你把 `dream.enable`、`music.enable`、`video.enable`、`recommend.enable` 都设置为 `false` 即可。

如果只想单独开启音乐的话无法隐藏此条嘛

**Comment by xx484782479** [comment]
> @jiuxiaxixi 你把 `dream.enable`、`music.enable`、`video.enable`、`recommend.enable` 都设置为 `false` 即可。

我拉的master分支  把这些都设置为false后还是没隐藏   是得dev 才行吗
