### ISSUE TITLE
请问下主文件中的配置文件url应该如何写啊？

### ISSUE THREAD

**Issue by cookingHero** [blinkfox/hexo-theme-matery#32]
配置好后页面路径都不对，css和js都无法引入

**Comment by cookingHero** [comment]
https://cookinghero.github.io/lcy.github.io/这是我的地址路径
配置：url: https://cookinghero.github.io/lcy.github.io
           root: /
本地起4000端口没问题，但是到github上就样式css无法加载，
GET https://cookinghero.github.io/css/matery.css net::ERR_ABORTED 404
GET https://cookinghero.github.io/libs/aos/aos.css net::ERR_ABORTED 404

**Comment by cookingHero** [comment]
解决问题了，rename一下项目项目名，保证和工程名一样就可以了

**Comment by blinkfox** [comment]
嗯，那我关闭这个问题了。

**Comment by cookingHero** [comment]
好的，谢谢啦




发自网易邮箱大师
在2018年11月22日 15:48，blinkfox 写道：

Closed #32.
