### ISSUE TITLE
主题中音乐播放器中默认如何关闭桌面歌词问题

### ISSUE THREAD

**Issue by athink8** [blinkfox/hexo-theme-matery#321]
#### 音乐播放器的主题修改无效

**Comment by athink8** [comment]
### 我的解决方法
> 简单粗暴的直接修改aplyer源码
查找 aplayer-icon aplayer-icon-lrc 在后添加 aplayer-icon-lrc-inactivity
查找 this.player.template.lrcButton.addEventListener 在前面添加 e.player.lrc.hide();

**Comment by blinkfox** [comment]
我看 aplayer 中有方法隐藏，但是没有对应的设置属性。你想直接简单解决的话，就按你自己的方式就行。
