### ISSUE TITLE
搜索功能无法使用,能弹出窗口,但是输入内容,没有搜索结果

### ISSUE THREAD

**Issue by Ifonly-go2019** [blinkfox/hexo-theme-matery#323]
控制台查看 : 
XML 解析错误：格式不佳
位置：http://localhost:4001/search.xml
行 6967，列 42： search.xml:6967:42
XML 解析错误：格式不佳
位置：http://localhost:4001/
行 6967，列 42：
搜索功能按照手册中操作的.
水平有限,折腾了半天也没整出来,Please help.
Console view: XML parsing error: Poorly formatted location: http: // localhost: 4001 / search.xml Row 6967, column 42: search.xml: 6967: 42 XML parsing error: Poorly formatted location: http: // localhost: 4001 / Row 6967, Column 42: The search function operates according to the manual. The level is limited, and it has not been adjusted for a long time.
Please help.

**Comment by blinkfox** [comment]
应该是你安装或配置搜索插件哪里出了问题，你卸载 `hexo-generator-search` 插件重新安装试试。

**Comment by Ifonly-go2019** [comment]
> 
> 
> 应该是你安装或配置搜索插件哪里出了问题，你卸载 `hexo-generator-search` 插件重新安装试试。
![QQ截图](https://user-images.githubusercontent.com/52337707/74341304-72ab5480-4de2-11ea-8076-c8428369ea93.png)
卸载后 按照文档的方法,控制台返回的信息也是XML格式错误-.-

**Comment by Ifonly-go2019** [comment]
问题已经解决
原因: 在我的一篇讲XSS(跨站脚本)的文章中,代码块引用了大量所谓的变形"JS"代码(payload),然后这个应该是代码高亮插件的问题,或者是什么问题,会解析我其中的代码,导致了提取出来的search.xml 出现问题,不能正常解析.
修复: 将存在问题的文章中的代码块,取消对其language设置,直接默认是普通代码块就行了.最后重新部署一下CDN,部署一下博客,可以进行搜索了
博客地址: https://hack-for.fun

Problem has been solved
Reason: In an article about XSS (cross-site scripting), the code block references a lot of so-called deformed "JS" code (payload), and then this should be a problem with the code highlighting plug-in, or what is the problem, Will parse the code in me, which causes problems in the extracted search.xml and cannot be parsed normally.
Fix: Cancel the code block in the article with the problem, cancel the language setting, and just default to the normal code block. Finally redeploy the CDN, deploy the blog, and search.
Blog address: https://hack-for.fun
Thanks again for the theme you provided, I really like it
