### ISSUE TITLE
百度分析/谷歌分析添加

### ISSUE THREAD

**Issue by lmwings** [blinkfox/hexo-theme-matery#325]
很好的主题。按文档都部署ok了；
看主题配置是支持百度分析的。这个要怎么开启啊。主题里的id填写什么？
我看百度分析里面是要求首页添加一段脚本（如下），这个对应到主题id要写什么
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?6fdfb99af350f72ffa18463cc4abcc04";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

**Comment by lmwings** [comment]
就是这窜数字6fdfb99af350f72ffa18463cc4abcc04；
\layout\_partial\baidu-analytics.ejs

**Comment by SekiBetu** [comment]
请问解决了吗，我写了js后面的ID也没用，难道整个这一段代码都写进去吗

**Comment by SekiBetu** [comment]
懂了，6fdfb99af350f72ffa18463cc4abcc04 这一行放进去就有效了，刚才是我没清除缓存
