### ISSUE TITLE
Github推送说要吧oauth2认证废弃，使用basic认证

### ISSUE THREAD

**Issue by iamazy** [blinkfox/hexo-theme-matery#328]
Github推送说要吧oauth2认证废弃，使用basic认证，目前这个主题的gitalk插件使用的是oauth2，可以改为basic吗

**Comment by iamazy** [comment]
见 [https://github.com/gitalk/gitalk/issues/343](https://github.com/gitalk/gitalk/issues/343)

**Comment by blinkfox** [comment]
最新 `develop` 分支已经解决过了，你下载 `develop` 分支的主题试试。

**Comment by EscapeLife** [comment]
@blinkfox close了吧

**Comment by blinkfox** [comment]
好。
