### ISSUE TITLE
如何使新页面在新窗口打开的问题

### ISSUE THREAD

**Issue by NneurotransmitterR** [blinkfox/hexo-theme-matery#330]
在banner和推荐文章里打开文章会在新窗口中打开，而点击下面的瀑布流和菜单会在本窗口中打开，请教这些分别在哪里设置？

**Comment by blinkfox** [comment]
在 `<a>` 标签中使用 `target="_blank"` 就是新标签页打开。

**Comment by NneurotransmitterR** [comment]
谢谢，通过更改相应的ejs文件实现了。
