### ISSUE TITLE
文章特色图片路径的问题

### ISSUE THREAD

**Issue by duanyuchen55** [blinkfox/hexo-theme-matery#333]
我把文章特色图放在hexo n创建文章时自动一并创建的文件夹内，特色图路径应该怎么写呀？
我尝试了/source/_posts/test/huaji.jpg还有huaji.jpg都不行= =

**Comment by blinkfox** [comment]
可以看下这个 #12 issue.

**Comment by duanyuchen55** [comment]
> 可以看下这个 #12 issue.
那个issue里的解决方法依然不奏效...

**Comment by duanyuchen55** [comment]
> 可以看下这个 #12 issue.

因为我是想把文章特色图放在hexo n时候一并创建出来的文件夹中，那个issue的解决方法不奏效。。实在不行我也把特色图放在/source/images下好了~谢谢啦
