### ISSUE TITLE
标签云字体太小了，比例不协调，而且不是居中对齐。希望可以优化。

### ISSUE THREAD

**Issue by lxl80** [blinkfox/hexo-theme-matery#335]
标签云字体太小了，比例不协调，而且不是居中对齐。希望可以优化。如图:
![image](https://user-images.githubusercontent.com/39109380/74720525-e92bd480-5270-11ea-9aed-ea81df253389.png)

**Comment by blinkfox** [comment]
最新版没有这个问题，我是比较老的版本，没升级过。
