### ISSUE TITLE
文章摘要截取函数没有区分中文/英文，导致页面对不齐。建议调整为中文占2个位置，英文占一个位置。

### ISSUE THREAD

**Issue by lxl80** [blinkfox/hexo-theme-matery#336]
文章摘要截取函数没有区分中文/英文，导致页面对不齐。如图：
![image](https://user-images.githubusercontent.com/39109380/74720679-1d06fa00-5271-11ea-95a1-1b4bda21702b.png)
建议调整为中文占2个位置，英文占一个位置，让无论纯中文还是英文为主排版都是齐的，效果类似下图：
![image](https://user-images.githubusercontent.com/39109380/74721032-b7ffd400-5271-11ea-8925-05530ec41828.png)

**Comment by blinkfox** [comment]
瀑布流布局本来就是高低错落的，设计上就是没要求高度一致。

**Comment by EscapeLife** [comment]
@lxl80 如果你是一个强迫症患者，可以在博客的开头的地方，多写点问题，满足摘要的字数限制，就可以保证对其。
