### ISSUE TITLE
chrome 浏览器 下 视频不能播放

### ISSUE THREAD

**Issue by coloriy** [blinkfox/hexo-theme-matery#340]
chrome 浏览器 下 视频不能播放，safari 浏览器可以，手机UC浏览器也可以。 我的网站： [https://www.yuv420.com](https://www.yuv420.com), 可以测试，视频直播地址：
http://ivi.bupt.edu.cn/hls/cctv10.m3u8

**Comment by EscapeLife** [comment]
@coloriy 你看下你的chrome是不是禁用了Flash呢？

**Comment by coloriy** [comment]
搞定了，没有禁止，是因为chrome浏览器需要在dplayer脚本加载前，先要加载一个hls支持脚本文件，F12调试了一下，发现chrome中提示hls不认识，于是搜索了一下，发现在dplayer 的demo中找到下面语句：

 10     <script src="https://cdn.jsdelivr.net/npm/flv.js/dist/flv.min.js"></script>
 11     <script src="https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js"></script>
 12     <script src="https://cdn.jsdelivr.net/npm/dashjs/dist/dash.all.min.js"></script>
 13     <script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
 14     <script src="https://cdn.jsdelivr.net/npm/pearplayer"></script>
 15     <script src="DPlayer.js"></script>
也就是说，dplayer如果支持hls解析，需要在它加载之前，加载hls.min.js就可以了，可以直接复制上面语句到dplayer脚本前，就可以播放hls直播了。

不过我的修改入下：
在_config.yml 中定义hls变量：
hls: /libs/dplayer/hls.min.js

然后在layout/_widget/video.ejs 中，添加下面语句：
 + 15 <script src="<%- theme.libs.js.hls %>"></script>
前提是，先下载一下hls.min.js 文件 到lib库中（dplayer同目录）
 16 <script src="<%- theme.jsDelivr.url %><%- theme.libs.js.dplayer %>"></script>

个人理解，safri等支持默认支持hls解析，但是chrome中需要设置hls支持。

**Comment by coloriy** [comment]
可以参考 https://www.cnblogs.com/fallTakeMan/p/12099242.html

**Comment by coloriy** [comment]
dplayer的官网说的比较清楚：http://dplayer.js.org/guide.html#hls

**Comment by coloriy** [comment]
最简单方法，就是在dplayer前添加一个一句：
<script src="https://cdn.jsdelivr.net/npm/hls.js/dist/hls.min.js"></script>

**Comment by coloriy** [comment]
还有个小需求，博主不知能否添加：
1. 就是给视频也添加一个列表项，用户可以选择相应的视频进行播放，类似音乐播放列表。
如果可以，我觉得博主可以加上。我觉得会让视频功能更加方便。

**Comment by coloriy** [comment]
本地测试，没有问题，提交到netlify后chrome依然播放不了？看来还需要研究一下啊。

**Comment by coloriy** [comment]
原来是https 网页不能播放http的m3u8, mixed content & CORS 问题，目前还没有找到好的方法。

**Comment by EscapeLife** [comment]
跨域的话，你可以把视频放到https的地址上面，就可与了

**Comment by coloriy** [comment]
关键这个视频是外链，服务器不受控制，属于公共资源，很多电台的公共资源，所以是http的，我控制不了。

**Comment by EscapeLife** [comment]
@coloriy 那就看能不能把对应的内容拔下来了，如果可以自己存放起来。最好还是不要外链第三方的东西，一旦有一点资源没有了，会导致博客对应的内容没有办法还原了。

**Comment by EscapeLife** [comment]
@coloriy 那就看能不能把对应的内容拔下来了，如果可以自己存放起来。最好还是不要外链第三方的东西，一旦有一点资源没有了，会导致博客对应的内容没有办法还原了。

**Comment by EscapeLife** [comment]
我去，你这加了个直播。。。强👍

**Comment by coloriy** [comment]
是啊，博主有办法帮加个视频列表功能吗？音乐有列表功能，我有很多视频直播地址，想可以让用户切换。

**Comment by blinkfox** [comment]
@coloriy 目前暂不考虑此功能哈。这个 `issue` 解决了，我就关闭这个问题了。
