### ISSUE TITLE
音乐在跳到子网页时无法连续播放

### ISSUE THREAD

**Issue by liwker** [blinkfox/hexo-theme-matery#346]
大佬您好，下午我部署了这个主题，很好用，就是我发现播放音乐时，点开文章后音乐就停止播放了（我用的是吸底模式），求解呀。

**Comment by a347807131** [comment]
因为跳转到新页面了，播放器也是重新构建的。

**Comment by liwker** [comment]
> 因为跳转到新页面了，播放器也是重新构建的。

有什么办法可以解决这个问题么，求教.

**Comment by a347807131** [comment]
@liwker 我知道的就式才能pjax，不过整个网站处理逻辑都需要变，不是很好整，

**Comment by liwker** [comment]
谢谢，那的确麻烦，以后再想想怎么解决.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Civin"<notifications@github.com&gt;; 
发送时间: 2020年2月27日(星期四) 下午5:53
收件人: "blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;; 
抄送: "Parker"<2385756605@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [blinkfox/hexo-theme-matery] 音乐在跳到子网页时无法连续播放 (#346)




@liwker 我知道的就式才能pjax，不过整个网站处理逻辑都需要变，不是很好整，

**Comment by L0ittle** [comment]
请问楼主找到解决办法了吗

**Comment by liwker** [comment]
> 请问楼主找到解决办法了吗

没呢

**Comment by blinkfox** [comment]
这个目前静态网页里面不好实现，目前不会改这块儿的逻辑，这个 `issue` 我先关了哈。
