### ISSUE TITLE
markdown table在手机上显示会出现越界的情况

### ISSUE THREAD

**Issue by chunchengwei** [blinkfox/hexo-theme-matery#35]
![11543975845_ pic](https://user-images.githubusercontent.com/15673819/49485469-1b246700-f876-11e8-8352-b527d4c82800.jpg)

效果如上

**Comment by blinkfox** [comment]
嗯，这个确实有些问题，我有空看看。

**Comment by chunchengwei** [comment]
辛苦辛苦 @blinkfox

**Comment by luokangyuan** [comment]
作为一个binkfox大佬仰慕者，我大概看了一下这个问题，应该是表格内容没有自动换行，可以在小屏幕下设置一下table的样式，让他自动换行，我等会修改了提一个pr吧，

**Comment by blinkfox** [comment]
@luokangyuan 谢谢！

**Comment by luokangyuan** [comment]
@chunchengwei 该问题已经解决，已经提交`pr`并合并。

**Comment by blinkfox** [comment]
@luokangyuan 谢谢，那我就关闭这个`issue`了
