### ISSUE TITLE
更新后遇到的新问题，修改主题背景和导航栏颜色无效，theme/source/matery.css（已解决但是感觉有些奇怪）

### ISSUE THREAD

**Issue by Nanzet** [blinkfox/hexo-theme-matery#353]
调试查看该请求引用了jsDelivr进行加速，调用该css文件的url为： https://cdn.jsdelivr.net/gh/Nanzet/Nanzet.github.io/css/matery.css
定位到"bg-color"中：
![图片](https://user-images.githubusercontent.com/48075743/75525574-0cae0680-5a4b-11ea-9d91-08464c22cc12.png)
发现该文件的值为默认的。

在自己的github仓库中查看该文件：
![图片](https://user-images.githubusercontent.com/48075743/75525601-19325f00-5a4b-11ea-80d3-9022b6ba7b04.png)
发现这里的值又是修改过的。。。。。。

解决：
  本地调试发现了一个问题，发现某个调用jsDelivr中显示的url里本应该是大写的仓库名Nanzet.github.io变成了小写nanzet.github.io，我的用户名是Nanzet，难道调用jsDelivr加速后会将大写字母转化为小写的吗？
  我尝试将主题配置文件的jsDelivr的url改成小写的仓库名，发现修改的主题背景色更改了。

**Comment by Yafine** [comment]
> 调试查看该请求引用了jsDelivr进行加速，调用该css文件的url为： https://cdn.jsdelivr.net/gh/Nanzet/Nanzet.github.io/css/matery.css
> 定位到"bg-color"中：
> ![图片](https://user-images.githubusercontent.com/48075743/75525574-0cae0680-5a4b-11ea-9d91-08464c22cc12.png)
> 发现该文件的值为默认的。
> 
> 在自己的github仓库中查看该文件：
> ![图片](https://user-images.githubusercontent.com/48075743/75525601-19325f00-5a4b-11ea-80d3-9022b6ba7b04.png)
> 发现这里的值又是修改过的。。。。。。
> 
> 解决：
> 本地调试发现了一个问题，发现某个调用jsDelivr中显示的url里本应该是大写的仓库名Nanzet.github.io变成了小写nanzet.github.io，我的用户名是Nanzet，难道调用jsDelivr加速后会将大写字母转化为小写的吗？
> 我尝试将主题配置文件的jsDelivr的url改成小写的仓库名，发现修改的主题背景色更改了。

这个jsdelivr更新新的资源需要时间，耐心等待就行

**Comment by Nanzet** [comment]
如果是jsdelivr更新新的资源需要时间的问题的话，那现在第一张图片里的颜色值就应该和下面图片的一样了啊。。。但是到了现在上述第一个url里bg-color的颜色值还是不一样的，我更改的是第二张图片里面的值的结果。

**Comment by Nanzet** [comment]
> 
> 
> > 调试查看该请求引用了jsDelivr进行加速，调用该css文件的url为： https://cdn.jsdelivr.net/gh/Nanzet/Nanzet.github.io/css/matery.css
> > 定位到"bg-color"中：
> > ![图片](https://user-images.githubusercontent.com/48075743/75525574-0cae0680-5a4b-11ea-9d91-08464c22cc12.png)
> > 发现该文件的值为默认的。
> > 在自己的github仓库中查看该文件：
> > ![图片](https://user-images.githubusercontent.com/48075743/75525601-19325f00-5a4b-11ea-80d3-9022b6ba7b04.png)
> > 发现这里的值又是修改过的。。。。。。
> > 解决：
> > 本地调试发现了一个问题，发现某个调用jsDelivr中显示的url里本应该是大写的仓库名Nanzet.github.io变成了小写nanzet.github.io，我的用户名是Nanzet，难道调用jsDelivr加速后会将大写字母转化为小写的吗？
> > 我尝试将主题配置文件的jsDelivr的url改成小写的仓库名，发现修改的主题背景色更改了。
> 
> 这个jsdelivr更新新的资源需要时间，耐心等待就行
如果是jsdelivr更新新的资源需要时间的问题的话，那现在第一张图片里的颜色值就应该和下面图片的一样了啊。。。但是到了现在上述第一个url里bg-color的颜色值还是不一样的，我更改的是第二张图片里面的值的结果。

**Comment by blinkfox** [comment]
该 `issue` 我先关了哈。
