### ISSUE TITLE
是否支持pdf在线预览功能

### ISSUE THREAD

**Issue by meteorsh** [blinkfox/hexo-theme-matery#355]
请问这个主题是否支持pdf在线预览功能，如果支持，怎么操作

**Comment by meteorsh** [comment]
已解决

**Comment by EscapeLife** [comment]
@meteorsh 怎么解决的呢？Markdown里面嵌套的标签吗？

**Comment by meteorsh** [comment]
> @meteorsh 怎么解决的呢？Markdown里面嵌套的标签吗？

安装一个hexo-pdf插件，具体可以看下我写的博客https://blog.csdn.net/qq_43827595/article/details/104574959

**Comment by EscapeLife** [comment]
@meteorsh 好的，学习下

**Comment by EscapeLife** [comment]
@blinkfox 我个人认为，可以把这个添加PDF文档的操作，更新到README.md里面。

**Comment by meteorsh** [comment]
> @meteorsh 好的，学习下
> 
> * 学习了下，发现你这用法有人提，本地引用不行吗？
> * 其实是可以的，比你博客里面的那个好些
> * `https://github.com/superalsrk/hexo-pdf`
> 
> ```shell
> {% pdf http://7xov2f.com1.z0.glb.clouddn.com/bash_freshman.pdf %}
> or
> {% pdf ./bash_freshman.pdf %}
> ```

嗯，本地引用也可以的
