### ISSUE TITLE
有没有什么办法来解决这个？

### ISSUE THREAD

**Issue by KangnakamuyiOfficial** [blinkfox/hexo-theme-matery#356]
我刚刚把主题部署上去后，发现了个问题，就是在标题旁边也会显示logo，而这影响了移动端的浏览体验，能否把这个标题旁的logo去除而保留侧栏的logo？
![photo_2020-03-01_14-16-22](https://user-images.githubusercontent.com/47733293/75620719-3db34600-5bc7-11ea-8477-81de4b54372c.jpg)
![photo_2020-03-01_14-16-18](https://user-images.githubusercontent.com/47733293/75620722-4146cd00-5bc7-11ea-9a63-6431640ea41a.jpg)

**Comment by EscapeLife** [comment]
@KangnakamuyiOfficial 可以看下之前的ISSUS，那个我忘记了，可以自行修改字体大小。

**Comment by EscapeLife** [comment]
@KangnakamuyiOfficial 解决了吗？解决了就关了吧

**Comment by KangnakamuyiOfficial** [comment]
> @KangnakamuyiOfficial 解决了吗？解决了就关了吧

没有啊（

**Comment by EscapeLife** [comment]
@KangnakamuyiOfficial 啪啪啪，打脸

- https://github.com/blinkfox/hexo-theme-matery/issues/147

**Comment by KangnakamuyiOfficial** [comment]
> @KangnakamuyiOfficial 啪啪啪，打脸 #147 可以将手机端的字体改小，变相的解决这个问题

谢谢了（
