### ISSUE TITLE
能否改进feature图匹配算法，使得无需更改图片为指定名称。

### ISSUE THREAD

**Issue by a347807131** [blinkfox/hexo-theme-matery#358]
比如，我想加入几张teature图，我就得按0,1,2...这样的形式为文件命名，如果文件名断档，则feature图丢失。
那么能都改进算法，使得代码制动去提取featurewen文件夹下的文件，更无需为命名烦恼，也无需添加到配置文件。

**Comment by Antares-Wu** [comment]
请问怎么自定义post的封面，似乎发上去的post封面是在featureimages图片里面随机选取的，我想要指定，请问在哪里修改？

**Comment by a347807131** [comment]
@Antares-Wu post设置img属性，并填写图片的链接。

**Comment by Antares-Wu** [comment]
> @Antares-Wu post设置img属性，并填写图片的链接。

请问本地图片的链接应该如何填写？我尝试了很多次，都没有成功显示。

**Comment by a347807131** [comment]
@a347807131 本地图片就是主题配置文件feature图的配置值，但post.img不支持jsdelivr。

**Comment by blinkfox** [comment]
@a347807131 那就得看看 Hexo 怎么读取文件夾下的所有资源文件了。

**Comment by blinkfox** [comment]
@a347807131 我看了下代码，特征图本来就是跟文件名无关的，是取的里面的值，没有直接读取名称，`featureImages` 下面的路径和名称可以任意填写，只要是有效的就行。

**Comment by a347807131** [comment]
ok
