### ISSUE TITLE
请问如何将banner的滤镜删去

### ISSUE THREAD

**Issue by xiuzheDorothy** [blinkfox/hexo-theme-matery#359]
个人不太习惯banner图上面各种颜色的滤镜，请问怎么删去这个东西呢

**Comment by EscapeLife** [comment]
@xiuzheDorothy look this

- https://github.com/blinkfox/hexo-theme-matery/blob/develop/README_CN.md#%E4%BF%AE%E6%94%B9%E4%B8%BB%E9%A2%98%E9%A2%9C%E8%89%B2

**Comment by xiuzheDorothy** [comment]
> 
> 
> @xiuzheDorothy look this
> 
>     * `https://github.com/blinkfox/hexo-theme-matery/blob/develop/README_CN.md#%E4%BF%AE%E6%94%B9%E4%B8%BB%E9%A2%98%E9%A2%9C%E8%89%B2`

谢谢！弄好了

**Comment by EscapeLife** [comment]
@xiuzheDorothy 解决了，ISSUS就可以关了哈
