### ISSUE TITLE
请问如何修改首页Banner图片加载过程中的背景色？

### ISSUE THREAD

**Issue by sddpljx** [blinkfox/hexo-theme-matery#360]
我的网站首页将rainbow效果去掉了，于是Banner在加载前会以红色为背景，请问这个红色背景能改为其他颜色吗？
![image](https://user-images.githubusercontent.com/37103761/75745318-e8f00680-5d51-11ea-8c13-605eea7f1c1d.png)

**Comment by blinkfox** [comment]
可以自己改 css 样式的。

**Comment by sddpljx** [comment]
> 可以自己改 css 样式的。
谢谢！我在修改css样式时，在\source\css\matery.css中修改与.bg-cover相关的地方，用background-color: #ffffff; 将背景设置为白色。这样依然不管用。。。
请问一下该如何修改呢？

**Comment by sddpljx** [comment]
已解决！
修改“\Hexo\themes\hexo-theme-matery\layout\_partial\index-cover.ejs"文件中的第63行即可。
``` html
    <div class="carousel-item red white-text bg-cover about-cover">
```

把“red”修改为其他颜色即可。

**Comment by blinkfox** [comment]
嗯，可以
