### ISSUE TITLE
代码显示区域异常

### ISSUE THREAD

**Issue by longlongqin** [blinkfox/hexo-theme-matery#361]
如图所示，这是我刚刚克隆的主题，然后，插入代码，就出问题了，是怎么回事啊？
![代码显示异常](https://user-images.githubusercontent.com/26651779/75980222-fefdf280-5f1c-11ea-9512-59c03e552320.png

**Comment by blinkfox** [comment]
你没有安装  hexo-prism-plugin 插件吧，执行 `npm i -S hexo-prism-plugin`，还需要修改 Hexo 根目录下 `_config.yml` 文件中 `highlight.enable` 的值为 `false`。

**Comment by longlongqin** [comment]
好的，谢谢了。我去试一下。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "闪烁之狐 (blinkfox)"<notifications@github.com&gt;; 
发送时间: 2020年3月5日(星期四) 晚上11:02
收件人: "blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;; 
抄送: "1198216723"<1198216723@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [blinkfox/hexo-theme-matery] 代码显示区域异常 (#361)




你没有安装  hexo-prism-plugin 插件吧，执行 npm i -S hexo-prism-plugin，还需要修改 Hexo 根目录下 _config.yml 文件中 highlight.enable 的值为 false。

**Comment by Vnzen** [comment]
我也遇到了,刚开始接触hexo的我,重复克隆了好几次也依然出现这个问题,让我怀疑人生.一番查找后才解决,原来只要用`hexo clean`清除缓存就好了
