### ISSUE TITLE
请问大佬这个文章密码的具体配置写法是什么样的？

### ISSUE THREAD

**Issue by yzp-99** [blinkfox/hexo-theme-matery#362]
我想给我的一些文章加密，但是我不太理解要如何使用这个passward，我尝试着给我的文章生成哈希加密密码，然后开启主题配置文件的相关配置，并且在对应文章中填写生成的哈希密码，但当我上传之后进行访问却发现很多托管在腾讯云上的图片等内容被阻止了，导致网页渲染失败。所以我想要一份完整详细的配置方法。
![1](https://user-images.githubusercontent.com/57695069/76097419-a143d600-6002-11ea-81ae-637d52dbe345.jpg)

**Comment by blinkfox** [comment]
主题 `config.yml` 配置文件中激活 `verifyPassword.enable: true` ，然后再你需要加密的文章中的 Front-Matter 中写 `password` 属性和值，这个值是你的原密码经过 SHA256 加密后的值。然后就行了，访问文章就需要输入密码了，你输入原密码就行。

**Comment by blinkfox** [comment]
该问题，没再继续回复的话，我认为已经解决了哈，我要关闭这个 `issue` 了。

**Comment by JiakaiYang** [comment]
> 该问题，没再继续回复的话，我认为已经解决了哈，我要关闭这个 `issue` 了。
有没有想法,开发个让我们不用先转码的..
