### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by longlongqin** [blinkfox/hexo-theme-matery#363]
我把根目录_config.yml中设置为`permalink: :title.html`，之后，图片的链接变得很奇怪，比如：/hexo-bo-ke-da-jian/hexo-zhi-matery-zhu-ti-pei-zhi.htm/qqpyimg1583400714.jpg
就不知道图片路径里面为什么多了一个htm，请大佬解答一下哈。

**Comment by blinkfox** [comment]
应该是你的 permalink 写的有问题.

**Comment by longlongqin** [comment]
谢谢您的回复，我写的确实有一些问题，我把他改成 :posts/title/&nbsp; 图片就显示正常了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "闪烁之狐 (blinkfox)"<notifications@github.com&gt;; 
发送时间: 2020年3月7日(星期六) 晚上11:31
收件人: "blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;; 
抄送: "1198216723"<1198216723@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [blinkfox/hexo-theme-matery] 图片无法显示 (#363)




应该是你的 permalink 写的有问题.
