### ISSUE TITLE
自定义手机端背景图

### ISSUE THREAD

**Issue by Arnoex** [blinkfox/hexo-theme-matery#365]
想要电脑端手机端分开显示背景，这个能实现吗

希望大佬解答

**Comment by Arnoex** [comment]
@media  only  screen  and（max-width：601 px）{.
     bg -cover  .title {
         font-size：2.8 rem ;
    }
}


是否可以参考这个代码，具体改一下？

**Comment by blinkfox** [comment]
你可以具体多测一下，提合并请求就行

**Comment by sweetcly** [comment]
<script type="text/javascript">
    // borwserRedirect
    (function browserRedirect(){
     var sUserAgent = navigator.userAgent.toLowerCase();
     var bIsIpad = sUserAgent.match(/ipad/i) == 'ipad';
     var bIsIphone = sUserAgent.match(/iphone os/i) == 'iphone os';
     var bIsMidp = sUserAgent.match(/midp/i) == 'midp';
     var bIsUc7 = sUserAgent.match(/rv:1.2.3.4/i) == 'rv:1.2.3.4';
     var bIsUc = sUserAgent.match(/ucweb/i) == 'web';
     var bIsCE = sUserAgent.match(/windows ce/i) == 'windows ce';
     var bIsWM = sUserAgent.match(/windows mobile/i) == 'windows mobile';
     var bIsAndroid = sUserAgent.match(/android/i) == 'android';
     if(bIsIpad || bIsIphone || bIsMidp || bIsUc7 || bIsUc || bIsCE || bIsWM || bIsAndroid ){
            $('.bg-cover').css('background-image', 'url(https://cdn.jsdelivr.net/gh/sweetcly/tcxzpic/mbanner/1.png)');
        }else{
            $('.bg-cover').css('background-image', 'url(https://cdn.jsdelivr.net/gh/sweetcly/tcxzpic/banner/1.jpg)' );
        }
    })();
</script>

我自己用的代码，因为banner轮播和这个一起不知道怎么写，我直接去掉了（还是大佬来写）
问题解决了  可以关了
