### ISSUE TITLE
图片和代码无法正常显示

### ISSUE THREAD

**Issue by L0ittle** [blinkfox/hexo-theme-matery#366]

**Comment by L0ittle** [comment]
代码全部乱码
图片显示不出来
不知道是因为修改config什么内容导致的

**Comment by blinkfox** [comment]
应该是你哪里配置有问题引起的了

**Comment by L0ittle** [comment]
就是自从加了懒加载插件之后就出现了这个问题，每次都需要hexo clean , hexo g, hexo d 解决

**Comment by L0ittle** [comment]
我快被这个问题搞疯了，每发一篇文章都报错，请问有没有人面临着一样的问题，救救我

**Comment by liruixue** [comment]
嗯，我的是代码块一下变成两个，用hexo dlean, hexo g后就可以了

**Comment by blinkfox** [comment]
嗯
