### ISSUE TITLE
文章内容超出

### ISSUE THREAD

**Issue by axh2018** [blinkfox/hexo-theme-matery#368]
![Screenshot_20200309_115059_com tencent mobileqq](https://user-images.githubusercontent.com/58505743/76183662-2944fe00-6204-11ea-8a29-6919a08dc97d.jpg)
![Screenshot_20200309_115112_com tencent mobileqq](https://user-images.githubusercontent.com/58505743/76183665-2ba75800-6204-11ea-8057-70f51e4ac58a.jpg)

在您的博客中，Java集合框架那篇文章，很多内容超出了，如图。

**Comment by blinkfox** [comment]
@axh2018 嗯，后续修改一下
