### ISSUE TITLE
主页不能正常显示文章特色图片

### ISSUE THREAD

**Issue by Lenv12138** [blinkfox/hexo-theme-matery#369]
![image](https://user-images.githubusercontent.com/40418978/76270275-a2e5f600-62af-11ea-875b-92092f564ed6.png)
请问下大佬这个是因为我把哪个文件改坏了吗？

**Comment by EscapeLife** [comment]
@Lenv12138 这个原因是你文章中 `img:` 标签没有找到对应图片，配置的问题。你可以现在本地把 
`hexo` 启动起来，然后改改路径调试下，应该很快就可以找到问题。祝好运！

**Comment by EscapeLife** [comment]
![image](https://user-images.githubusercontent.com/16237571/76272018-1f2f0800-62b5-11ea-8136-b989168bdedb.png)

**Comment by Lenv12138** [comment]
请问这个图片是要存储在主题source->medias里面吗？我的图片是放在了blog根目录source->images里面，直接在md文件里面更爱img吗？如果是的话我想问下img的路径是写/source/images/name.jpg吗？

**Comment by EscapeLife** [comment]
项目目录下，不是主题目录下

**Comment by Lenv12138** [comment]
![image](https://user-images.githubusercontent.com/40418978/76272887-70d89200-62b7-11ea-9ae9-48ae9427104b.png)
我在项目目录下创建了images文件夹，然后在md文件里面指定了路径，但是我上传服务器后，博客图片路径没有更改。
![image](https://user-images.githubusercontent.com/40418978/76272974-9fef0380-62b7-11ea-9b55-f960060c18da.png)

**Comment by Lenv12138** [comment]
我进入博客文章后，上一篇和下一篇文章的特色图片显示正常。
![image](https://user-images.githubusercontent.com/40418978/76273089-f2c8bb00-62b7-11ea-831d-81b0fa33f29e.png)

**Comment by Lenv12138** [comment]
谢谢大佬，我更改成功了，我把路径从`/source/images/1.jpg`改成了`/images/1.jpg`

**Comment by EscapeLife** [comment]
@Lenv12138 好的，Close吧！

**Comment by Vnzen** [comment]
@EscapeLife 
大佬你好,我也遇到和这个一摸一样的问题,我没有添加`img:`但是也出现了 `//medias/featureimages/9.jpg`的问题.多了前面一条 `/` ,是我改了什么的问题吗?
