### ISSUE TITLE
友链使用post的那种风格怎么样？貌似我的实现比较麻烦

### ISSUE THREAD

**Issue by xq773939719** [blinkfox/hexo-theme-matery#37]
如果友链使用post的那种风格怎么样？貌似我的实现比较麻烦，大佬看下
https://xq773939719.github.io/friend/
顺便请教下大佬想如何实现呢？

**Comment by luokangyuan** [comment]
关于友链这一块，我觉得我这个设计还可以，详情查看[码酱博客](http://luokangyuan.com/friend/ship/)，周末，我可以提一个`pr`。

**Comment by xq773939719** [comment]
> 关于友链这一块，我觉得我这个设计还可以，详情查看[码酱博客](http://luokangyuan.com/friend/ship/)，周末，我可以提一个`pr`。

**Comment by xq773939719** [comment]
> 关于友链这一块，我觉得我这个设计还可以，详情查看[码酱博客](http://luokangyuan.com/friend/ship/)，周末，我可以提一个`pr`。

收了，大佬的友链的确可以。
先加个友链了

**Comment by blinkfox** [comment]
友情链接的功能已经加了，这个issue我就关了。
