### ISSUE TITLE
文章列表忽然变成显示两列了，请问要如何解决呢？

### ISSUE THREAD

**Issue by duanyuchen55** [blinkfox/hexo-theme-matery#372]
![image](https://user-images.githubusercontent.com/42858158/76480829-d01adb80-644a-11ea-80d7-77f4b3385e43.png)
昨天打开博客发现忽然这样了，我好像也没有修改什么配置文件呀qaq，麻烦大佬帮忙看一下

**Comment by EscapeLife** [comment]
@duanyuchen55 

- 首先，你需要贴一下的博客地址
- 其次，需要贴一下你的项目配置文件

不然怎么看呢？https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by duanyuchen55** [comment]
> @ duanyuchen55
> 
> * 首先，你需要贴一下的博客地址
> * 在上面，需要贴一下你的项目配置文件
> 
> 不然怎么看呢？[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

哦哦哦，我刚刚准备贴来着，结果去截了一下图就给忘记了，网址是duanyc.top

**Comment by duanyuchen55** [comment]
我刚刚发现好像问题不在于主题文件，我打开我之前的部署在gitee上面的好久都没修改过的一个版本（https://duanyuchen_blog.gitee.io/），也是两列，我现在怀疑可能是chrome的问题~
