### ISSUE TITLE
主页随机文章图片无法显示。

### ISSUE THREAD

**Issue by roxsky** [blinkfox/hexo-theme-matery#373]
没有指定文章图片的文章在主页上会显示随机的图片。但是现在随机的图片地址有问题
生成的图片地址路径错误，所以无法显示，没有改过任何设置，默认的就会有这个问题。

`<img src="//medias/featureimages/12.jpg" class="responsive-img" alt="Hello World">`

**Comment by Lewin671** [comment]
是在linux环境下运行的吗？我的也是和你同样的问题

**Comment by roxsky** [comment]
> 是在linux环境下运行的吗？我的也是和你同样的问题

是的，我也是Linux环境的。

**Comment by TWENTYYM** [comment]
在windows下也是这样

**Comment by Lewin671** [comment]
在Pull Request那里已经给出了解决方案了

**Comment by blinkfox** [comment]
@roxsky 该问题还存在吗？不存在的话就把 `issue` 关了吧
