### ISSUE TITLE
关于首页图片显示bug

### ISSUE THREAD

**Issue by TWENTYYM** [blinkfox/hexo-theme-matery#375]
如图所示，在生成的index首页里面图片显示错误，查看网页源代码，发现用了两个斜杠。
怀疑是这个问题，修改了一下之后网页正常显示。
那么现在我想知道对应的首页的模板在哪里，有无大佬指点一下
![QQ截图20200313164502](https://user-images.githubusercontent.com/46795948/76604725-33d7fe00-654a-11ea-81bb-07bc346bfc97.png)
![QQ截图20200313164513](https://user-images.githubusercontent.com/46795948/76604730-35a1c180-654a-11ea-8422-71c0dee7f4ae.png)

**Comment by Lewin671** [comment]
在Pull Request已经给出了解决方案

**Comment by TWENTYYM** [comment]
> 在Pull Request已经给出了解决方案

 好的谢谢
