### ISSUE TITLE
markdown里的英文单引号会被解析成中文全角的单引号

### ISSUE THREAD

**Issue by rainstopper** [blinkfox/hexo-theme-matery#379]
![image](https://user-images.githubusercontent.com/14566097/76696891-6eb56f80-66cb-11ea-83cb-31a9d42d7363.png)
![image](https://user-images.githubusercontent.com/14566097/76696926-a15f6800-66cb-11ea-978b-777143b8ff33.png)

**Comment by chengpengzhao** [comment]
在/node_modules/hexo-renderer-marked文件夹下，找到index.js，将其中smartypants选项改成：
```js
smartypants: false,
```

**Comment by rainstopper** [comment]
> 在/node_modules/hexo-renderer-marked文件夹下，找到index.js，将其中smartypants选项改成：
> 
> ```js
> smartypants: false,
> ```

点赞！这个确实有效。

但考虑到重新安装依赖（比如更换设备、重装环境时）可能丢失对node_modules目录下文件的修改，个人并不提倡。
我选择在`_config.yml`配置文件中添加以下的配置：
```
# hexo-renderer-marked插件配置
marked:
  smartypants: false
```

**Comment by chengpengzhao** [comment]
> > 在/node_modules/hexo-renderer-marked文件夹下，找到index.js，将其中smartypants选项改成：
> > ```js
> > smartypants: false,
> > ```
> 
> 点赞！这个确实有效。
> 
> 但考虑到重新安装依赖（比如更换设备、重装环境时）可能丢失对node_modules目录下文件的修改，个人并不提倡。
> 我选择在`_config.yml`配置文件中添加以下的配置：
> 
> ```
> # hexo-renderer-marked插件配置
> marked:
>   smartypants: false
> ```

噢还可以这样设置，不过我还改了很多其他插件所以都是直接连node_modules一起打包的- -

**Comment by blinkfox** [comment]
这个 `issue` 我就关了哈。
