### ISSUE TITLE
你好，我想问一下，你每篇文章的目录哪里来的?

### ISSUE THREAD

**Issue by jackywei1228** [blinkfox/hexo-theme-matery#38]
目录
简介
安装主题
效果图

**Comment by blinkfox** [comment]
@jackywei1228 你多看看主题里面的`_config.yml`配置文件，里面有个TOC目录，开启就行 ，里面还有很多配置项的，有些开启了，有些没有，你看看吧

**Comment by jackywei1228** [comment]
好的，谢谢了，已经搞定了....
ifonly.me
