### ISSUE TITLE
Tidio导致网站打开变慢的问题

### ISSUE THREAD

**Issue by jinxiqinghuan** [blinkfox/hexo-theme-matery#384]
您好，我配置了Tidio后，发现网站打开十分缓慢，一直在加载Tidio，我查阅了Tidio的API文档，是可以设置以后再加载tidio的，跪求修复一下这个问题。

**Comment by blinkfox** [comment]
好，后续有空我看看

**Comment by jinxiqinghuan** [comment]
谢谢大佬~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 晚上10:14
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"1196680037"<1196680037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] Tidio导致网站打开变慢的问题 (#384)





 
好，后续有空我看看

**Comment by blinkfox** [comment]
你有示例页面吗？我看看 TIdio 加载慢是哪里加载慢引起的，是不是 `://code.tidio.co` 比较慢。

**Comment by jinxiqinghuan** [comment]
示例：lijitao.top
我已经把它关闭了，您稍等，我重新打开给你看一下
五分钟后能打开。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午1:48
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"1196680037"<1196680037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] Tidio导致网站打开变慢的问题 (#384)





 
你有示例页面吗？我看看 TIdio 加载慢是哪里加载慢引起的，是不是 ://code.tidio.co 比较慢。

**Comment by jinxiqinghuan** [comment]
> 你有示例页面吗？我看看 TIdio 加载慢是哪里加载慢引起的，是不是 `://code.tidio.co` 比较慢。

我暂时打不开tidio了，，，您有时间再来看看吧

**Comment by jinxiqinghuan** [comment]
> 你有示例页面吗？我看看 TIdio 加载慢是哪里加载慢引起的，是不是 `://code.tidio.co` 比较慢。

大佬，我打开了，[网址](http://www.lijitao.top/)：http://www.lijitao.top/你可以看一下，比刚才没开启的时候慢了一些。不开启一般都是秒打开的。打开tidio,好像开着梯子会快一些，不开梯子会慢。

**Comment by jinxiqinghuan** [comment]
> 你有示例页面吗？我看看 TIdio 加载慢是哪里加载慢引起的，是不是 `://code.tidio.co` 比较慢。

大佬，我打开了，网址：http://www.lijitao.top/      你可以看一下，比刚才没开启的时候慢了一些。不开启一般都是秒打开的。打开tidio,好像开着梯子会快一些，不开梯子会慢。

**Comment by blinkfox** [comment]
@jinxiqinghuan 我看了下页面的资源加载，加了 Tidio 之后确实会慢一些，很大原因应该是访问国外的网址慢引起的吧，如果你对页面加载速度要求高的话，就关掉 Tidio 吧。
![Snip20200407_2](https://user-images.githubusercontent.com/4027734/78685965-0e5dca80-7925-11ea-8488-8e34f4b6cf08.png)

**Comment by jinxiqinghuan** [comment]
好的大佬！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 晚上11:11
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"1196680037"<1196680037@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] Tidio导致网站打开变慢的问题 (#384)





 
@jinxiqinghuan 我看了下页面的资源加载，加了 Tidio 之后确实会慢一些，很大原因应该是访问国外的网址慢引起的吧，如果你对页面加载速度要求高的话，就关掉 Tidio 吧。
