### ISSUE TITLE
請問如何修改起始頁的"subtitle"?

### ISSUE THREAD

**Issue by teacookies1031** [blinkfox/hexo-theme-matery#386]
![image](https://user-images.githubusercontent.com/62531873/77457826-3256e180-6e38-11ea-800a-c00a2f1878b3.png)

**Comment by blinkfox** [comment]
在根 `_config.yml` 里面。

**Comment by teacookies1031** [comment]
> 在根 `_config.yml` 里面。

謝謝啊，抱歉沒看清說明
