### ISSUE TITLE
标题出现关键字，主页就会乱码

### ISSUE THREAD

**Issue by happywzy** [blinkfox/hexo-theme-matery#387]
1、如标题中出现`<Object>`，主页就会乱码。

2、如果`<>`中不是Object，标题就会不显示`<>`中内容，但不会乱码。

**Comment by blinkfox** [comment]
估计是 Hexo 的问题了吧

**Comment by happywzy** [comment]
> 估计是 Hexo 的问题了吧

试了`landscape`主题没有问题。

**Comment by blinkfox** [comment]
应该还是 Hexo 的问题，你用 `&#60;`、`&#62;` 转义符转义一下就行，比如：`&#60;Object&#62;`，解析后就是 `<Object>`。

**Comment by blinkfox** [comment]
@happywzy v1.3.0 版本没这个问题了哈，以前处理的时候，没有使用转义的渲染标签。
