### ISSUE TITLE
如何在博客页脚位置添加又拍云图片logo

### ISSUE THREAD

**Issue by meteorsh** [blinkfox/hexo-theme-matery#388]
您好，我想问下，怎么在foot.ejs中设置，使页脚处出现又拍云logo
![image](https://user-images.githubusercontent.com/46078304/77724904-0b163500-702f-11ea-8a65-c8d83381e194.png)

我不懂ejs或html的语法，所以不知道怎么添加图片logo，所以请教下您
![image](https://user-images.githubusercontent.com/46078304/77725028-5defec80-702f-11ea-94b7-0deb2fb35d5a.png)

**Comment by blinkfox** [comment]
可以加 <img /> 标签，你看看[这个链接](https://www.w3school.com.cn/tags/tag_img.asp)里面的教程就会了，比较简单。

**Comment by meteorsh** [comment]
已解决，谢谢！
