### ISSUE TITLE
大哥，文章瀑布流不填充就换页的问题

### ISSUE THREAD

**Issue by BorenHU** [blinkfox/hexo-theme-matery#390]
文章的瀑布流在最后的时候不填充，就直接换页了，应该怎么处理

**Comment by blinkfox** [comment]
分页条数要设置为 6 或 6的倍数，设置为 `12` 即可。

**Comment by BorenHU** [comment]
老哥，问题已解决。老哥，要想了解这个主题需要学习什么框架，有些东西想自己改但又看不懂

**Comment by blinkfox** [comment]
Hexo 的渲染模板是 [ejs](https://ejs.bootcss.com/)、CSS 框架是 [materialize](https://materializecss.com/)，其他基础就是 html + css +js 了。
