### ISSUE TITLE
mathjax矩阵显示有问题

### ISSUE THREAD

**Issue by maojunhat** [blinkfox/hexo-theme-matery#393]
![image](https://user-images.githubusercontent.com/20972206/78133144-82453200-7450-11ea-9143-81c4c9700fbe.png)
所有的矩阵都会变成一行...

**Comment by blinkfox** [comment]
不太懂这是啥，是 MathJax 数学公式吗，Hexo 的数学公式支持的不好。

**Comment by maojunhat** [comment]
抱歉，确实不是主题的问题
原因应该在于hexo默认的渲染器解析，矩阵换行标志用\\\就行了
