### ISSUE TITLE
音乐播放器首页可以播放，切换到文章或其他地方后播放就会停止

### ISSUE THREAD

**Issue by sunnyzhifei** [blinkfox/hexo-theme-matery#394]
音乐播放器首页可以播放，切换到文章或其他地方后播放就会停止

**Comment by EscapeLife** [comment]
不就是这样的逻辑呀。。。

**Comment by sunnyzhifei** [comment]
@EscapeLife 我是想，是否可以贴底后的音乐，切换菜单也不会影响我正在播放的。希望是个全局的音乐播放，而不只是在首页

**Comment by EscapeLife** [comment]
暂时没有这个功能，你可能需要自己改代码

**Comment by blinkfox** [comment]
这个各个页面都是独立的静态页面，无法统一控制，只能各个页面独立播放。

**Comment by sunnyzhifei** [comment]
@blinkfox 好的，明白了，谢谢啦
