### ISSUE TITLE
如何重置不蒜子的统计数

### ISSUE THREAD

**Issue by YeSomeone** [blinkfox/hexo-theme-matery#396]
直接拿了网站源码下来魔改自己使用，但是不蒜子的统计数还是原来的基础上增加的，如何重置？

**Comment by EscapeLife** [comment]
把项目目录下生成的 . 开头的文件删除了，重新部署就可以了。具体哪个文件夹，不记得了，手机不好看。

**Comment by EscapeLife** [comment]
@YeSomeone 看了下，是这个 `.deploy_git` 目录

**Comment by YeSomeone** [comment]
好的，谢谢，我去试试





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Escape"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午9:45
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"小叶"<2737001949@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 如何重置不蒜子的统计数 (#396)





 
@YeSomeone 看了下，是这个 .deploy_git 目录

**Comment by EscapeLife** [comment]
解决了的话，close吧
