### ISSUE TITLE
跳转锚点没有生效

### ISSUE THREAD

**Issue by citisy** [blinkfox/hexo-theme-matery#399]
引用的链接中已经设置了锚点对应的`#indexCard`，可以跳转到对应的文章，但没有跳转到对应的锚点。
检查过文章的标题元素，有生成`id`属性的标签。
还有一个很奇怪的现象，譬如一开始URL的锚点部分是`#toc-heading-10`，第一次输入回车，跳转对应的锚点失败，然后URL锚点部分改为`#toc-heading-11`按回车，居然跳转成功了。
作者大大，这是什么原因引起的？

**Comment by blinkfox** [comment]
中文锚点支持的不好，为了解决这个问题，给说有标题都加了自动计算的ID，就是 `toc-heading-10` 等等，依次往下加的

**Comment by citisy** [comment]
感谢作者大大的回复，我后来也试了英文的标题，结果还是跳转不了，是目前版本对锚点的支持都不太好，还是我没有get到正确的用法？ @blinkfox

**Comment by chengpengzhao** [comment]
@citisy 你试试在标题前后各空一行？  
我之前也遇到过跳转不正确的问题，这样做然后就好了。。。现在在md文件里每次写标题都习惯性多空几行。

**Comment by citisy** [comment]
@chengpengzhao 谢谢你的建议。
刚测试了，这个方法好像也行不通。没辙-_-||

**Comment by blinkfox** [comment]
@citisy 你让我看看你的文章或链接呢，我试试，光看文字不太懂啥意思

**Comment by citisy** [comment]
@blinkfox http://citisy.site/posts/4be3.html#toc-heading-10 ，例如这个连接就没办法跳转到对应的标题

**Comment by blinkfox** [comment]
应该是页面初始化之后，有什么东西影响到了。
