### ISSUE TITLE
代码显示时，开启行号只有一条竖线

### ISSUE THREAD

**Issue by chunchengwei** [blinkfox/hexo-theme-matery#40]
这个要改哪里的代码啊？

**Comment by blinkfox** [comment]
代码行号是不支持的。

**Comment by chunchengwei** [comment]
如果想要添加这个的话，要改哪块代码？

**Comment by blinkfox** [comment]
方法就是不用`hexo-prism-plugin`的插件，去[prism](https://prismjs.com/)这个官网去下载教全的插件和css，它里面有行号的插件，你可以试试

**Comment by sherlonWang** [comment]
prism插件好像只有coy这个主题行号可以正常显示，其他都不行

**Comment by blinkfox** [comment]
这个没有仔细研究了，很抱歉，后续也应该不会再做这个需求了，将关闭这个`issue`。
