### ISSUE TITLE
默认分支希望设为master

### ISSUE THREAD

**Issue by EndlessPeak** [blinkfox/hexo-theme-matery#400]
我没注意分支的问题，克隆了dev分支，遇到了很多问题，最后对着作者的博客源码一行行改还原了，才发现主分支是可以正常使用的。希望作者能把默认分支设为master，免得误导后人。

**Comment by blinkfox** [comment]
默认分支还是以 `develop` 开发分支为主，如果你需要下载的话，通常是去 [releases](https://github.com/blinkfox/hexo-theme-matery/releases) 中去下载发布的稳定版

**Comment by blinkfox** [comment]
我先关闭这个 `issue` 了哈。
