### ISSUE TITLE
master分支主页音乐不能正常显示，不支持子目录部署

### ISSUE THREAD

**Issue by LiuXingLong** [blinkfox/hexo-theme-matery#401]

**Comment by blinkfox** [comment]
@LiuXingLong 最新 develop 分支中，已修改支持子目录的部署，你可以试试，后续没啥问题了，再发一版，主页音乐不显示的问题，没复现。

**Comment by blinkfox** [comment]
新版已经支持了哈，你可以试试，我要关闭这个 `issue` 了。
