### ISSUE TITLE
项目部署

### ISSUE THREAD

**Issue by liuyanzhou** [blinkfox/hexo-theme-matery#404]
请问一下 项目是不可以只部署到gitee(码云上吗) ，我多次尝试都是路径出现问题 ， 但用其他主题却不会出现路径问题

**Comment by blinkfox** [comment]
你可以看看这个 [issue](https://github.com/blinkfox/hexo-theme-matery/issues/133) 看能否临时解决，主题还是有问题，后续修改

**Comment by blinkfox** [comment]
@liuyanzhou 最新 develop 分支中，已修改支持子目录的部署，你可以试试，后续没啥问题了，再发一版

**Comment by liuyanzhou** [comment]
好的，我有个问题就是当主题升级了，多了其他功能的话，我该如何更新现有的代码支持呢？就是我已经把主题改成我想要的样子了，但又想支持主题升级后的功能。

**Comment by liuyanzhou** [comment]
好的，我有个问题就是当主题升级了，多了其他功能的话，我该如何更新现有的代码支持呢？就是我已经把主题改成我想要的样子了，但又想支持主题升级后的功能。

**Comment by blinkfox** [comment]
貌似没法，你只能自己备份好之前的修改，后面恢复

**Comment by blinkfox** [comment]
该 `issue` 没其他疑问，我就关闭了哈。
