### ISSUE TITLE
代码块应该怎么去掉最上面macOS那种风格的装饰呢？

### ISSUE THREAD

**Issue by maojunhat** [blinkfox/hexo-theme-matery#408]
这是我的博客
![image](https://user-images.githubusercontent.com/20972206/78956205-23e51700-7b14-11ea-933e-4589ad78cf8e.png)
这是演示的博客
![image](https://user-images.githubusercontent.com/20972206/78956191-192a8200-7b14-11ea-9e64-89cb70bfb0d7.png)
最上面一行
![image](https://user-images.githubusercontent.com/20972206/78956244-4119e580-7b14-11ea-990a-48603e72730f.png)
应该应该怎么去掉呢？
感谢！

**Comment by blinkfox** [comment]
我的主题是老版本的，这个是新版本的效果，没法配置去掉
