### ISSUE TITLE
文章链接显示过长，请问如何隐藏

### ISSUE THREAD

**Issue by ZHEN7954** [blinkfox/hexo-theme-matery#410]
如下图：
![GojwrR](https://user-images.githubusercontent.com/26821147/78973780-26ab3080-7b43-11ea-805f-c1d3a218ded8.png)

请问是如何隐藏该模块，我看你的博客下没有该模块内容。
请赐教。

**Comment by EscapeLife** [comment]
@ZHEN7954 使用随机数作为URL地址，而不要是文章标题，具体配置详见官方文档。

**Comment by ZHEN7954** [comment]
可以将该模块隐藏吗，请问是在theme下的_config.yml里吗

**Comment by ZHEN7954** [comment]
已解决，多谢

**Comment by EscapeLife** [comment]
@ZHEN7954 不客气

**Comment by ZHEN7954** [comment]
补充：原因为，另一台电脑上没安装npm i hexo-permalink-pinyin --save
