### ISSUE TITLE
部署到OSS后需要修改Index.html的问题

### ISSUE THREAD

**Issue by nagenanhai** [blinkfox/hexo-theme-matery#411]
你好，请问一下部署到oss后访问不到，是不是需要修改index.html路径，如果是的话怎么修改。。网上搜到的都是Next主题的修改方式，不一样

**Comment by blinkfox** [comment]
没部署过，不太了解，你部署之后，你的的环境网站可以发我看看

**Comment by nagenanhai** [comment]
![image](https://user-images.githubusercontent.com/42707759/79044945-eaf39200-7c3a-11ea-80dd-699d69bd25b7.png)  这个是我访问后的403提示
![image](https://user-images.githubusercontent.com/42707759/79044960-0363ac80-7c3b-11ea-8266-888da8fe649a.png)   这个是我的OSS路径
OSS和CDN的授权及回源请求等我已经检查好，没什么问题，参考next主题的修改路径，但是我不太清楚matery修改路径是怎么修改的

**Comment by nagenanhai** [comment]
> 没部署过，不太了解，你部署之后，你的的环境网站可以发我看看

![image](https://user-images.githubusercontent.com/42707759/79044945-eaf39200-7c3a-11ea-80dd-699d69bd25b7.png)  这个是我访问后的403提示
![image](https://user-images.githubusercontent.com/42707759/79044960-0363ac80-7c3b-11ea-8266-888da8fe649a.png)   这个是我的OSS路径
OSS和CDN的授权及回源请求等我已经检查好，没什么问题，参考next主题的修改路径，但是我不太清楚matery修改路径是怎么修改的

**Comment by blinkfox** [comment]
我用 OSS 部署了下，可以正常使用的

**Comment by blinkfox** [comment]
@nagenanhai 部署 OSS，需要设置你的桶为**公共只读**，设置桶为静态网站托管模式，且必须绑定自定义域名才行，这是我部署在 OSS 上的，你可以看看。
<http://blinkfox.com>

**Comment by nagenanhai** [comment]
> @nagenanhai部署OSS，设置需要你的桶为**公共只读**，设置桶为静态网站托管模式，且必须绑定自定义域名才行，这是我部署在OSS上的，你可以看看。
> [HTTP：/ /blinkfox.com](http://blinkfox.com)

那大佬问一下，准备部署在oss之前，matery有什么需要注意和更改的地方吗，不只是oss上的域名，还有您部署在oss上一开始的域名是自定义域名还是oss分配的域名

**Comment by nagenanhai** [comment]
> 那大佬问一下，准备部署在oss之前，物料有什么需要注意和更改的地方吗，不只是oss上的域名，还有您部署在oss上一开始的域名是自定义域名还是oss分配的域名

**Comment by nagenanhai** [comment]
对了大佬，你用的是阿里云的oss还是腾讯云的cos

**Comment by nagenanhai** [comment]
大佬想问下，你是部署到哪个，阿里云的oss还是腾讯云的cos，另外那个上传到对象存储之前，matery的url或者相关有哪些需要设置的，怎么设置。。。求解答 401973177 邮箱：401973177@qq.com 签名由 网易邮箱大师 定制 在2020年04月13日 00:06，闪烁之狐 (blinkfox) 写道： @nagenanhai 部署 OSS，需要设置你的桶为公共只读，设置桶为静态网站托管模式，且必须绑定自定义域名才行，这是我部署在 OSS 上的，你可以看看。 http://blinkfox.com — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by blinkfox** [comment]
@nagenanhai 阿里云 OSS，没设置啥 URL 吧，上传的是 `public` 目录下的静态文件

**Comment by nagenanhai** [comment]
大佬，我是在url里设置的自己的域名,https://xxx.xxx.com/。上传了public里的文件，但是访问就是403.方便的话您可以加一下我的qq401973177详谈吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午1:24
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"(10X5T29) 活动中心"<401973177@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 部署到OSS后需要修改Index.html的问题 (#411)





 
@nagenanhai 阿里云 OSS，没设置啥 URL 吧，上传的是 public 目录下的静态文件

**Comment by blinkfox** [comment]
@nagenanhai 加了
