### ISSUE TITLE
词云跳转链接问题

### ISSUE THREAD

**Issue by fallingswing** [blinkfox/hexo-theme-matery#412]
自动生成的标签云，显示没问题，但点击指向的链接嵌套了一层。
比如“阅读”这个标签  应该指向mysite/tags/阅读
但实际上他指向了 mysite/tags/mysite/tags/阅读,导致404。
学艺不精特别困惑。

**Comment by blinkfox** [comment]
@fallingswing  这是 `bug`，已修复，可以更新 develop 分支的代码，如果你不想更新的话，可以将 主题`/layout/_widget/tag-wordcloud.ejs` 文件中的第 `20` 行代码，替换为如下的代码即可：

```js
tagWordArr.push({'text': tag.name, 'weight': tag.length, 'link': url_for(decodeURI(tag.path))});
```

**Comment by fallingswing** [comment]
自行修改了代码，我加上了分类和标签的英文映射，完美解决了， 感谢！
关闭issue了。
