### ISSUE TITLE
社交链接鼠标移上去的提示条未显示

### ISSUE THREAD

**Issue by fallingswing** [blinkfox/hexo-theme-matery#420]
关于页脚的社交链接。
![image](https://user-images.githubusercontent.com/51070608/79307892-369f8780-7f2a-11ea-999d-d4d64653435c.png)
当我把鼠标移上去后，并没有如同期望出现提示条。于是我浏览了socialLink.ejs以及网页源码，如下
`<a href="<%= theme.socialLink.github %>" class="tooltipped" target="_blank" data-tooltip="访问我的GitHub" data-position="top" data-delay="50">
        <i class="fab fa-github"></i>`
然后我浏览了[码酱](http://luokangyuan.com/)的页面。
![image](https://user-images.githubusercontent.com/51070608/79308186-b594c000-7f2a-11ea-935b-3162021ed355.png) 提示条是能正确显示的，他的源码是
`<a href="https://github.com/luokangyuan" class="tooltipped" target="_blank" data-tooltip="访问我的GitHub" data-position="top" data-delay="50" data-tooltip-id="7083e468-b5b6-b1a0-1b53-bfad6f7ac3a0">
                <i class="fa fa-github fa-lg"></i>
            </a>`
发现两者的差别仅在于data-tooltip-id这一段，我尝试从他的源码中删去这段，这样就和我的源码是一致的，但提示条仍然能显示。涉及到知识盲区，不是大问题但实在好奇。不知道作者大大有没有头绪。

**Comment by blinkfox** [comment]
这是 `bug`，估计之前的贡献人员删了对应的 tooltip 初始化代码，你加上就行，我已经修改提交到 `develop` 分支上了，你不想升级的话，[参考我](https://github.com/blinkfox/hexo-theme-matery/commit/b06415098e047981b6746fb8b59882d3d16e593e)的改一下就行。

**Comment by fallingswing** [comment]
OK了
