### ISSUE TITLE
请教：如何配置自定义PAGE?

### ISSUE THREAD

**Issue by myRedeemer** [blinkfox/hexo-theme-matery#430]
主题默认的page有五个：categories/tags/about/contact/friend。求教：对于自己生成的page如何配置？例如：hexo new page "test", 我想通过导航栏的某一个菜单去引用这个test page。
新手小白，请各位前辈赐教！谢谢

**Comment by blinkfox** [comment]
跟其他页面一样，不过在你新建的 `index.md` 里面写内容就行。

**Comment by myRedeemer** [comment]
> 跟其他页面一样，不过在你新建的 `index.md` 里面写内容就行。

谢谢！
