### ISSUE TITLE
主题配置文件缺失：hexo-theme-matery/source/_data/recommends.json

### ISSUE THREAD

**Issue by destinys** [blinkfox/hexo-theme-matery#432]
主题配置文件中说明使用配置文件进行推荐文章共享时，需要拷贝hexo-theme-matery/source/_data/recommends.json文件至博客source/_data目录下，但该文件在当前版本库中不存在。

**Comment by blinkfox** [comment]
@destinys 你肯定是在主题配置文件中，把 `recommend.useConfig` 设置为 `true` 了，默认是 `false`的，改成 `false` 就行，你看看它的含义。

**Comment by destinys** [comment]
![image](https://user-images.githubusercontent.com/18349138/80050725-028b1e80-8549-11ea-8038-797f958bf213.png)
我目前的配置就是false，但是在博客中无法显示推荐文章

**Comment by blinkfox** [comment]
你不通过配置文件的方式，那就你要在文章的 `Front-Matter` 设置 `top: true`。

**Comment by destinys** [comment]
搞定，多谢。
