### ISSUE TITLE
请教：“我的梦想” 板块的2个问题

### ISSUE THREAD

**Issue by myRedeemer** [blinkfox/hexo-theme-matery#433]
1. “我的梦想” 板块的背景默认是白色，如何修改颜色，如何将一个图片设置为背景？
2. “ “我的梦想”标题底下的文字如何换行？
非常感谢！

**Comment by blinkfox** [comment]
一时说不清，你学习下 HTML + CSS 吧，这些比较基础，要换行，在文本中加入 `<br />` 标签就行。

**Comment by myRedeemer** [comment]
thanks. ticket closed

**Comment by garywei944** [comment]
第二个问题
1. 把 `layout/_widget/dream.ejs` 第9行的 `<%= theme.dream.text %>` 改成 `<%- theme.dream.text %>`。这样EJS渲染的就是没有被转义过的text了。
2. 然后在theme下的 `_config.yml` 里，写 `dream.text` 时候加上`<br>`就好了。但是相对的 `<` `&`之类的特殊符号要写成转义之后的 `&lt;`和 `&amp;`
