### ISSUE TITLE
文章打开和归档页面问题

### ISSUE THREAD

**Issue by topking66** [blinkfox/hexo-theme-matery#434]
大佬，请问怎么设置打开文章后不是在当前页面跳转而是打开新的页面啊，还有归档的文章的图能不能去掉，太占位置了，谢谢大佬拉

**Comment by blinkfox** [comment]
要新标签页打开须在 `<a>` 标签中添加 `target="_blank"` 就行，你学习一下 HTML + CSS，归档页面你按自己的需求修改即可。

**Comment by topking66** [comment]
谢谢大佬，问题解决了
