### ISSUE TITLE
[question]请问音乐播放器的歌曲名颜色哪里可以修改

### ISSUE THREAD

**Issue by SekiBetu** [blinkfox/hexo-theme-matery#445]
![image](https://user-images.githubusercontent.com/38283893/81188498-f3e04500-8fe7-11ea-91ca-477bdea966be.png)
歌曲名是白色的，看不清

**Comment by athlonreg** [comment]
> ![image](https://user-images.githubusercontent.com/38283893/81188498-f3e04500-8fe7-11ea-91ca-477bdea966be.png)
> 歌曲名是白色的，看不清

![image](https://user-images.githubusercontent.com/28970198/81274196-8b927180-9082-11ea-9bee-75567395acce.png)

图中的#fff改成#666试下

**Comment by SekiBetu** [comment]
> > ![image](https://user-images.githubusercontent.com/38283893/81188498-f3e04500-8fe7-11ea-91ca-477bdea966be.png)
> > 歌曲名是白色的，看不清
> 
> ![image](https://user-images.githubusercontent.com/28970198/81274196-8b927180-9082-11ea-9bee-75567395acce.png)
> 
> 图中的#fff改成#666试下

改了，无效

![image](https://user-images.githubusercontent.com/38283893/81275513-5c7cff80-9084-11ea-9582-db02bdc2044b.png)

**Comment by athlonreg** [comment]
如果用了cdn的话会有缓存，需要等段时间才可以看到，我本地测试了一下，是没问题的

![image](https://user-images.githubusercontent.com/28970198/81276699-f5604a80-9085-11ea-90e4-f9784d4ab247.png)

**Comment by SekiBetu** [comment]
> 如果用了cdn的话会有缓存，需要等段时间才可以看到，我本地测试了一下，是没问题的
> 
> ![image](https://user-images.githubusercontent.com/28970198/81276699-f5604a80-9085-11ea-90e4-f9784d4ab247.png)

![image](https://user-images.githubusercontent.com/38283893/81276841-23de2580-9086-11ea-8cea-02113ef0c82d.png)
确实，我现在去看了眼，可以了，刚才刷新也没反应
