### ISSUE TITLE
添加访客人数和总访问量

### ISSUE THREAD

**Issue by XuQianJin-Stars** [blinkfox/hexo-theme-matery#45]
能否添加添加访客人数和总访问量

**Comment by XuQianJin-Stars** [comment]
hi @blinkfox 我现在用的是google分析和卜算子 能够做成hexo 配置项 用户决定是否开启

**Comment by XuQianJin-Stars** [comment]
@blinkfox 已提交pr https://github.com/blinkfox/hexo-theme-matery/pull/46

**Comment by blinkfox** [comment]
@XuQianJin-Stars 嗯，合并了，谢谢。
