### ISSUE TITLE
文章底部样式问题

### ISSUE THREAD

**Issue by hhhOscar** [blinkfox/hexo-theme-matery#450]
请问文章底部样式有问题应该修改哪个文件呢？效果如图，打赏的图片没有居中
![image](https://user-images.githubusercontent.com/29939882/81479435-a9fc9680-9255-11ea-8660-4f4708c331ae.png)

**Comment by blinkfox** [comment]
在主题的这个文件中：`layout\_partial\reward.ejs`。

**Comment by hhhOscar** [comment]
> 在主题的这个文件中：`layout\_partial\reward.ejs`。

thanks
