### ISSUE TITLE
url引用文章中目录TOC段落失效

### ISSUE THREAD

**Issue by myRedeemer** [blinkfox/hexo-theme-matery#451]
请教： 从menu希望通过url直接链接到某篇文章中TOC目录中的某个段落，例如希望点击URL （path1/path2/#toc-heading-3.）直接跳到文章目录中的第三段落，  但实际点击后总是跳到文章的第一个目录。不知道为什么？谢谢

**Comment by blinkfox** [comment]
以前排查过这个问题，估计跟加载机制有关系，因为那个 `toc-heading-3` 是页面加载过程中生成的，去访问时，页面还没生成引起的，暂时还无解决方案。

**Comment by myRedeemer** [comment]
Thanks a lot, ticket closed
