### ISSUE TITLE
引用最新tag-wordcloud.ejs，但标签栏跳转中文标签链接依旧失败

### ISSUE THREAD

**Issue by nagenanhai** [blinkfox/hexo-theme-matery#452]
![image](https://user-images.githubusercontent.com/42707759/81529717-01078600-9392-11ea-9969-8e7aa56c7c59.png)
![image](https://user-images.githubusercontent.com/42707759/81529732-0f55a200-9392-11ea-96d0-d752a16b2a5c.png)
![image](https://user-images.githubusercontent.com/42707759/81529765-23999f00-9392-11ea-843a-4a9e5a6af136.png)
![image](https://user-images.githubusercontent.com/42707759/81529773-298f8000-9392-11ea-8847-e7a32b662e2e.png)
![image](https://user-images.githubusercontent.com/42707759/81529850-4b890280-9392-11ea-8069-6768c42d655a.png)
大佬，我在安装这个最新的tag-wordcloud.ejs后，标签栏中的中文标签，点开链接依旧乱码失败。。请问这怎么回事。。

**Comment by blinkfox** [comment]
你页面发我看看

**Comment by blinkfox** [comment]
新版 dev 分支已修复，或者直接替换主题 `layout/_widget/tag-wordcloud.ejs` 中的内容 `url_for(decodeURI(tag.path))` 为 `decodeURI(url_for(tag.path))` 即可。
