### ISSUE TITLE
文章详情页面，底部文章链接过长时，UI异常

### ISSUE THREAD

**Issue by ASCII13** [blinkfox/hexo-theme-matery#453]
问题描述：如题

问题截图如下：
<img width="1375" alt="QQ20200512-171233@2x" src="https://user-images.githubusercontent.com/8610206/81665839-cece5500-9473-11ea-8814-545f35774b34.png">

如暂无时间修复，盼告知此部分文件名称，可以自行尝试修复。

**Comment by blinkfox** [comment]
没有复现过你这个问题，你可以把你页面发出来，我们看看。

**Comment by EscapeLife** [comment]
@ASCII13 试试更新一下版本，我这里也没有复现

**Comment by ASCII13** [comment]
> 没有复现过你这个问题，你可以把你页面发出来，我们看看。

链接如下：
https://ascii13.github.io/2020/05/11/%E6%B5%85%E6%9E%90%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8Fwxs%E4%BC%A0%E5%80%BCundefined/

**Comment by ASCII13** [comment]
> @ASCII13 试试更新一下版本，我这里也没有复现

我这个应该是最新的版本了，今天刚clone的

**Comment by blinkfox** [comment]
在 `my.css` 文件中可以加一个样式，让文字换行： 
```css
#artDetail .reprint-info {
    word-break: break-word;
}
```

**Comment by ASCII13** [comment]
> ```css
> #artDetail .reprint-info {
>     word-break: break-word;
> }
> ```

已完美修复
<img width="969" alt="1" src="https://user-images.githubusercontent.com/8610206/81667319-b3644980-9475-11ea-989c-3a73da69f244.png">
