### ISSUE TITLE
首页dream模块enable设置为false时，UI异常

### ISSUE THREAD

**Issue by ASCII13** [blinkfox/hexo-theme-matery#454]
问题描述：如题

问题截图：
<img width="1434" alt="22" src="https://user-images.githubusercontent.com/8610206/81667832-62088a00-9476-11ea-9b91-014c0b97fa9c.png">

预期：
dream模块enable设置为false时，整个区域隐藏

盼告知相关文件，可自行尝试调整。

**Comment by blinkfox** [comment]
dream模块、音乐模块、视频模块和推荐模块都在这里面，你把这几个都设置为 `false` 才行。

**Comment by ASCII13** [comment]
> dream模块、音乐模块、视频模块和推荐模块都在这里面，你把这几个都设置为 `false` 才行。

感谢！
