### ISSUE TITLE
轮播图切换按钮和底部分页器不显示

### ISSUE THREAD

**Issue by gejiuyuan** [blinkfox/hexo-theme-matery#462]
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.
  useConfig: true # 是否使用配置文件, 在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg
 

**轮播图部分的配合默认都是开启的。但就是不显示分页器和左右切换按钮，没有切换效果。求解！！**

**Comment by gejiuyuan** [comment]
> cover:
> showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
> showIndicators: true # 是否显示指示器. # Whether to display the indicators
> autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
> duration: 120 # 切换延迟时间. Switching delay time.
> intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.
> useConfig: true # 是否使用配置文件, 在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg
 
> **轮播图部分的配合默认都是开启的。但就是不显示分页器和左右切换按钮，没有切换效果。求解！！**

**Comment by daisf666** [comment]
+1

**Comment by blinkfox** [comment]
你的效果页面发我下

**Comment by blinkfox** [comment]
你的效果页面发我下

**Comment by daisf666** [comment]
> 你的效果页面发我下
https://www.fjct.city/

**Comment by daisf666** [comment]
我知道问题了，需要添加几篇文章设置cover: true

**Comment by gejiuyuan** [comment]
> 你的效果页面发我下

弄好啦已经！之前以为它会默认使用banner文件里的所有图片自动配置好轮播，后来仔细看了readme发现原来是要添加上文章后加上cover才行。还是感谢哈~~
