### ISSUE TITLE
描述和文章显示错乱

### ISSUE THREAD

**Issue by athlonreg** [blinkfox/hexo-theme-matery#463]
![image](https://user-images.githubusercontent.com/28970198/83162070-d8c2aa00-a13b-11ea-84bd-465f30a293e1.png)

如图，有的文章的描述和标题错乱了。一篇文章显示的描述是其它文章的内容。

**Comment by blinkfox** [comment]
把你页面 URL 发出来看看。

**Comment by athlonreg** [comment]
> 把你页面 URL 发出来看看。

https://blog.tlhub.cn/page/2/

**Comment by athlonreg** [comment]
Sorry, 是我自己的问题，混用了summary
