### ISSUE TITLE
回到顶部的按钮错位

### ISSUE THREAD

**Issue by BlueSky01st** [blinkfox/hexo-theme-matery#464]
如图，怎么办？
![wrong](https://user-images.githubusercontent.com/57856874/83228308-aacf7b00-a1b8-11ea-9a39-bf762f205aea.png)

**Comment by blinkfox** [comment]
估计是你的 `css` 或 `js` 没加载完全吧。

**Comment by BlueSky01st** [comment]
试了很多次，都没用

**Comment by blinkfox** [comment]
你把你的页面发给我看看

**Comment by BlueSky01st** [comment]
什么意思？我不是发了一张截图吗？

**Comment by BlueSky01st** [comment]
https://bluesky01st.github.io

**Comment by blinkfox** [comment]
看页面样式没有正常加载，有一些 404 的请求。你使用的是什么版本呢

**Comment by BlueSky01st** [comment]
什么的版本？

**Comment by blinkfox** [comment]
hexo 版本和主题的版本

**Comment by BlueSky01st** [comment]
Hexo:
hexo-cli: 3.1.0
os: Windows_NT 10.0.16299 win32 x64
node: 12.17.0
v8: 7.8.279.23-node.37
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0

**Comment by BlueSky01st** [comment]
主题是昨天Git clone的

**Comment by blinkfox** [comment]
你把 `node_modules` 删掉，hexo 版本弄高一点儿，重新 `install` 下呢

**Comment by BlueSky01st** [comment]
没有用啊……

**Comment by blinkfox** [comment]
那你把你的程序 `node_modules` 删掉，打个压缩包，发我邮箱 chenjiayin1990@163.com，我回家有空试试，肯定还是哪里有问题。

**Comment by BlueSky01st** [comment]
我已经删了重做……

**Comment by BlueSky01st** [comment]
问题解决了，但我如何做到GitHub,Gitee双部署呢？ Gitee上显示不出来……
https://whatwhy.gitee.io/blog
