### ISSUE TITLE
可以设置文章内图片的标签不显示吗？

### ISSUE THREAD

**Issue by handbye** [blinkfox/hexo-theme-matery#472]
![image](https://user-images.githubusercontent.com/26617058/83835447-60ec1500-a723-11ea-975b-412dfe8fbdcc.png)

**Comment by blinkfox** [comment]
不太懂你的意思。

**Comment by blinkfox** [comment]
目前没有这个设置功能，你可以根据自己的需求改改，觉得不错的话，可以提一下 `pr`。这个功能就是之前的一个人提的 pr 做的
