### ISSUE TITLE
大佬可以添加一个畅言评论系统吗，或者指导引用的方法

### ISSUE THREAD

**Issue by xiaoleGun** [blinkfox/hexo-theme-matery#475]
有人吗，给个提示，怎么搞

**Comment by blinkfox** [comment]
@xiaoleGun 一般都是引它提供的 `js`，然后再主题中写一个 `ejs` 文件，在某个 `<div>` 中显示就行，你可以看看其他评论系统在主题中是怎么集成的，参考下就行。以前有个  #192 的 issue，讲关于这个，你也可以看看。

**Comment by xiaoleGun** [comment]
> @xiaoleGun 一般都是引它提供的 `js`，然后再主题中写一个 `ejs` 文件，在某个 `<div>` 中显示就行，你可以看看其他评论系统在主题中是怎么集成的，参考下就行。以前有个 #192 的 issue，讲关于这个，你也可以看看。

next主题的引用貌似不一样，我已经设置了ejs，但是css没有加载吗？评论板块不显示（捂脸）
