### ISSUE TITLE
导航栏标题如何自定义

### ISSUE THREAD

**Issue by WolfGirlM** [blinkfox/hexo-theme-matery#477]
求助大佬，导航栏图标旁边的title怎么自定义呢~半天没找见地方~~跪谢

![image](https://user-images.githubusercontent.com/25200451/84909033-c824a480-b0e7-11ea-90c0-03a7351870e7.png)

**Comment by BlueSky01st** [comment]
博客根目录下`_config.ym`l修改：
![图片](https://user-images.githubusercontent.com/57856874/84963737-c76a2d80-b13c-11ea-99ad-63ea342bee8d.png)

**Comment by WolfGirlM** [comment]
> 博客根目录下`_config.ym`l修改：
> ![图片](https://user-images.githubusercontent.com/57856874/84963737-c76a2d80-b13c-11ea-99ad-63ea342bee8d.png)

谢谢大神!
