### ISSUE TITLE
无法加载categories页面和categories chart

### ISSUE THREAD

**Issue by zhengMK** [blinkfox/hexo-theme-matery#481]
大佬, 我按着你给的教程部署完后, 发现整个categories页面和about页面的categories chart加载不出来. 求大佬帮忙看看啥原因, 真的十分感谢 ORZ.
<img width="1680" alt="截屏2020-06-24 19 54 06" src="https://user-images.githubusercontent.com/61963726/85551764-e7c24c80-b654-11ea-8134-fabb0bb1f984.png">
<img width="1222" alt="截屏2020-06-24 19 46 17" src="https://user-images.githubusercontent.com/61963726/85551811-f446a500-b654-11ea-9460-27c558186d38.png">

**Comment by blinkfox** [comment]
@zhengMK 你应该没有写 `categories` 吧，在文章的 `Front-Matter` 中写上 `categories` 就行。

**Comment by zhengMK** [comment]
太谢谢作者大大了，果然加上categories就好了，十分感谢。
其实我还有个小问题，就是把_config.yml文件里cover下的useConfig改成true后，localhost:4000就打不开了。我照着提示去找_data/covers.json，但是没能找到。

**Comment by blinkfox** [comment]
@zhengMK 那个 `covers.json` 文件需要自己去创建填内容，主题只是去读取 `json` 文件中的内容而言。

**Comment by zhengMK** [comment]
okkk, 真的十分感谢作者大大的对我这种小白的耐心解答.

**Comment by blinkfox** [comment]
这个 issue 我就要关了。
