### ISSUE TITLE
picture_question

### ISSUE THREAD

**Issue by JackChenSmile** [blinkfox/hexo-theme-matery#49]
你好，我用了你的这个博客主题的模板，有一个问题想请教你。
在模板的config.yml文件中，最后一个图片的设置，如果想放置很多图片，都将每一张图片都添加到那个文件中的话，感觉有点不合适，所以我想问，可以把那些图片放进一个文件夹，然后通过获取文件夹中的图片，来渲染页面，这个方法可行吗？

**Comment by blinkfox** [comment]
可行是可行，就类似于banner图那种，但是得改代码，而且特征图每篇文章不一样，单独设置就行，如果全放里面太多了也不适合放吧

**Comment by JackChenSmile** [comment]
嗯嗯，知道了，谢谢
