### ISSUE TITLE
代码显示不全

### ISSUE THREAD

**Issue by doutv** [blinkfox/hexo-theme-matery#492]
```cpp
#include <iostream>
#include <algorithm>
#include <string>
#include <cstring>
#include <array>
#include <chrono>
#include <cmath>
using namespace std;

auto time_start = chrono::steady_clock::now();

// #define LINUXOUTPUT
#define OUTPUT
#define TEST
```
像这一段代码，中间有空行会将代码块切断，显示效果是这样的：https://doutv.github.io/2020/05/24/2020/5-3/#toc-heading-6

**Comment by blinkfox** [comment]
估计是你 Markdown 代码写的有问题，代码需要包裹在三个反引号之间，并写上对应的编程语言。你看看这个[代码写法的介绍](https://www.runoob.com/markdown/md-code.html)。

**Comment by doutv** [comment]
> 估计是你 Markdown 代码写的有问题，代码需要包裹在三个反引号之间，并写上对应的编程语言。你看看这个[代码写法的介绍](https://www.runoob.com/markdown/md-code.html)。

我找到一个解决方案：代码块前面要空一行，这样就不会出现错误了。
