### ISSUE TITLE
刷新页面的时候闪现另外的页面

### ISSUE THREAD

**Issue by bh7cw** [blinkfox/hexo-theme-matery#493]
刷新页面的时候闪现下半页为粉色的页面，将.bg-cover:after 里的display: none; 之后，去掉了渲染颜色之后，也会闪现页面。

**Comment by blinkfox** [comment]
没复现你说的现象呢

**Comment by bh7cw** [comment]
刷新的时候会闪现白色或者黄色或者别的颜色的页面，麻烦老师看一下我的页面bh7cw.de，git链接是https://github.com/bh7cw/bh7cw.github.io

**Comment by blinkfox** [comment]
设置 `cover` 为 `true` 的文章至少两篇，也就是让至少 3 个可轮播的页面才行，2 个的话会回滚导致由有白的。。

**Comment by bh7cw** [comment]
设置了4个轮播页面，依然闪现哎 https://bh7cw.de/

**Comment by blinkfox** [comment]
我看没有问题吧
