### ISSUE TITLE
音乐播放插件问题

### ISSUE THREAD

**Issue by DearDeer7** [blinkfox/hexo-theme-matery#495]
好像只能停留在首页时有用，我一切换到文章或其他界面音乐就没了。
能不能就是让音乐插件设置对象是整个网站，切到其他页面时音乐继续播放。

**Comment by blinkfox** [comment]
没法，生成的是静态文件，每个页面是独立的，没有服务端，就没法做到切到其他页面时音乐继续播放。

**Comment by DearDeer7** [comment]
> 没法，生成的是静态文件，每个页面是独立的，没有服务端，就没法做到切到其他页面时音乐继续播放。

那知道了，谢谢。
