### ISSUE TITLE
Problem in about page rendering

### ISSUE THREAD

**Issue by bolisettynihith** [blinkfox/hexo-theme-matery#496]
How to add the content present in `about/index.md` to the `/about` page. Without using the introduction in theme _config.yml.

**Comment by bolisettynihith** [comment]
Is it possible to have both displayed on the about page in the blog?
1. Profile introduction
2. Add content present in `about/index.md` to the `/about` page

**Comment by blinkfox** [comment]
Can't do it now, You can modify the code yourself

**Comment by bolisettynihith** [comment]
Thanks, I tried it, as I am not mostly into blog develop and I tried adding this `<%- partial('_partial/article', {post: page, index: false}) %>` by referring to other blogs, but I am unsuccessful in that, can you suggest how I can add that?

**Comment by blinkfox** [comment]
You can use `<%- page.content %>` in `layout/about.ejs` to show the contents of the `about/index.md` file. 

For example: insert the following code at line 45 of `layout/about.ejs`:

```xml
<div>
    <%- page.content %>
</div>
```

**Comment by bolisettynihith** [comment]
Thanks, It worked :)
