### ISSUE TITLE
能否添加评论模块

### ISSUE THREAD

**Issue by XiaoSenLuo** [blinkfox/hexo-theme-matery#5]
能否添加一个评论模块？

**Comment by blinkfox** [comment]
评论模块目前有的吧，有gitment和disqus，两种，你在配置项中激活并配置相关的值就行

**Comment by blinkfox** [comment]
@XiaoSenLuo 最近新增了`Gitalk`评论的支持，配置使用方式和`Gitment`类似，不过比`Gitment`好用点儿，你可以试试。

**Comment by jiubanmoli** [comment]
评论appId 和 appKey.去哪里拿啊
