### ISSUE TITLE
字数统计

### ISSUE THREAD

**Issue by jiubanmoli** [blinkfox/hexo-theme-matery#50]

**Comment by jiubanmoli** [comment]
好的，可以试着集成一下pdf插件这些

**Comment by blinkfox** [comment]
@jiubanmoli 我已经在最新的主题中加了文章字数统计、阅读时长和站点总字数的功能，可更新主题，安装`npm i --save hexo-wordcount`插件，并在主题的`_config.yml`文件中激活配置即可。
