### ISSUE TITLE
浏览器标签页文字中出现 | null

### ISSUE THREAD

**Issue by linupychiang** [blinkfox/hexo-theme-matery#501]
在浏览器标签页文字中出现 | null ，怎么解决？谢谢

打开浏览器开发者工具，查看 title 标签中，内容如下：
`<title>文章标题 | null</title>`

**Comment by blinkfox** [comment]
估计是你没写站点的 `title` 属性吧，你链接发出来我看看。

**Comment by linupychiang** [comment]
谢谢，这个问题解决了，确实是title没有写
