### ISSUE TITLE
友情链接处多余了一条白框

### ISSUE THREAD

**Issue by teamssix** [blinkfox/hexo-theme-matery#502]
我的博客友情链接地址：https://teamssix.com/friends/

在友情链接处多了一个白框，即下图中的红色框线标注处，请问这个要怎么去除呢？

![image](https://user-images.githubusercontent.com/49087564/88874023-9f4c0f00-d250-11ea-9886-cae085244b9e.png)

**Comment by blinkfox** [comment]
当时有个贡献的开发者遗留的一个小 bug，目的是想显示自定义内容，你可以往 friends 的 `index.md` 里面写点儿内容，就会显示了

**Comment by teamssix** [comment]
哦哦，这样子，谢了啊
