### ISSUE TITLE
代码块内的花括号转义成了 &#123;和&#125;

### ISSUE THREAD

**Issue by LRQLRQ** [blinkfox/hexo-theme-matery#503]
![image](https://user-images.githubusercontent.com/34814090/89369149-e124fb80-d70f-11ea-8af4-9a18550a5c02.png)

js代码，markdown如下

---

```javascript
function curry(fn, ...args) {
  if(fn.length > args.length) { // 传入参数还未到达
    return function(...arguments) {  // 返回函数
      return curry(fn, ...args, ...arguments); // 递归调用自己
    }
  } else {
    return fn(...args); // 符合条件，返回最终函数
  }
}
```

**Comment by blinkfox** [comment]
这个你得自己排查下了，估计是你的环境有问题吧

**Comment by LRQLRQ** [comment]
老哥。方便把你的 hexo -v， 版本信息贴一下吗，我排查了很久，不是你的主题的问题。在别的主题也是有这个问题。
我试了很多操作
1. 更新hexo-cli  我原始的版本是2.0更新到最新5.0，还是不行
2. 有一次是执行了 hexo clean 之后，有报错，找不到prism_plugin插件,然后就出现这种情况了

晚安.

**Comment by LRQLRQ** [comment]
![image](https://user-images.githubusercontent.com/34814090/89435775-e453d200-d777-11ea-9c11-10e7a0590302.png)
什么都没配置的qing'kuan情况下，代码框是这种情况，请问是哪里出错了吗~

抱歉这么晚了。

**Comment by blinkfox** [comment]
把默认的 lighheigh 关掉，配置文档里面有说明的，你看看

**Comment by niuiic** [comment]
遇到了同样的问题

hexo clean显示_config.yml中不存在hexo-prism-plugin选项

然而实际上是有效果的，只是花括号乱码了

可以确定_config.yml中的配置没问题，文件编码是utf-8。

这个插件好久没更新了，可能是新版本hexo中什么与它产生了冲突。我尝试了多种其他的高亮配置，均会出现同样的结果。

**Comment by LRQLRQ** [comment]
> 把默认的 lighheigh 关掉，配置文档里面有说明的，你看看

应该不是这个原因，我试过了。

**Comment by LRQLRQ** [comment]
> 遇到了同样的问题
> 
> hexo clean显示_config.yml中不存在hexo-prism-plugin选项
> 
> 然而实际上是有效果的，只是花括号乱码了
> 
> 可以确定_config.yml中的配置没问题，文件编码是utf-8。
> 
> 这个插件好久没更新了，可能是新版本hexo中什么与它产生了冲突。我尝试了多种其他的高亮配置，均会出现同样的结果。

确实是hexo的问题，在hexo的issue里面找到了有一样的情况，但是没看到怎么解决了的。

下面是我的环境，配置文件，效果。先凑活这样，回头了再改改。你可以参考一下。

### 环境
![image](https://user-images.githubusercontent.com/34814090/89601068-2f640700-d896-11ea-8840-77a8f3712cfd.png)

### 配置文件
![image](https://user-images.githubusercontent.com/34814090/89601090-3db22300-d896-11ea-89d3-24ef48ccfc3e.png)

### 效果
![image](https://user-images.githubusercontent.com/34814090/89601121-53274d00-d896-11ea-9943-4fbe2fc9c0c6.png)

**Comment by hangpei-bazahei** [comment]
我基本遇到了跟你完全一样的所有问题 。。。 大括号的转义 代码分段 prism_not_loaded问题 高亮都是暗色的 

高亮的问题还没解决。。。试了网上说的改marked正则表达式无效
代码分段的问题好像是highlight和plugin的改配置解决了（有时候配对了 但还是分段 不过现在好了）
大括号的转义没解决。。。目前用这种写法暂时替代。。。
{% codeblock [lang:java] [title] [url] [link text] %}
code block
{% endcodeblock %}

头一次玩hexo 头大。。。

**Comment by blinkfox** [comment]
那大家可以先把 Hexo 的版本降一下。

**Comment by hangpei-bazahei** [comment]
真的是。。。hexo降了之后再升回来 代码高亮问题就解决了somehow。。。

@LRQLRQ 还要请教一下 你的花括号转义问题最后怎么解决的

**Comment by niuiic** [comment]
![image](https://user-images.githubusercontent.com/63799565/89698340-3f8dec00-d953-11ea-81d4-a79a3d9ceb9c.png)

@LRQLRQ  我们的版本还不太一样。我试过用自带的highlight，不会有花括号的问题，但我这还有排列混乱、字体大小不一的问题。用其他的插件或者自己导入js和css要么没效果，要么和hightlight一样。还是全禁了吧hhh。

**Comment by LRQLRQ** [comment]
> 真的是。。。hexo降了之后再升回来 代码高亮问题就解决了somehow。。。
> 
> @LRQLRQ 还要请教一下 你的花括号转义问题最后怎么解决的

`_config.yml`文件改成我贴出图的配置，我记得好像是 lightlight开启，hljs也开启。但是没有高亮的效果。你可以试一下。

**Comment by AMDyesIntelno** [comment]
我把`_config.yml`文件改成这样
```yml
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: true    # default false
  custom_css:
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
缺少了高亮,先将就着使用
![图片](https://user-images.githubusercontent.com/52127603/89710569-ef487580-d9b6-11ea-8b15-891fc4d3a1e4.png)

**Comment by 1171257311** [comment]
已解决。原来版本hexo是5.0以上，出现了同样问题，将hexo版本换成4.1.1问题解决。hexo --version查询版本，npm i hexo@4.1.1更换版本。

**Comment by await-you** [comment]
> 已解决。原来版本hexo是5.0以上，出现了同样问题，将hexo版本换成4.1.1问题解决。hexo --version查询版本，npm i hexo@4.1.1更换版本。

感谢，花括号成功显示。

**Comment by hangpei-bazahei** [comment]
正解！

**Comment by inkss** [comment]
从百度搜到了这里，不过我在后面的搜索后发现这个算是上游问题，升级到 Hexo 5.1.1 就行了。

https://github.com/hexojs/hexo/issues/4482

https://github.com/hexojs/hexo/pull/4490

**Comment by xmuli** [comment]
> 从百度搜到了这里，不过我在后面的搜索后发现这个算是上游问题，升级到 Hexo 5.1.1 就行了。
> 
> [hexojs/hexo#4482](https://github.com/hexojs/hexo/issues/4482)
> 
> [hexojs/hexo#4490](https://github.com/hexojs/hexo/pull/4490)

我的版本就是 5.1.1 ，两天前升级的，升级方式见此 [Hexo 升级教程](https://xmuli.tech/posts/cb1e6c4f/) ；
然后发现依旧会有此问题； 问题详细 [#61](https://github.com/YunYouJun/hexo-theme-yun/issues/61)

附上详细版本，供大家详细参考，和前端上游高手解决参考
```bash
☁  xmuliMark [master] ⚡  hexo -v
INFO  Validating config
INFO  Yun version 1.0.0. Guide: https://yun.yunyoujun.cn
hexo: 5.1.1
hexo-cli: 4.2.0
os: Darwin 18.7.0 darwin x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

**Comment by zbw0520** [comment]
> 已解决。原来版本hexo是5.0以上，出现了同样问题，将hexo版本换成4.1.1问题解决。hexo --version查询版本，npm i hexo@4.1.1更换版本。

按照这个方法做我也弄成了

**Comment by blinkfox** [comment]
该问题在 hexo-theme-matery 的 `2.0.0` 版本修复了，建议大家可以直接升级 Hexo 到 5.x 最新版本就行，去掉 hexo-prism-plugin 的插件，直接将内置的 `prismjs.enable` 设置为 `true` 就行。

如果不想再做任何改动，可以忽略此消息。
