### ISSUE TITLE
文章封面图片怎么改

### ISSUE THREAD

**Issue by zsh2020** [blinkfox/hexo-theme-matery#507]
例子给的是这个 coverImg: /images/1.jpg
但是每次都是随机的图片，这个images文件夹的绝对路径是啥呢

**Comment by blinkfox** [comment]
可以是相对路径，也可以是 互联网中的图片文件 URL

**Comment by EscapeLife** [comment]
@zsh2020 reference to Readme.md

**Comment by EscapeLife** [comment]
@blinkfox close掉吧
