### ISSUE TITLE
CDN加速后chrome中图片更新异常

### ISSUE THREAD

**Issue by niuiic** [blinkfox/hexo-theme-matery#509]
配置jsDelivr后修改media中的图片并重新部署

用chrome访问网站图片未修改，用firefox访问图片已修改

下图中左侧为chrome，右侧为firefox

![image](https://user-images.githubusercontent.com/63799565/89705354-3753a200-d98f-11ea-8a0c-739a44a15a73.png)

- 关闭该功能后一切正常
- 本地调试正常（无论是否开启该功能）
- github上图片已经修改
- 原图片已不存在
- 清理chrome缓存无效
- 关闭该功能后重新部署，chrome上图片已修改，再开启该功能，重新部署，仍旧正常，再刷新，依旧正常。重启系统后再用chrome访问，依旧正常，但刷新后变回原图。且之后只要不再重复前面的操作，就一直是原图。

不清楚其中的原理，但已经不存在的图总不能凭空变出来。是不是因为开启了这个功能后，图片还在别的地方有保存呢？

**Comment by lscheng0905** [comment]
请问这个问题是如何解决的呢
