### ISSUE TITLE
关于使用hexo-prism-plugin，代码 “{” ，“ }” 不能正常显示

### ISSUE THREAD

**Issue by henji-Guo** [blinkfox/hexo-theme-matery#514]
## 如下图所示：
- {  变成了  &#123 
- }  变成了  &#125 

![image](https://img-blog.csdnimg.cn/20200819191750848.png)

## 在_config.yml配置如下：

![image](https://img-blog.csdnimg.cn/20200819191637544.png)

**Comment by henji-Guo** [comment]
Well, it's a bug, the hexo version is not compatible.
The way I did it was to drop the hexo version to 4.2.1 from 5.0.0 +.
![image](https://user-images.githubusercontent.com/68638626/90731239-06af2900-e2fc-11ea-8e9c-01585d1be20e.png)

**Comment by SekiBetu** [comment]
hexo5.0好像原生带了这个插件

**Comment by blinkfox** [comment]
该问题在 hexo-theme-matery 的 `2.0.0` 版本修复了，建议大家可以直接升级 Hexo 到 5.x 最新版本就行，去掉 hexo-prism-plugin 的插件，直接将内置的 `prismjs.enable` 设置为 `true` 就行。
