### ISSUE TITLE
多行引用渲染后变成了一行

### ISSUE THREAD

**Issue by SlimShadyBaby** [blinkfox/hexo-theme-matery#519]
1. 这是我的markdown代码：

    ![image](https://user-images.githubusercontent.com/29156868/91152219-4b1e3880-e6f1-11ea-9873-75204b8533db.png)

2. 本地vscode的预览

    ![image](https://user-images.githubusercontent.com/29156868/91151679-9257f980-e6f0-11ea-9cef-2ef8c4d78995.png)

3. 执行hexo s后访问博客页面变成了一行

    ![image](https://user-images.githubusercontent.com/29156868/91151722-9f74e880-e6f0-11ea-8ee2-1d4477abf901.png)

是不支持这样用？还是说我写法有问题？

**Comment by blinkfox** [comment]
@SlimShadyBaby 我本地试了一下，会渲染成多行的。另外，我看你这个应该属于“代码”，不应该写成“引用”吧。

**Comment by SlimShadyBaby** [comment]
> @SlimShadyBaby 我本地试了一下，会渲染成多行的。另外，我看你这个应该属于“代码”，不应该写成“引用”吧。

我换了个markdown的渲染引擎就好。另外，单个cli命令我喜欢用“引用“这样排版，个人习惯，写起来方便一些。总之，还是感谢回复，这个issue我就关闭吧
