### ISSUE TITLE
请问如何在移动端开启TOC

### ISSUE THREAD

**Issue by jeffreyouni** [blinkfox/hexo-theme-matery#520]
你好，我想在移动端也开启TOC，但是我找不到在哪个文件里修改代码。
（现在的思路是让那个TOC的展开收缩按钮在移动端也显示，默认收缩。）
可以指导一下吗？
谢谢！

**Comment by blinkfox** [comment]
在 `layout/_partial/post-detail-toc.ejs` 文件第 `98` 和 `108` 行中，去掉 `hide-on-med-and-down` 样式就行，意思时再中小屏幕下隐藏。
