### ISSUE TITLE
左侧侧边栏消失了

### ISSUE THREAD

**Issue by lancewu98** [blinkfox/hexo-theme-matery#521]
之前左边会有个侧边栏 可以选择菜单并且有个人头像和description的 现在没有了 是在哪里设置的吗 求大佬解答

**Comment by blinkfox** [comment]
那是移动端模式，只有当屏幕是宽度小于 `993px` 时才会出现。

**Comment by lancewu98** [comment]
> 那是移动端模式，只有当屏幕是宽度小于 `993px` 时才会出现。

好的 已解决 非常感谢
