### ISSUE TITLE
更新最新版matery之后table莫名没有自适应了

### ISSUE THREAD

**Issue by jeffreyouni** [blinkfox/hexo-theme-matery#523]
更新最新版matery之后table莫名没有自适应了

**Comment by blinkfox** [comment]
我试了下，没问题吧

**Comment by jeffreyouni** [comment]
能麻烦问一下怎么排查table宽度没有自适应吗？现在的问题就是就是宽度没有拉长，文字多长表格就多长。另外能麻烦你解答一下issue#522吗？
麻烦你了！谢谢！

**Comment by jeffreyouni** [comment]
很奇怪的就是我重新创建了新的hexo然后clone了新的matery进去，只更改了文章，然后依旧没有自适应宽度，用默认的landscape的话，table就有自适应宽度

**Comment by jeffreyouni** [comment]
在文章markdown里添加css可以解决，应该是markdown的css没有解析成功，不知道在哪里可以更改，不用每篇文章都添加css。
谢谢！

**Comment by jeffreyouni** [comment]
在head.ejs里加入css样式解决了，至今还是不明白为啥突然出现错误，可能是玄学，不知道是不是renderer有问题

**Comment by houhaoqi** [comment]
怎么更新主题啊

**Comment by blinkfox** [comment]
@houhaoqi 通常来说，备份之前的主题，删掉下载使用最新的主题，主题中的 `_config.yml` 替换成你备份的主题就行。但是，不太建议你直接覆盖老的 `_config.yml`，而是参考新老版本的 `_config.yml` 配置项，进行对应复制、粘贴，因为可能新主题中有新的配置选项。

**Comment by houhaoqi** [comment]
好的
