### ISSUE TITLE
友链页面有bug

### ISSUE THREAD

**Issue by PaddyLin-xum** [blinkfox/hexo-theme-matery#527]
我只设置一个友链，却出现了很多个![Snipaste_2020-09-09_20-07-46](https://user-images.githubusercontent.com/67828139/92596301-31c3e180-f2d8-11ea-9859-cfd0631dec48.png)

**Comment by blinkfox** [comment]
没复现你的问题，估计是缓存，你 `hexo clean `一下，以及清一下浏览器缓存。

**Comment by EscapeLife** [comment]
@PaddyLin-xum 你上面的截图是本地测试的地址吗？如果是的，你部署上去之后，通过域名查看就会正常的。如果还无法显示的话，你就需要看下对应的图片链接是否可以正常访问、是否加了访问限制等等。

- like this: `http://localhost:4000/`
- 还有问问题之前，你需要提供一个我们可以复现的场景，不然怎么排除问题呢？

**Comment by EscapeLife** [comment]
@PaddyLin-xum 有解决掉了吗？

**Comment by PaddyLin-xum** [comment]
谢谢啊，解决了，是我弄错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blinkfox/hexo-theme-matery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午4:46
收件人:&nbsp;"blinkfox/hexo-theme-matery"<hexo-theme-matery@noreply.github.com&gt;;
抄送:&nbsp;"功过一综成"<2841738015@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blinkfox/hexo-theme-matery] 友链页面有bug (#527)





 
@PaddyLin-xum 有解决掉了吗？

**Comment by EscapeLife** [comment]
@PaddyLin-xum To close

**Comment by EscapeLife** [comment]
@blinkfox Close吧

**Comment by jacksonKnight** [comment]
友情链接为啥也有评论 怎么关闭

**Comment by blinkfox** [comment]
@jacksonKnight 貌似没有配置，你可以自己编辑 `layout/friends.ejs` 文件中的内容，把评论相关的代码去掉。

**Comment by EscapeLife** [comment]
@jacksonKnight 直接把评论关了，友链也就没有了
