### ISSUE TITLE
Chrome中首页的cover部分显示异常

### ISSUE THREAD

**Issue by liuyaanng** [blinkfox/hexo-theme-matery#529]
在Chrome浏览器中，首页轮播图部分是白屏，在第一次加载的过程，轮播图会闪一下后消失，之后就是白屏
![](https://i.loli.net/2020/09/12/xBVWcTLojEF7GUi.png)
![](https://i.loli.net/2020/09/12/juK2ZGVa6P8qn4M.png)
在Safari上显示正常
![](https://i.loli.net/2020/09/12/kvhYKawGPeZiFtE.png)

**Comment by EscapeLife** [comment]
@liuyaanng 清空缓存，试试看！

**Comment by EscapeLife** [comment]
@blinkfox close吧，有问题再open吧！

**Comment by liuyaanng** [comment]
> @liuyaanng 清空缓存，试试看！

我试过了，有效，谢谢！
