### ISSUE TITLE
手机上文章分类统计图显示有问题

### ISSUE THREAD

**Issue by axh2018** [blinkfox/hexo-theme-matery#530]
![Screenshot_20200914_165709_com.android.chrome.jpg](https://user-images.githubusercontent.com/58505743/93065528-66a2b080-f6ab-11ea-9835-6cd353031c2d.jpg)
如图，Linux只显示出了Linu，在手机chrome和edge上都显示如此。

**Comment by blinkfox** [comment]
跟 `padding` 有关系，内容太宽被挡住了。
