### ISSUE TITLE
首页推荐文章图全灰了

### ISSUE THREAD

**Issue by Nanzet** [blinkfox/hexo-theme-matery#534]
首页推荐文章图灰了，查看源码是这里的图片链接不对，主题配置文件的jsDelivr设置的url和文章里的url拼接在一起了，导致图片显示不出来
![图片](https://user-images.githubusercontent.com/48075743/93603398-8b25c200-f9f6-11ea-8a25-0814f26dde39.png)

**Comment by blinkfox** [comment]
@Nanzet 你再更新下最新代码，你平时使用时，最好下载使用 `master` 分支的代码或者从 `releases` 发布版本中去下载，`develop` 中的还不稳定。

**Comment by Nanzet** [comment]
> 
> 
> @Nanzet 你再更新下最新代码，你平时使用时，最好下载使用 `master` 分支的代码或者从 `releases` 发布版本中去下载，`develop` 中的还不稳定。

ok，已经解决了
