### ISSUE TITLE
代码中的花括号显示错误问题

### ISSUE THREAD

**Issue by proton991** [blinkfox/hexo-theme-matery#536]
![Screenshot 2020-09-23 102654](https://user-images.githubusercontent.com/45759352/93957673-52377580-fd87-11ea-92c4-10c91973f493.png)
有大佬知道怎么解决吗

**Comment by blinkfox** [comment]
应该是 Hexo 的版本问题。

**Comment by lsqi** [comment]
之前遇到过的问题，是因为安装代码高亮插件(hexo-prism-plugin)，我卸载这个插件之后，这个问题是能解决的。

**Comment by houhaoqi** [comment]
> 之前遇到过的问题，是因为安装代码高亮插件(hexo-prism-plugin)，我卸载这个插件之后，这个问题是能解决的。

请问怎么卸载啊，我也有这个问题，还没有解决

**Comment by lsqi** [comment]
> > 之前遇到过的问题，是因为安装代码高亮插件(hexo-prism-plugin)，我卸载这个插件之后，这个问题是能解决的。
> 
> 请问怎么卸载啊，我也有这个问题，还没有解决

我是用npm安装的，卸载命令是 ** npm uninstall hexo-prism-plugin(插件名 )**

**Comment by houhaoqi** [comment]
好的我去试试，感谢

**Comment by blinkfox** [comment]
该问题在 hexo-theme-matery 的 `2.0.0` 版本修复了，建议大家可以直接升级 Hexo 到 5.x 最新版本就行，去掉 hexo-prism-plugin 的插件，直接将内置的 `prismjs.enable` 设置为 `true` 就行。
