### ISSUE TITLE
建议将文章无特色图片时随机选择

### ISSUE THREAD

**Issue by Writeup007** [blinkfox/hexo-theme-matery#546]
目前关于文章无特色图片时的处理方法是：_文章特色图会根据文章标题的 hashcode 的值取余，然后选取主题中对应的特色图片。_这样做的好处显而易见：_达到让所有文章都的特色图各有特色_
但是忽略了一点，就是，在无特色图片文章数量较多的情况下，因为内置只有 24 张图，还是会有一定的概率重复的，如果我想自己添加更多的特色图在里面就需要在主题下的 _config.yml 文件中的 featureImages 项进行添加，当我添加的图片比较多的时候比如100张以上，或者新增了喜欢的图片时就会比较麻烦，而且容易造成 _config.yml 文件阅读起来较不友好。
所以我的建议是不如直接将现有方法改为文章无特色图时，随机从 `/medias/featureimages/` 目录下选取一张，因为我的图片数量较多，有一定重复概率，但是几率较小，应该处于可接受范围。而且使用起来也比较简单粗暴，直接将图片放在指定目录下即可，程序自动随机选择。

**Comment by blinkfox** [comment]
这块儿逻辑不会改哈，你可以自定义改成自己的方式，不过推荐给每篇文章设置自己真正意义上的特色图。
