### ISSUE TITLE
回到顶部的按钮与其他按钮重叠

### ISSUE THREAD

**Issue by jason-bowen-zheng** [blinkfox/hexo-theme-matery#551]
你好, 我增加了 DaoVoice 功能, 但是那个按钮和回到顶部的那个按钮重叠了, 而且 DaoVoice 的按钮似乎不能改动位置:

![image](https://images.gitee.com/uploads/images/2020/1018/132531_0fc36523_7976939.jpeg)

> 在手机上和电脑上是一样的

**Comment by blinkfox** [comment]
以前有一个这样的 [# 402 issue](#402)，你参考改一下就行。

**Comment by jason-bowen-zheng** [comment]
似乎更改样式更方便, 后面那个控制台设置可能需要时间.
