### ISSUE TITLE
不蒜子统计 异常

### ISSUE THREAD

**Issue by linupychiang** [blinkfox/hexo-theme-matery#560]
新创建的博客，显示阅读量、总访问量、总访问人数异常
![image](https://user-images.githubusercontent.com/46371795/98469495-fc296f00-221a-11eb-80e7-8ccbd73e9981.png)
![image](https://user-images.githubusercontent.com/46371795/98469521-18c5a700-221b-11eb-89ce-df4fbda50db6.png)

**Comment by EscapeLife** [comment]
@linupychiang 你这个一看就是测试本地 `http://localhost:4000/` 的网站，这个没有问题，等你 `push` 上去之后就没问题。

**Comment by EscapeLife** [comment]
@blinkfox 不是问题，close了吧

**Comment by linupychiang** [comment]
谢谢， @EscapeLife @blinkfox
