### ISSUE TITLE
访问博客加载不出文章列表

### ISSUE THREAD

**Issue by deckcode** [blinkfox/hexo-theme-matery#567]
部署等都没问题，前天晚上可以用，第二天就用不了了
部署带gitee后访问就出问题了。
![123](https://user-images.githubusercontent.com/54943979/99496261-e6e8d900-29ae-11eb-8723-2e80bae17519.PNG)

![1234](https://user-images.githubusercontent.com/54943979/99496044-8ce81380-29ae-11eb-8c5b-84bf33338b71.PNG)
![12345](https://user-images.githubusercontent.com/54943979/99496051-907b9a80-29ae-11eb-9c6f-03ab3496a91f.PNG)
![123456](https://user-images.githubusercontent.com/54943979/99496054-92455e00-29ae-11eb-908b-5a53f424a672.PNG)

报错！！！

本地测试没问题

![1234567](https://user-images.githubusercontent.com/54943979/99497061-4eebef00-29b0-11eb-8468-3ad5457acdb9.PNG)

**Comment by blinkfox** [comment]
估计是部署的时候，部署目录写的不对吧

**Comment by deckcode** [comment]
可以具体一点吗？。。。

**Comment by blinkfox** [comment]
我记得在 Gitee 里面部署的时候，需要在根 `_config.yml` 文件中把 `root` 属性写成博客项目仓库的名字的。

**Comment by deckcode** [comment]
好的，谢谢。

**Comment by blinkfox** [comment]
解决了吗？

**Comment by deckcode** [comment]
最近比较忙没去弄，过段时间看看。
