### ISSUE TITLE
RSS订阅的问题

### ISSUE THREAD

**Issue by wikun0507** [blinkfox/hexo-theme-matery#568]
博主你好，我的那个RSS订阅点了之后是显示一个XML文件，而且顶上有个报错是：
This XML file does not appear to have any style information associated with it. The document tree is shown below.
我想问下怎么解决。

**Comment by liginity** [comment]
RSS 订阅一般是用软件（比如一些邮件客户端，如 Thunderbird ）来阅读的，点击 RSS 订阅后打开 XML 文件是符合预期的。

**Comment by wikun0507** [comment]
> Thunderbird

好的  谢谢解答
