### ISSUE TITLE
Font awesome CDN

### ISSUE THREAD

**Issue by Micraow** [blinkfox/hexo-theme-matery#570]
我看到现在这个代码加载图标，是通过网络字体的方式加载的，可是我认为这太慢了，影响了我网站的速度，希望能够改为通过font awesome cdn提供。

**Comment by Micraow** [comment]
可以用我的博客来测试一下，现在用的还是jsdelivr 

[我的博客](https://msblog.ml)

**Comment by blinkfox** [comment]
@Micraow 使用者可以自己改配置文件中的 CDN 就行，默认使从部署地去加载的
