### ISSUE TITLE
正文右侧目录样式小问题

### ISSUE THREAD

**Issue by WangQuan-cn** [blinkfox/hexo-theme-matery#571]
刚进入页面是，正文页面右侧目录偏上明显，滚动条向下滚动触发重新布局后，显示正常。

似乎是下面这段代码导致的

https://github.com/blinkfox/hexo-theme-matery/blob/3ddcaee5faa8121c05de197cdff6dff127b09e28/layout/_partial/post-detail-toc.ejs#L31

margin改为padding后，看起来变得正常了。

抱歉暂时没有条件做pr

**Comment by blinkfox** [comment]
谢谢提醒，应该是有人改了相关样式引起的，我已经改了。
