### ISSUE TITLE
请问首页打字效果那里的subtitle在哪里配置或者修改呢？

### ISSUE THREAD

**Issue by chenmg2020** [blinkfox/hexo-theme-matery#574]
# 打字效果副标题.
# 如果有符号 ‘ ，请在 ’ 前面加上 \
subtitle:
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 50 # 打字速度
  backSpeed: 50 # 删除速度
  sub1: 从来没有真正的绝境, 只有心灵的迷途
  sub2: Never really desperate, only the lost of the soul

这里没有标题的配置项，只有副标题？
初次使用，特请教下大家

**Comment by latent-shell** [comment]
我也同问，请问题主找到方法了吗？

**Comment by growdu** [comment]
看这个https://github.com/blinkfox/hexo-theme-matery/issues/386
在_config.yml里修改。

**Comment by EthanLiu6** [comment]
我的NexT8版本咋弄不了
