### ISSUE TITLE
Bug: 点击文章卡片文字会出错

### ISSUE THREAD

**Issue by Micraow** [blinkfox/hexo-theme-matery#576]
我使用Android 上的chrome .
在点击文章卡片下片的文字部分时，不会有卡片放大的特效，或进入文章，反而是页面上元素出错，按钮和标题栏左右摇摆，极为难看，影响使用

问题页面

[问题页面](https://msblog.ml)

**Comment by blinkfox** [comment]
到底什么错呢，有图有真相吗？我点击看没有问题呢

**Comment by Micraow** [comment]
抖动的图截不下来，但确实有问题，在3台设备上实验。特色图片下不是有文字吗？点一下，就会复现这个问题

**Comment by Micraow** [comment]
已修复
