### ISSUE TITLE
TOC目录似乎无法显示一级标题？

### ISSUE THREAD

**Issue by KennyNg-19** [blinkfox/hexo-theme-matery#578]
rt, 右侧TOC目录只能从2级标题开始显示

**Comment by blinkfox** [comment]
是的，一级标题就是文章第一行的大标题，一个文章只有一个，做 TOC 意义不大。

**Comment by EscapeLife** [comment]
话说显示一级标题干啥？

**Comment by KennyNg-19** [comment]
> 话说显示一级标题干啥？

没，我就自己写文章的时候用蛮多H1，然后发现不能用就来issue下
