### ISSUE TITLE
php 代码大括号被转义

### ISSUE THREAD

**Issue by wenjy** [blinkfox/hexo-theme-matery#588]
类似

```php
<?php
class Test
{
}
```

`{` 被转义替换了 `&#123;`

**Comment by wenjy** [comment]
[示例的 博客连接 https://blog.wenjy.top/2018/10/23/design-patten/visitor.html](https://blog.wenjy.top/2018/10/23/design-patten/visitor.html)

**Comment by blinkfox** [comment]
@wenjy 你参考 [README.md](https://github.com/blinkfox/hexo-theme-matery/blob/develop/README_CN.md#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE) 说明文档使用和配置，不要安装以前的 `hexo-prism-plugin` 插件，这个插件几年没更新了。因为 `Hexo 5.0` 自带了 `prismjs` 插件相互冲突了引起的。

**Comment by wenjy** [comment]
@blinkfox 多谢~，晚上回去试一下
