### ISSUE TITLE
artitalk配置好了怎么用？

### ISSUE THREAD

**Issue by guhailong18** [blinkfox/hexo-theme-matery#590]
源代码里面我也没找到theme.artitalk.enable，作者是不是忘记写这个页面了？只有_widget/artitalk.ejs，也没有看到哪里有使用这个文件，有些迷惑。。。。。

哔哔功能似乎也有问题，我的显示效果如下图，[地址](https://blog.guke1.vercel.app/bb)，这说说是要怎么发的，不是很懂啊，求大佬解答
![image](https://user-images.githubusercontent.com/56160866/102444063-34ff0400-4063-11eb-9766-5d109d1ea270.png)

**Comment by blinkfox** [comment]
之前代码审查不严格，应该是之前的贡献人员没有提交引起的。

**Comment by txmu** [comment]
你好，我就是哔哔的贡献者。第一次pr时我没在yaml文件里写全教程。之后的pr中我已经把教程写进去了

**Comment by txmu** [comment]
## 哔哔功能配置
## 登陆leancloud创建应用。进入应用后，点击创建 Class，将「 Class 名称」命名为 content 
## 点击刚刚创建的content Class，点击添加列并创建名称为content的列，类型为String，注意列注释也要填写（随意填）
## 记录appid，masterkey，api域名
## 输入:hexo new page bb
## hexo就在source文件夹下创建了bb/index.md。
修改index.md的frontmater下的layout为bb：
---
title: 黑石说
layout: bb
---
## 里面的文字可以自己随意加，会显示在哔哔的上方。
## 关注公众号 "黑石哔哔"，发送: //bindCurrentUser:你的APPID,你的MASTERKEY,你的RESTAPI 
## 可用leancloud国际版，国际版api为 https://appid前八位.api.lncldglobal.com

**Comment by txmu** [comment]
yaml文件里就有

**Comment by txmu** [comment]
artitalk的问题我也发现了。最近如果有空，我会在我的那个开启的pr中尝试修复一下

**Comment by guhailong18** [comment]
> //bindCurrentUser:你的APPID,你的MASTERKEY,你的RESTAPI

感谢您的解答，我已成功发表说说，发了文字，图片和默认表情包
![image](https://user-images.githubusercontent.com/56160866/102558265-0b4be880-4108-11eb-855c-9f7800d29df3.png)
如上图所示，效果似乎有些不尽人意，图片和表情包都未显示出来，文字的样式也有些与周围不太契合，期待改进(￣︶￣)

**Comment by guhailong18** [comment]
> 之前代码审查不严格，应该是之前的贡献人员没有提交引起的。

看了下PR，已自行解决
![image](https://user-images.githubusercontent.com/56160866/102560322-f2920180-410c-11eb-8aec-c876a32c91f7.png)
待会我提交个PR修复吧
