### ISSUE TITLE
几个小问题，请大佬给个提示

### ISSUE THREAD

**Issue by linuxcpp** [blinkfox/hexo-theme-matery#591]
1. 有关logo： 每次替换了，在/public/medias/下面，每次hexo clean都清除，后又生成最初的那个。
2. 右上角，下拉出现的 fork me 怎么去除掉
3. 个人介绍页，是自动生成的，在主题配置文件里面，如何个性化，不自动生成呢

**Comment by nailu0** [comment]
大部分你想要修改的部件都可以在这个文件中找到
themes\hexo-theme-matery\_config.yml

**Comment by linuxcpp** [comment]
> themes\hexo-theme-matery_config.yml

主要水平不行，大佬能给个具体的提示，比如：fork那个标记怎么去掉

**Comment by blinkfox** [comment]
@linuxcpp 

`logo` 你肯定不能去替换 `public` 里面的啊，那个是生成的文件，你要替换主题文件里面的 `source/medias/` 下的 logo，public 目录下的是根据这些生成的。
Forkme 那个在主题的 `_config.yml` 配置文件中，可以设置 `githubLink.enable` 为 `false`就行。
个人介绍页很多内容也在主题的 `_config.yml` 配置文件中的 `profile` 选项中可以设置自己的内容，`myProjects` 用于设置项目名，不想要可以设置为 `enable` 为  `false`, `mySkills` 相关的是技能类的，同理参看设置就行。如果想完全按自己的风格定制，就相当于自己完全写代码实现了。参考其他页面的代码就行。

**Comment by linuxcpp** [comment]
> @linuxcpp
> 
> `logo` 你肯定不能去替换 `public` 里面的啊，那个是生成的文件，你要替换主题文件里面的 `source/medias/` 下的 logo，public 目录下的是根据这些生成的。
> Forkme 那个在主题的 `_config.yml` 配置文件中，可以设置 `githubLink.enable` 为 `false`就行。
> 个人介绍页很多内容也在主题的 `_config.yml` 配置文件中的 `profile` 选项中可以设置自己的内容，`myProjects` 用于设置项目名，不想要可以设置为 `enable` 为 `false`, `mySkills` 相关的是技能类的，同理参看设置就行。如果想完全按自己的风格定制，就相当于自己完全写代码实现了。参考其他页面的代码就行。

感谢知道
