### ISSUE TITLE
chrom浏览器85版本之后关于不蒜子统计错误的问题

### ISSUE THREAD

**Issue by PoenZhang** [blinkfox/hexo-theme-matery#592]
chrom浏览器85版本之后，默认的Referrer Policy变为了strict-origin-when-cross-origin，导致不蒜子统计时，每篇文章的阅读数都是共用的

**Comment by PoenZhang** [comment]
自己解决了。。。，在主题的layout/_partial/head.ejs文件中，找到head区，随便找个<meta name=....下边增加一行：
<meta name="referrer" content="no-referrer-when-downgrade"" />

**Comment by blinkfox** [comment]
@PoenZhang 可能这是共性问题，那我后续直接在主题中把这个加上。
