### ISSUE TITLE
banner区域可以左右滑动导致手机访问时不容易下滑

### ISSUE THREAD

**Issue by SekiBetu** [blinkfox/hexo-theme-matery#594]
如题，banner区域可以左右滑动确实好看，
但是手机页面进入网页时必须很精确地垂直移动手指才能往下滑动浏览，导致了使用上的不便
是否需要增加一个选项来关闭此功能或者直接删除此功能？

**Comment by blinkfox** [comment]
感觉还好把，没那么难滑吧，目前没有关闭此选项的功能。
