### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Micraow** [blinkfox/hexo-theme-matery#597]
是这样的，我即将做一个项目，想把用户文档发在自己的博客，但这样，它像文章一样发布，就会在首页上显示，大量的文档会使我的技术类文章被冲到第2,3页。能不能添加这个功能，使我可以在front-matter里设置某一篇文章不在首页显示，只在归档，或标签，或分类页面中显示？

**Comment by blinkfox** [comment]
你可以直接把首页的瀑布流文章功能去掉，只把把推荐文章放首页就行了

**Comment by Micraow** [comment]
可，，我又想要瀑布流。。

**Comment by blinkfox** [comment]
那可能你得自己实现了。

**Comment by Micraow** [comment]
能帮我做一下吗？我不会js

**Comment by blinkfox** [comment]
自己加一个 `front-matter` 变量，然后在 ejs 文件里面做判断就行，我最近应该没时间，你可以在 QQ 群里面问问其他人。

**Comment by blinkfox** [comment]
@Micraow 这个功能 @LamForest 已经加了，该 `issue` 我就先关了哈。
