### ISSUE TITLE
博客的这一块没办法修改成中文吗，我已经把语言选成中文了

### ISSUE THREAD

**Issue by WangTingZheng** [blinkfox/hexo-theme-matery#6]
![default](https://user-images.githubusercontent.com/32613835/46484831-208d1300-c82d-11e8-82e6-41652b08297d.png)

**Comment by WangTingZheng** [comment]
还有，建议加上大赏功能

**Comment by blinkfox** [comment]
这个是在主题中的`_config.yml`配置文件中设置的，你把`Index`、`Tags`等改成`首页`、`标签`即可，你也可以配置自己的图标，图标可以参考[Font Awesome](http://fontawesome.dashgame.com/)。

**Comment by blinkfox** [comment]
@WangTingZheng 打赏在后续开发任务里面有，优先级还不高
