### ISSUE TITLE
代码块问题

### ISSUE THREAD

**Issue by ChinaVolvocars** [blinkfox/hexo-theme-matery#605]
![代码块问题](https://user-images.githubusercontent.com/11059094/103163363-1f929280-4838-11eb-9d63-5e2a7730a0d7.PNG)
这个问题怎么解决啊
hexo: 5.3.0
hexo-cli: 4.2.0

hexo-theme-matery-2.0.0

**Comment by blinkfox** [comment]
估计是你配置使用有啥问题引起的

**Comment by KKKErde** [comment]
[C-C-auto.md.tar.gz](https://github.com/blinkfox/hexo-theme-matery/files/5751510/C-C-auto.md.tar.gz)

将这个文件里面的md文件放到 ./source/_posts/ 目录下，然后执行
```
hexo clean && hexo g
hexo s
```
看下是否有问题。hexo自带的那个md似乎是有问题。

**Comment by Liu-rui-bin** [comment]
请问解决了吗，我也出现这个问题

**Comment by zy1120575649** [comment]
我也是这个问题 怎么办

**Comment by zy1120575649** [comment]
> [C-C-auto.md.tar.gz](https://github.com/blinkfox/hexo-theme-matery/files/5751510/C-C-auto.md.tar.gz)
> 
> 将这个文件里面的md文件放到 ./source/_posts/ 目录下，然后执行
> 
> ```
> hexo clean && hexo g
> hexo s
> ```
> 
> 看下是否有问题。hexo自带的那个md似乎是有问题。

还是这样

**Comment by Liu-rui-bin** [comment]
> 我也是这个问题 怎么办
我那个问题图片加载不出来，是什么问题来着。。我忘了，但是好像解决了。。。。

**Comment by zy1120575649** [comment]
![image](https://user-images.githubusercontent.com/16127700/105812796-c8740f00-5fe9-11eb-8157-a17c5dd3f087.png)

**Comment by zy1120575649** [comment]
> > 我也是这个问题 怎么办
> > 我那个问题图片加载不出来，是什么问题来着。。我忘了，但是好像解决了。。。。

![image](https://user-images.githubusercontent.com/16127700/105812844-dcb80c00-5fe9-11eb-9770-e96037b73b73.png)
我的是这个样子 你的也是吗

**Comment by Liu-rui-bin** [comment]
> > > 我也是这个问题 怎么办
> > > 我那个问题图片加载不出来，是什么问题来着。。我忘了，但是好像解决了。。。。
> 
> ![image](https://user-images.githubusercontent.com/16127700/105812844-dcb80c00-5fe9-11eb-9770-e96037b73b73.png)
> 我的是这个样子 你的也是吗
嗯嗯，当初我也出现了这个情况。。。不知道你有没有解决。。。我之前调好的方法可以参考下：https://liuruibin.com/posts/64eb.html#toc-heading-3

**Comment by Liu-rui-bin** [comment]
> > > 我也是这个问题 怎么办
> > > 我那个问题图片加载不出来，是什么问题来着。。我忘了，但是好像解决了。。。。
> 
> ![image](https://user-images.githubusercontent.com/16127700/105812844-dcb80c00-5fe9-11eb-9770-e96037b73b73.png)
> 我的是这个样子 你的也是吗

在代码高亮部分的尾部，有关于这个问题的叙述。。注意改好后hexo clean hexo g 在部署才能看到效果哈。。如果还遇到问题再跟我说哈

**Comment by zy1120575649** [comment]
> > > > 我也是这个问题 怎么办
> > > > 我那个问题图片加载不出来，是什么问题来着。。我忘了，但是好像解决了。。。。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16127700/105812844-dcb80c00-5fe9-11eb-9770-e96037b73b73.png)
> > 我的是这个样子 你的也是吗
> 
> 在代码高亮部分的尾部，有关于这个问题的叙述。。注意改好后hexo clean hexo g 在部署才能看到效果哈。。如果还遇到问题再跟我说哈

哇塞，成功啦！谢谢谢谢

**Comment by niexiaoxiaocheng** [comment]
![image](https://user-images.githubusercontent.com/30178676/110212480-7cfd2c80-7ed6-11eb-8a7b-95b5e318ad39.png)
代码块问题 按照图片，分别修改为false 和true 可解决

**Comment by ExtraBits42** [comment]
emmmmm，遇到了同样的问题，刷评论区解决了！

**Comment by Drun1baby** [comment]
> emmmmm，遇到了同样的问题，刷评论区解决了！

大佬怎么解决的呀

**Comment by Drun1baby** [comment]
已解决 https://blog.csdn.net/Withdraw_end/article/details/120645255?spm=1001.2014.3001.5501

**Comment by ChinaVolvocars** [comment]
我已经解决了

**Comment by ChinaVolvocars** [comment]
我已经解决了
