### ISSUE TITLE
请问是否支持二级分类？ 

### ISSUE THREAD

**Issue by winter91** [blinkfox/hexo-theme-matery#607]
RT

**Comment by blinkfox** [comment]
不支持

**Comment by winter91** [comment]
> 不支持

好的，谢谢！请问后续会有支持计划吗？

**Comment by blinkfox** [comment]
目前暂时没有哈，分类的含义偏向大的分类，如果想细分的话，一般用标签就行，这样也好归类、统计等等。

**Comment by winter91** [comment]
> 目前暂时没有哈，分类的含义偏向大的分类，如果想细分的话，一般用标签就行，这样也好归类、统计等等。

好的，谢谢
