### ISSUE TITLE
search.xml加载慢。

### ISSUE THREAD

**Issue by NongGuangXin** [blinkfox/hexo-theme-matery#617]
查看浏览器控制台发现，/search.xml页面无法通过CDN加速，加载非常慢；而其他图片和资源可以通过CDN加速，有什么办法加速search.xml的加载吗？

**Comment by Tokisaki-Galaxy** [comment]
emm，建议你去看看node_modules目录里面关于搜索的插件，然后改那里面的源码，不过这样太麻烦了。
建议直接换个好点的托管地方

**Comment by NongGuangXin** [comment]
close
