### ISSUE TITLE
如何自定义标签顺序？

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#62]
如何自定义tags页标签的先后显示顺序？
P.S.感谢作者，这是我最钟爱的主题。

**Comment by blinkfox** [comment]
标签顺序是指标签页面里面的标签的顺序吗，在Hexo里面目前来看还没法定义吧。只能自己把所有标签都定义在一个标签的文件数据里面，然后从那个文件数据里面读取标签，但是这样的话，需要经常去维护这个文件，而且需要单独的定制化开发，这个就只能自己去做了吧
