### ISSUE TITLE
关于使用materialize tabs的问题

### ISSUE THREAD

**Issue by tuhongwei** [blinkfox/hexo-theme-matery#622]
当我用到materialize 里面的tabs组件的时候，url上面会出现瞄点，导致一些问题（比如抖动，active设置不生效），调试了下，在执行到materialize tabs之前url上面就会出现瞄点，而且从hexo里面单独拿出来也没有问题，因此可断定是hexo的问题或者主题的问题，不知道blinkfox对此有啥解决办法没

**Comment by blinkfox** [comment]
应该就是样式问题吧，你可以看看主题中赞“赏”的功能，微信和支付宝切换的地方就是用的 `tabs` 页签

**Comment by tuhongwei** [comment]
我刚看了，那个也会造成url上面出现瞄点，但是区别是这个弹框出现的时候没有滚动条的滚动，所以不会出现我之前的那些问题。
我看materialize.js 的源码有调用e.preventDefault()，但是调试的时候是在调用这个之前url上面就出现了瞄点

**Comment by blinkfox** [comment]
你通过样式去除下就行了吧

**Comment by tuhongwei** [comment]
不是样式的问题，是因为href="#test"里面的这个瞄点点击的时候生效了

**Comment by blinkfox** [comment]
那就不太清楚了，那你能不用 # 的方式使用 tab 吗？

**Comment by tuhongwei** [comment]
我看materialize 文档没有提供这种方式，这样的话就只能自己写一个了或者改materialize.js的tabs部分

**Comment by tuhongwei** [comment]
知道原因了，是因为APlayer.min.js 和 clicklove.js中的点击事件造成的影响。
解决办法： 在用到tabs的页面加上这样的代码。
```
$('.tab a').on('click', function (e) {
    e.preventDefault();
});
```
