### ISSUE TITLE
[颜色] 代码块颜色是反色的 代码块有设置模板吗

### ISSUE THREAD

**Issue by datager** [blinkfox/hexo-theme-matery#626]
[这个是的blog中有问题的代码块](https://sonnary.github.io/2021/02/16/c%E8%AF%AD%E8%A8%80/unix%E7%BC%96%E7%A8%8B/ )

![image](https://user-images.githubusercontent.com/19160032/108090863-14304a80-70b6-11eb-82ec-4c37ba7dcb14.png)

按hexo-theme-matery的github中文文档设置了一遍, 但是字体有问题, 应该怎么调整呢

[以下是我的hexo-theme-matery/source/css/matery.css配置](https://github.com/sonnary/blog)

已经设置过`npm uninstall hexo-prism-plugin`了

**Comment by datager** [comment]
需要设置prismjs.enable=true

**Comment by churoc** [comment]
我也出现了这个问题，但是我是改了/source/css/matery文件里的pre，本来没有margin和background，不知道是不是下载时出错了，借这个issue写一下，方便以后遇到同类问题的朋友。
