### ISSUE TITLE
subtitle和description中文显示乱码

### ISSUE THREAD

**Issue by Zessay** [blinkfox/hexo-theme-matery#63]
显示乱码请问大佬该怎么解决

**Comment by zhaohaichaozhc** [comment]
我也是

**Comment by blinkfox** [comment]
@Zessay @zhaohaichaozhc 你们检查下你们的根配置文件`_config.yml`的编码是否是`UTF-8`，这两个字段的值是从主配置文件的`_config.yml`文件中读取的。

**Comment by zhaohaichaozhc** [comment]
谢谢大佬😍，将配置文件保存成UTF-8格式就可以了

**Comment by GoffyW** [comment]
配置文件编码合适，但上面说的这两个属性还是乱码问题，麻烦前辈指示一下。谢谢

**Comment by blinkfox** [comment]
@GoffyW 检查下自己所有的文件是否是 `UTF-8` 吧，这个一般都是文件编码问题
