### ISSUE TITLE
谁能帮我把首页滤镜去掉！！！求求了

### ISSUE THREAD

**Issue by akqaq** [blinkfox/hexo-theme-matery#630]

**Comment by axh2018** [comment]
readme，不用谢

**Comment by blinkfox** [comment]
把主题中的 `matery.css`  的 `@-webkit-keyframes rainbow` 和 `@keyframes rainbow` 相关的内容去掉，或修改为自己的颜色样式等等

**Comment by akqaq** [comment]
> 
> 
> 把主题中的 `matery.css` 的 `@-webkit-keyframes rainbow` 和 `@keyframes rainbow` 相关的内容去掉，或修改为自己的颜色样式等等

OKOK，多谢！
