### ISSUE TITLE
代码高亮显示失效问题

### ISSUE THREAD

**Issue by sherlonWang** [blinkfox/hexo-theme-matery#64]
可能也有人跟我一样，刚接触Markdown语法，在用这个主题时，发现代码高亮部分不起作用。代码块渲染时需要声明语言才能被正确渲染，如下所示，渲染java代码，这样写就可以了。

‘’’java
public static void main(String[] args){
	System.out.println("hello world");
}
‘’’
github上也是用markdown语法渲染的...这里示例的代码块为了不让github渲染替换成了单引号',实际以 ` 为准。

**Comment by blinkfox** [comment]
要声明语言的，这是`prism.js`插件所限制的，[这个链接](https://prismjs.com/#languages-list)是Prism.js所支持的语言的写法。

**Comment by blinkfox** [comment]
这个不算问题，我把这个`issue`关了。
