### ISSUE TITLE
文章字体大小

### ISSUE THREAD

**Issue by wwwei1997** [blinkfox/hexo-theme-matery#643]
你好，请问在哪能够修改文章的字体大小呢，感觉默认字体太小了

**Comment by blinkfox** [comment]
@wwwei1997 每种页面元素的字体大小控制不一样，你在浏览器中可以 F12 看看，每个元素的字体，主要是 `<p></p>` 标签字体的大小，你改改就行。

你可以在 `hexo-theme-matery/source/css/my.css` 文件中添加对应的字体大小的样式，会覆盖默认的。

**Comment by wwwei1997** [comment]
已解决，谢谢
