### ISSUE TITLE
当视频在第三方网站时，一般那个网站提供的是iframe来分享

### ISSUE THREAD

**Issue by yuxuanh** [blinkfox/hexo-theme-matery#644]
bilibili，爱奇艺都是如此。

**Comment by blinkfox** [comment]
@yuxuanh 你可以改下代码，新增一种适配情况，来适配 iframe 的情形

**Comment by yuxuanh** [comment]
I have added this. 看看会不会有用，因为一开始我会以为播放页放上去url是可以的，结果是不行的。我在config也加了comment。
https://github.com/blinkfox/hexo-theme-matery/pull/645

**Comment by luanxinchen** [comment]
老哥很秀，我刚好有这个需求，下班回去试一下 :laughing:

> I have added this. 看看会不会有用，因为一开始我会以为播放页放上去url是可以的，结果是不行的。我在config也加了comment。
> #645
