### ISSUE TITLE
配置jsDelivr 导致博客图片显示异常

### ISSUE THREAD

**Issue by Rui2450** [blinkfox/hexo-theme-matery#649]
有问题的代码:
``` php
background-image: url('<%- theme.jsDelivr.url %><%- url_for(coverImg) %>');
```
如果你的coveimg 是来自其他网站的内容 
这行代码导致url会拼接为
```
background-image: url('https://cdn.jsdelivr.net/gh/rui2450/rui2450.github.iohttps://z3.ax1x.com/2021/04/14/cgSHl4.jpg');
```

**Comment by blinkfox** [comment]
@Rui2450 那你直接把那个图片放在 jdDelivr 中就行

**Comment by Rui2450** [comment]
@blinkfox 
感谢回复
这样写主要是能用图床节省空间,我把<%- theme.jsDelivr.url %>直接删掉了, 当然不能用也不是大问题,
不过能问下这个模板支持类似这样的逻辑么
判断 url_for(coverImg)的前缀 如果是http开头就 不拼接<%- theme.jsDelivr.url %>
