### ISSUE TITLE
文章转载规则生成的链接不对,在gitee子项目下部署博客

### ISSUE THREAD

**Issue by luwanglin** [blinkfox/hexo-theme-matery#655]
你好,我是在gitee 的非用户名仓库下部署的博客,博客源码所在仓库为https://gitee.com/LuWangLin/luckyforefforts
但是在生产转载文章链接时,出现以下问题
这是本来的访问链接https://luwanglin.gitee.io/luckyforefforts/2020/08/19/java-fan-xing/,
但是生产的转载链接中多加了一个luckyforefforts,如下
![image](https://user-images.githubusercontent.com/34809270/115998459-e7e6fc00-a619-11eb-9323-4913ae7b20a8.png)
后来在配置文件中加上了
```
url: https://luwanglin.gitee.io/luckyforefforts
root: /luckyforefforts
```
生成的链接还是都是上面那样,多加了一个luckyforefforts

**Comment by blinkfox** [comment]
@luokangyuan 你的 url 就不用加 `luckyforefforts` 了

**Comment by luwanglin** [comment]
> @luokangyuan 你的 url 就不用加 `luckyforefforts` 了

好的，非常感谢解决问题了
