### ISSUE TITLE
友链出现无法更新的现象

### ISSUE THREAD

**Issue by hamsali** [blinkfox/hexo-theme-matery#667]
这个友链测试的时候正确的，部署的时候友链无法渲染在HTML。
friends.json 中，的信息不能更新在网站上。

**Comment by blinkfox** [comment]
一版可能是缓存引起的

**Comment by cnrkuo** [comment]
一樣的問題
清除 cache 即可

**Comment by hamsali** [comment]
> 一版可能是缓存引起的

> 一樣的問題
> 清除 cache 即可

谢啦很久以前已经好了O(∩_∩)O
