### ISSUE TITLE
代码块重复显示

### ISSUE THREAD

**Issue by dingiso** [blinkfox/hexo-theme-matery#669]
您好，我照着，readme 里删除了插件并且对 config.yml 进行了更改,但是显示效果是这样的，请问有人遇到了同样的问题么？
![image](https://user-images.githubusercontent.com/43989619/121812210-a24dc380-cc99-11eb-8e13-ec4e578d4553.png)

**Comment by blinkfox** [comment]
你需要 hexo clean 下，清除掉之前的数据。

**Comment by dingiso** [comment]
好的，已成功解决，非常感谢
