### ISSUE TITLE
建议加个黑暗模式

### ISSUE THREAD

**Issue by fzxhub** [blinkfox/hexo-theme-matery#678]
建议加个黑暗模式，看文档可以非常舒服。

**Comment by lxl80** [comment]
我也想提这个需求，+1

**Comment by SuCicada** [comment]
+1

**Comment by aloeJun** [comment]
这个不是已经有了吗？

**Comment by fzxhub** [comment]
> 这个不是已经有了吗？

**Comment by fzxhub** [comment]
> 这个不是已经有了吗？

怎么使用的？  说明里面没有看到。

**Comment by aloeJun** [comment]
https://www.islu.cn/posts/21369.html 自己配置一下吧

**Comment by fzxhub** [comment]
> https://www.islu.cn/posts/21369.html 自己配置一下吧

👌

**Comment by EscapeLife** [comment]
@ialoe 哈喽，这个暗色模式，是不是可以考虑提一个pr呢？
