### ISSUE TITLE
TOC样式问题

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#69]
我想要在每个h2标题的左边加上一个小矩形，像这样
![](https://i.loli.net/2019/02/08/5c5d7806f3cec.png)
于是我在h2的css里加上 `border-left` 的代码

但是这样会带来问题
![](https://i.loli.net/2019/02/08/5c5d7a5515e78.png)

原主题中，为了**规避toc跳转后，标题被菜单挡住，在源代码**中有
```
padding-top: 76px;
margin-top: -76px;
````
但是因为有了`padding-top`，导致 `border-left` 高度太高

就像上图一样

请问有什么好的解决办法呢？

**Comment by blinkfox** [comment]
我也没啥好办法，你可以再研究研究。

**Comment by lzctuhao** [comment]
解决了，用了`h2:before`里面设置`border-left`
感谢大佬关注！

**Comment by blinkfox** [comment]
@lzctuhao 嗯，好的。
