### ISSUE TITLE
代码复制的问题

### ISSUE THREAD

**Issue by Kong-Aobo** [blinkfox/hexo-theme-matery#694]
复制代码

![image](https://user-images.githubusercontent.com/64878837/131236770-61d455f2-9c51-4dca-98aa-75beaa186a64.png)

无论是手动复制还是直接点击  
粘贴后会变成一行 如下图
![image](https://user-images.githubusercontent.com/64878837/131236739-3acbcf96-eedf-4705-947d-83208de0b6cd.png)

这是怎么回事呢，求教。

**Comment by BlueSky01st** [comment]
你应该是用了代码压缩的插件。
