### ISSUE TITLE
怎么把分享文章的那一排button去掉？

### ISSUE THREAD

**Issue by jiachangyang1025** [blinkfox/hexo-theme-matery#70]
每篇文章下面有一排按钮分享去微信，Facebook，Google等等的，在哪里可以去掉这些按钮？非常感谢。btw, 非常喜欢这个布局，很漂亮。

**Comment by lzctuhao** [comment]
你试试删除`\themes\hexo-theme-matery\layout\_partial\share1.ejs`文件，
应该就可以了

**Comment by blinkfox** [comment]
@jiachangyang1025 在主题的`layout/_partial/post-detail.ejs`文件中，大概`76`的行的位置，去掉`<%- partial('_partial/share') %>`这一行代码即可。

**Comment by jiachangyang1025** [comment]
> @jiachangyang1025 在主题的`layout/_partial/post-detail.ejs`文件中，大概`76`的行的位置，去掉`<%- partial('_partial/share') %>`这一行代码即可。

就是这个，非常感谢。
