### ISSUE TITLE
BUG之关于首页的文章显示顺序不按照时间排列

### ISSUE THREAD

**Issue by xzajyjs** [blinkfox/hexo-theme-matery#709]
# 首页的文章瀑布流有部分不按照时间顺序排列，而默认的档案分页中的时间轴能正确显示。
![](https://serverless-page-bucket-lv779z7b-1307395653.cos-website.ap-shanghai.myqcloud.com/other/kk.png)

**Comment by xzajyjs** [comment]
# 文章头的日期格式如下：
```
date: 2021-08-18 18:57:29
```
# 本来是首页设置的12篇文章，从第7篇顺序开始乱。即使将首页文章个数调成6个，则第二页的总序第七个之后仍然是乱序

**Comment by blinkfox** [comment]
瀑布流的顺序不是从左到右，而是从上到下。

**Comment by xzajyjs** [comment]
### 不管是从左向右还是从上到下**顺序逻辑**似乎有点问题呀。
- 如果从左往右看，第一排的第一个到第三个然后接着第二行的第一个到第三个这六篇的时间顺序正好是按照从新到旧。
- 如果从上到下看，第一列从上到下看到底，然后开始第二列，但是第二列的第一个的日期比第一列最后一个的日期要新。

#### 根据很多其他人的matery主题(例如[这里](https://www.sqlsec.com))，日期顺序应该是按照行优先、行中自左向右。
#### 这是我网站首页的链接，具体你可以点开看一看,[点我](https://xzajyjs.cn/)

**Comment by blinkfox** [comment]
因为你的卡片高度不一致，后续更高的，顺序会优先计算在前面
