### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#71]
请问：
## Q1
![](https://i.loli.net/2019/02/10/5c5fdca70e5cf.png)
在小屏幕手机下，过长的菜单栏会和联系方式重叠。

上图是iPhoneSE ios12的safaria浏览器的截屏

## Q2

现在已知`page.category`的值为`test1`，

我想要在当前页面写出 `根目录/source/_data/test1.md` 里面的文件，为什么不能用如下代码：（注释//是我后面加的）？
``` EJS
<% var name = page.category ;%>  //name=test1

<div class="card-content">
            <%- site.data.name %>    //写出_data/test1.md的内容
</div>
```

PS: 我本来是想要在每个category页加上一段介绍文字的

打扰大佬了，谢谢！

**Comment by blinkfox** [comment]
@lzctuhao 要解决第一个问题的话，得加滚动条了；第二个问题`_data`目录下的文件只能是`json`或者`yml`文件吧。

**Comment by lzctuhao** [comment]
但是下面的代码是可以成功把`根目录/source/_data/cate1.md`内容写出到当前页面的啊~
```
<div class="card-content">
    <%- site.data.cate1 %>
</div>
```

但是如果这样写，那么所有分类的介绍都会显示成cate1的介绍了

**Comment by blinkfox** [comment]
不清楚你的这个操作，真要显示介绍，我觉得做一个`json`文件，然后读取好点儿吧

**Comment by lzctuhao** [comment]
嗯嗯，好的，我本来还想读取与分类同名的md文件呢
您这个思路会更好一些，我试试
感谢大佬不厌其烦的指教～

大佬要早点睡哦～（逃

**Comment by lzctuhao** [comment]
嗯，用`json`已经实现了，但是如果json里面包含html代码就比较麻烦

**Comment by blinkfox** [comment]
还可以用`yaml`文件也行。

**Comment by lzctuhao** [comment]
已经改用`yml`了，`yaml`可以完美解决问题，并且简洁很多！谢谢大佬！！！

**Comment by guhailong18** [comment]
可以把代码放出来吗？给我这种小白借鉴一下

**Comment by guhailong18** [comment]
> 已经改用`yml`了，`yaml`可以完美解决问题，并且简洁很多！谢谢大佬！！！

求代码
