### ISSUE TITLE
生成博客时，代码报错

### ISSUE THREAD

**Issue by SummerSec** [blinkfox/hexo-theme-matery#719]
![image](https://user-images.githubusercontent.com/47944478/137607092-baaedbb1-7c84-40ef-9a39-6b1f5a3967a9.png)

**Comment by SekiBetu** [comment]
盲猜你的配置文件哪里写错了，大多数都是写 `true` 或者 `false`，而不是什么 `enable`

**Comment by SummerSec** [comment]
一个配置写了两次。
