### ISSUE TITLE
编译时，archive.ejs报错

### ISSUE THREAD

**Issue by chunlintang** [blinkfox/hexo-theme-matery#72]
![image](https://user-images.githubusercontent.com/8286273/52686292-fe985f80-2f87-11e9-913a-c621010137a0.png)

编译报了个错，打开归档页面显示的和首页是一样的，没有归档文章。。。求问怎么回事。。。

**Comment by chunlintang** [comment]
找到原因了，问题出在archive.ejs代码注释上了。
![image](https://user-images.githubusercontent.com/8286273/52691663-7ff9ed00-2f9c-11e9-8a33-b3315b08a2db.png)

按理说注释没有问题，但就是会报错，具体原因还待查。。。

**Comment by blinkfox** [comment]
一直在用，都没你这个问题呢，是不是你`hexo`或者`ejs`版本有问题额。

**Comment by chunlintang** [comment]
> 一直在用，都没你这个问题呢，是不是你`hexo`或者`ejs`版本有问题额。

大概率有可能这个原因，在stackoverflow上有看到类似的问题，是hexo版本的问题，我目前是
```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
node: 11.7.0
v8: 7.0.276.38-node.16
uv: 1.24.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
cldr: 34.0
icu: 63.1
tz: 2018e
unicode: 11.0
```

**Comment by chunlintang** [comment]
可以close掉这个issue了

**Comment by mikexfreeze** [comment]
> 一直在用，都没你这个问题呢，是不是你`hexo`或者`ejs`版本有问题额。

请问你的hexo版本是多少啊，我也遇到同样的问题

**Comment by chunlintang** [comment]
> > 一直在用，都没你这个问题呢，是不是你`hexo`或者`ejs`版本有问题额。
> 
> 请问你的hexo版本是多少啊，我也遇到同样的问题

3.8.0

**Comment by mikexfreeze** [comment]
升级了所有包之后正常了
`"dependencies": {
    "hexo": "^3.8.0",
    "hexo-admin": "^2.3.0",
    "hexo-deployer-git": "^0.3.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-permalink-pinyin": "^1.0.0",
    "hexo-prism-plugin": "^2.3.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }`
