### ISSUE TITLE
关于 Release 的使用

### ISSUE THREAD

**Issue by ChungZH** [blinkfox/hexo-theme-matery#73]
可以定期发布一个新版本在 [Releases](https://github.com/blinkfox/hexo-theme-matery/releases) 中，以便配合 GitHub 的 `Releases only` 的 `watch` 方式 :heart:

> 目前许多 hexo 主题都是这样管理版本的

**Comment by blinkfox** [comment]
嗯，后续我看看

**Comment by blinkfox** [comment]
已经在 [Releases](https://github.com/blinkfox/hexo-theme-matery/releases) 中发布了版本，我关闭这个`issue`了哈。
