### ISSUE TITLE
代码高亮出现严重问题，希望可以快一点解决

### ISSUE THREAD

**Issue by EthantLu** [blinkfox/hexo-theme-matery#731]
### 问题如下
1. 代码<>内的元素消失
2. 没有高亮显示
3. 非选择性部分代码随机消失
4. 页面因代码块出现严重问题

**Comment by syunaht** [comment]
有错误示例吗，看不到示例开发者也不好办吧

**Comment by EthantLu** [comment]
> 有错误示例吗，看不到示例开发者也不好办吧

已经解决问题了，是因为那个高亮插件无法识别C++语言
