### ISSUE TITLE
请问支持Github.io吗

### ISSUE THREAD

**Issue by TinyuZhao** [blinkfox/hexo-theme-matery#732]
我安装文档说明配置后上传到github上，就收到了官方邮件说不支持这个theme
![image](https://user-images.githubusercontent.com/44396641/138786025-f9c3eef8-24f6-4422-9af9-8f8f4b9c14ce.png)

**Comment by EscapeLife** [comment]
@Tinyu-Zhao 支持，只要是主题都支持
