### ISSUE TITLE
文章标题过多，导致目录显示不全

### ISSUE THREAD

**Issue by teamssix** [blinkfox/hexo-theme-matery#733]
作者您好，感谢作者开发出如此美观优雅的主题，今天在更新文章时，发现当文章标题过多时会出现目录显示不全的问题，这个需要怎么解决呢？

目录显示不全的文章地址：https://teamssix.com/211027-163641.html

**Comment by blinkfox** [comment]
我看文章太长了，你可以把文章切分为上下篇，或者（一）、（二）、（三）之类的篇章，每篇不会很长，目录也能显示得全。
