### ISSUE TITLE
文章内锚点无法跳转，只能跳一级标题五级标题六级标题，且不支持中文

### ISSUE THREAD

**Issue by limitlm** [blinkfox/hexo-theme-matery#748]
![image](https://user-images.githubusercontent.com/60577891/142014484-5d2c2c02-0f92-480d-b22c-35e8bc13afef.png)
如图markdown文章使用
\[文章内部锚点](#二级标题)
[文章内部锚点](#二级标题)
无法跳转文章内部锚点
猜测的原因是因为id对应不上
html里面h1，h5，h6的id就是对应markdown文章内一级标题五级标题六级标题的文本
测试：文章有个六级标题，名字是test 使用   \[跳转到test](#test)   结果确实能够成功跳转
而html内h2，h3，h4的id自动生成为“toc-heading-序号”，与markdown中文对应不上导致无法跳转
另一个问题是markdown内使用   \[跳转到顶部](#顶部) 
在生成的html中会被替换成   \[跳转到顶部](#%E9%A1%B6%E9%83%A8) 
导致不支持中文锚点跳转
这个情况在next主题上没有出现过
所以应该是matery主题出现了bug

**Comment by limitlm** [comment]
![image](https://user-images.githubusercontent.com/60577891/142743292-1350cf1e-0211-4a82-8a80-73e2a7a67447.png)
原因是这个，toc目录为了支持中文跳转，特地写了函数为每个h2，h3，h4标题创建英文id
所有开启toc目录就不能使用文章内部锚点跳转
想使用文章内部锚点跳转就得关闭toc功能
有没有两者兼容的方法呢

**Comment by appotry** [comment]
butterfly 主题支持中文锚点没问题，可以参考butterfly主题

**Comment by appotry** [comment]
看着已经可以支持中文，需要修改一下

https://github.com/tscanlin/tocbot/pull/84


Fixed Issue: [[#81](https://github.com/tscanlin/tocbot/issues/81)](https://github.com/tscanlin/tocbot/issues/81) [[#82](https://github.com/tscanlin/tocbot/issues/82)](https://github.com/tscanlin/tocbot/issues/82)

In the `tocbot/src/js/scroll-smooth/index.js`

```
var tgt = document.querySelector('[id="' + target.split('#').join('') + '"]')
```

- `tgt`: [object HTMLHeadingElement] target element
- `target`: [string] toc item, a.herf

When heading is nonASCII, a.herf will be encoded, but `id` attribute will be not encoded, it leads to not finding the tgt element by id.

For example, `WMI读取硬件信息` will encoded to `WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF`, but its `id` attribute is still `WMI读取硬件信息`, so `document.querySelector('[id="WMI%E8%AF%BB%E5%8F%96%E7%A1%AC%E4%BB%B6%E4%BF%A1%E6%81%AF"]')` can't find element, should be `document.querySelector('[id="WMI读取硬件信息"]')`.

After I add a decoding, it works on nonASCII heading.

```
// DecodeURI for nonASCII hashes, they was encoded, but id was not encoded, it lead to not finding the tgt element by id.
var tgt = document.querySelector('[id="' + decodeURI(target).split('#').join('') + '"]')
```

**Comment by appotry** [comment]
https://github.com/blinkfox/hexo-theme-matery/pull/779

已经提交修复，  测试可用 [自定制修改](http://blog.17lai.site/posts/40300608/#%E8%87%AA%E5%AE%9A%E5%88%B6%E4%BF%AE%E6%94%B9)

**Comment by limitlm** [comment]
原来只要删掉那个生成id的函数就能解决，属实没想到
