### ISSUE TITLE
新版本开启背景图片后，在移动端上，背景图会被垂直拉伸

### ISSUE THREAD

**Issue by limitlm** [blinkfox/hexo-theme-matery#749]
电脑访问显示正常，手机访问，背景图就会被垂直拉伸，不太美观。。。

**Comment by appotry** [comment]
嗯，应该事我提交的
不拉伸就会超出屏幕。 很多pagetest工具都会报错

**Comment by limitlm** [comment]
> 嗯，应该是我提交的 不延伸长度。

![image](https://user-images.githubusercontent.com/60577891/142739847-b208aeea-045d-4e96-9d1d-34bbb3de428d.png)
我这样更改后就和旧版本的显示效果差不多，不知道会不会报错。

**Comment by limitlm** [comment]
能看就行
