### ISSUE TITLE
博主，这种情况怎么办？

### ISSUE THREAD

**Issue by DDDANBO** [blinkfox/hexo-theme-matery#75]
![360 20190217152050362](https://user-images.githubusercontent.com/46922471/52909717-04fc4380-32c8-11e9-9969-90e998690e96.jpg)

**Comment by DDDANBO** [comment]
博主，左边文章内容和右边目录索引不一致怎么办？

**Comment by blinkfox** [comment]
你好，已修复此问题，可以下载使用[最新版](https://github.com/blinkfox/hexo-theme-matery/releases)的主题。
