### ISSUE TITLE
valine评论出现错误

### ISSUE THREAD

**Issue by handbye** [blinkfox/hexo-theme-matery#753]
```
Code -1: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc. [N/A GET https://us.avoscloud.com/1.1/classes/Comment]
```
![image](https://user-images.githubusercontent.com/26617058/143668220-6bd8276e-9905-4beb-aaa8-f46a8a17f544.png)

**Comment by handbye** [comment]
valine升级到最新版本问题解决

**Comment by Bin0Liu** [comment]
> valine升级到最新版本问题解决

Hi, 我也出现同样问题，请问如何升级？求指引

**Comment by handbye** [comment]
> > valine升级到最新版本问题解决
> 
> Hi, 我也出现同样问题，请问如何升级？求指引
![image](https://user-images.githubusercontent.com/26617058/145741095-4d705ced-7cb2-4b67-a51d-dfce76da7ab0.png)
修改配置文件中的这里即可

**Comment by Bin0Liu** [comment]
@handbye 感谢大佬，已解决。

**Comment by JiakaiYang** [comment]
![image](https://user-images.githubusercontent.com/79317176/146384192-d7945898-3b50-413a-8fc8-a8168d407b12.png)
如何使用coolpushkey???
