### ISSUE TITLE
Banner图红色背景

### ISSUE THREAD

**Issue by fun-li** [blinkfox/hexo-theme-matery#756]
打开页面时 banner图片一瞬间是红色背景  比较违和  css菜鸡 能否教一下怎么配置

**Comment by limitlm** [comment]
在主题文件的 /source/css/matery.css 文件中，找到这两个，注释掉或删掉就行了
分别是什么效果我给忘了，作者注释都是动态切换背景颜色
你去每次删一项试一下吧，成功了可以告诉我分别是什么效果吗QAQ

@-webkit-keyframes rainbow {
   /* 动态切换背景颜色. */
}

@keyframes rainbow {
    /* 动态切换背景颜色. */
}

**Comment by fun-li** [comment]
等我回家试一试
