### ISSUE TITLE
使用Github action自动部署失败

### ISSUE THREAD

**Issue by Super-YYQ** [blinkfox/hexo-theme-matery#757]
大佬你好，我是用这个主题在本地可以成功部署且推送至github page，之后我想使用github action 自动部署的时候一直报错，请问有使用action部署的方案嘛，或者能帮忙看下我这是哪里出问题了嘛？

https://github.com/Super-YYQ/yyqblog/runs/4497644502?check_suite_focus=true

**Comment by Super-YYQ** [comment]
源码仓库（私钥）和静态文件仓库（公钥）中已分别放入secret。

**Comment by limitlm** [comment]
可以检查一下
源码仓库的secret名字是不是HEXO_DEPLOY_PRI
公钥的话直接放在个人设置的SSH and GPG keys选项→ssh keys里面
