### ISSUE TITLE
关于banner下和header右侧的GitHub链接

### ISSUE THREAD

**Issue by churoc** [blinkfox/hexo-theme-matery#758]
您好，想问一下这两个代码块有什么区别，都能在首页生成一个GitHub链接
![两个github区别](https://user-images.githubusercontent.com/96056308/146185605-0c399483-1b45-4257-9da4-247cb26b15b6.PNG)

**Comment by limitlm** [comment]
位置不一样
第一个是在首页中间的开始阅读旁边添加一个按钮，跳转到GitHub
第二个是在header栏，就是右上角添加一个GitHub的跳转链接

**Comment by churoc** [comment]
谢谢你的回答，
我做了一些尝试：
![test](https://user-images.githubusercontent.com/96056308/146284968-63c75319-fecf-4d3a-a327-74ad53f7e231.PNG)
打开header显示，关闭在banner显示，结果还是在开始阅读右侧有一个按钮
![fork me](https://user-images.githubusercontent.com/96056308/146285054-3653e649-894a-4ed6-a27a-35fda9a45d24.PNG)

**Comment by limitlm** [comment]
抱歉 有可能是我记反了 你可以反过来重新尝试一下
我自己是两个都关掉了的

**Comment by churoc** [comment]
我也都关掉了，虽然使用起来没什么影响，但是比较好奇。

你没有记反，githubLink对应的按钮确实在右上角header，但是它在开始阅读右侧这个按钮未启动的时候就会顶替上去，就像上图所示“FORK ME”

没学过前端，一点也看不懂css文件。
