### ISSUE TITLE
添加css/js文件路径配置选项

### ISSUE THREAD

**Issue by pygyme** [blinkfox/hexo-theme-matery#76]
为了加快访问速度，会把博客涉及的css/js文件切换成CDN提供的URL路径，这样就要改ejs文件；

这样过于繁琐，如果能在主题配置文件里直接设置会更加方便。

**Comment by pygyme** [comment]
最好注明版本号

**Comment by blinkfox** [comment]
嗯，后续考虑吧

**Comment by blinkfox** [comment]
你好，已调整了这个配置功能，可以下载使用[最新版](https://github.com/blinkfox/hexo-theme-matery/releases)的主题。

**Comment by birajpaul600** [comment]
birajpaul600@gmail.com
