### ISSUE TITLE
使用vercel+mongodb配置的twikoo遇到无法显示的问题

### ISSUE THREAD

**Issue by hengxingstu** [blinkfox/hexo-theme-matery#791]
作者大大你好，我在配置twikoo时，遇到了问题：无法加载评论
![image-20220402200713585](https://s2.loli.net/2022/04/02/bYBONkx2yLWGvcg.png)
我是使用vercel+mongodb方式部署的云函数，得到的链接是`https://twikoo-hengxing.vercel.app/`，访问的效果是正常的，然后我在`_config.yml`中这样配置：

```
twikoo:
 enable: true
 envId: https://twikoo-hengxing.vercel.app/
```

就出现了上面的报错

我注意到报错有如下内容：

```shell
Access to XMLHttpRequest at 'https://tcb-api.tencentcloudapi.com/web?env=https%3A%2F%2Ftwikoo-hengxing.vercel.app%2F' from origin 'https://hengxingstu.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Uncaught (in promise) Error: network request error
```

似乎是matery将我的vercel链接当作了腾讯云的envid。这种情况如何处理呢，有解决方式吗？

在butterfly主题中，是这么处理的

> 若为腾讯云，使用envid。若为vercel，使用URL

另外我测试时使用issue中提供的envid是部署成功的，所以配置方面也没有什么问题

**Comment by tuoyou-hao** [comment]
试试看使用最新版的twikoo？在主题matery底下的_config.yml中修改
js:
    twikoo: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.all.min.js

**Comment by hengxingstu** [comment]
> 试试看使用最新版的twikoo？在主题matery底下的_config.yml中修改
> js:
>     twikoo: https://cdn.jsdelivr.net/npm/twikoo/dist/twikoo.all.min.js 

你好，确实是这个问题，已经解决。多谢回答
