### ISSUE TITLE
音乐播放器未生效

### ISSUE THREAD

**Issue by zanwen** [blinkfox/hexo-theme-matery#80]
您好，按照您博客中的所说配置了音乐播放器，但并未生效，该怎么办？

**Comment by zanwen** [comment]
我在站点目录下的source文件夹下添加了musics.json：
[{
    "name": "五月雨变奏电音",
    "artist": "AnimeVibe",
    "url": "http://xxx.com/music1.mp3",
    "cover": "http://xxx.com/music-cover1.png"
}, {
    "name": "Take me hand",
    "artist": "DAISHI DANCE,Cecile Corbel",
    "url": "/medias/music/music2.mp3",
    "cover": "/medias/music/cover2.png"
}, {
    "name": "Shape of You",
    "artist": "J.Fla",
    "url": "http://xxx.com/music3.mp3",
    "cover": "http://xxx.com/music-cover3.png"
}]
在主题目录下的_config.yml中添加了：
# 是否在首页显示音乐.
music:
  enable: true
  showTitle: false
  title: 听听音乐
  fixed: false 
  autoplay: false 
  theme: '#42b983'
  loop: 'all' 
  order: 'list' 
  preload: 'auto' 
  volume: 0.7 
  listFolded: false
  listMaxHeight: 90

但hexo generate后并未出现播放器

**Comment by blinkfox** [comment]
你得修改`musics.json`中的音乐`url`和`cover`的链接地址改成你自己的，你开过吗？

**Comment by zanwen** [comment]
改过，但仍没有生效。即使地址不对那插件应该也能加载出来吧，F12也没有报404。不过还好，之后我通过APlayer插件做好了

**Comment by blinkfox** [comment]
首页激活`music.ejs`的条件是：`if (theme.music.enable && site.data && site.data.musics) {`，`music.ejs`文件中也会去加载本地`libs`中的`aplayer`插件的，遇到你这种情况你可以分析下原因，是什么导致的，我们没有出现过这些问题呢。

**Comment by blinkfox** [comment]
你好，如果没有这方面的疑问的话，我就关闭这个`issue`了哈。
