### ISSUE TITLE
请问是否有代码块自动折叠功能

### ISSUE THREAD

**Issue by Halecoder** [blinkfox/hexo-theme-matery#838]
代码块能自动折叠吗，太长了不太好滚屏阅读

**Comment by zxalive** [comment]
主题配置yaml文件内

# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: false # 代码是否折行

**Comment by appotry** [comment]
个人实现了一个代码框折叠功能

实现效果见链接 [Vercel 自定义Header缓存时间](https://blog.17lai.site/posts/e922fac8/#%E8%87%AA%E5%AE%9A%E4%B9%89Header%E7%BC%93%E5%AD%98%E6%97%B6%E9%97%B4)
