### ISSUE TITLE
文章链接分享到微信没有缩略图...

### ISSUE THREAD

**Issue by thismj** [blinkfox/hexo-theme-matery#84]
首先感谢提供这么好看的博客主题，但是现在博客链接分享到微信没有缩略图，大佬考不考虑弄一下🙏

**Comment by blinkfox** [comment]
分享到微信是有缩略图的啊

**Comment by blinkfox** [comment]
我理解了你的意思了，这个分享插件使用的是[share.js](https://github.com/overtrue/share.js)，好像有人去给它提过这个`issue`，我这里处理不了哈，这个`issue`我要关闭了。
