### ISSUE TITLE
本地静态网站显示正常，但上传到github没有主题，只有乱序的文字

### ISSUE THREAD

**Issue by ycluohuang** [blinkfox/hexo-theme-matery#851]
![屏幕截图(28)](https://user-images.githubusercontent.com/107366313/189492891-3fa7899d-e3af-4e2b-a5a7-b2ecee0cbfab.png)
![屏幕截图(27)](https://user-images.githubusercontent.com/107366313/189492945-693cb5b0-e882-4ecc-b62b-b477817ab895.png)

就像这样，重头开始弄一遍还是这样，搞了两天了还是不行.

**Comment by appotry** [comment]
F12 打开控制台看一下报错是什么

**Comment by EscapeLife** [comment]
@ycluohuang 访问你主页是可以看到的，解决的话，issues就关了
