### ISSUE TITLE
音乐播放中断问题

### ISSUE THREAD

**Issue by StarsPicking** [blinkfox/hexo-theme-matery#866]
添加首页音乐和单独的音乐播放界面后，刷新页面音乐会中断播放，是否考虑修复呢

**Comment by appotry** [comment]
这个需要新增ajax支持才能支持刷新不间断播放音乐，已经有人在这个主题中实现过

刚翻了下以前笔记的[参考链接](https://blog.17lai.site/posts/84b4059a/#%E5%8F%82%E8%80%83-%E6%84%9F%E8%B0%A2)，这个源码已经支持了

https://github.com/aloeJun/hexo-themes-matery-pro
