### ISSUE TITLE
Can't display post image with local asset

### ISSUE THREAD

**Issue by Tilix4** [blinkfox/hexo-theme-matery#87]
Hi, thank you for your wonderful work !

I want to set the image of my post with a local asset `img: /sources/medias/featureimages/MyImage.jpg` but it doesn't work. What am I missing ?

My code looks like:

> title: MyPost
> date: 2016-06-13 15:44:43
> img: /sources/medias/featureimages/MyImage.jpg

**Comment by blinkfox** [comment]
@Tilix4 You should remove the `/sources` prefix，and write like this:

 `img: /medias/featureimages/MyImage.jpg`

**Comment by Tilix4** [comment]
@blinkfox Thank you very much, it works for that.
What if I want to get an image from my hexo root folder (not from matery theme)? Like:
`/source/images/myimage.jpg`

**Comment by blinkfox** [comment]
Same as before.
Like: `/images/myimage.jpg`.

**Comment by Tilix4** [comment]
Wonderful. Thank you.
