### ISSUE TITLE
首页轮播推荐文章设置不生效

### ISSUE THREAD

**Issue by 3232731490** [blinkfox/hexo-theme-matery#876]
![image](https://user-images.githubusercontent.com/75670203/219406005-43ed7f05-29c4-49f6-8ed9-973184094f9d.png)
“在 _data/covers.json 下配置推荐文章, false则使用主题在文章中的配置 cover coverImg” 
“useConfig 使用方式: 将主题 hexo-theme-matery/source/_data/covers.json 移动到 my-blog/source/_data/下修改配置即可”
未在指定目录找到covers.json文件

**Comment by frankt2099** [comment]
我也没发现这个文件，所以首页没有banner轮播效果，，，，
