### ISSUE TITLE
代码样式出错

### ISSUE THREAD

**Issue by cunyu1943** [blinkfox/hexo-theme-matery#878]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/22308895/219946194-9665d896-bebb-4d0e-b276-81c645b6926f.png">

**Comment by jiak94** [comment]
go to hexo's config, set the `highlight.enable=false`, and set `prismjs.enable=true`. Then restart the hexo.

**Comment by Bigwode** [comment]
求问为啥我这么设置了还是不行
![WX20240124-001329](https://github.com/blinkfox/hexo-theme-matery/assets/28911418/5e664948-b920-4836-b944-1adc4b9c65f7)
