### ISSUE TITLE
图片标签问题

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#88]
在文章中，如果一些图片有标签，一些没有，那么点开图片后，没有标签的图片会显示上一张图片的标签。

比如说，文章是这么写的：
```md
![图片1](/1.jpg)
![](/2.jpg)
```
然后文章页呈现：
![](https://s2.ax1x.com/2019/03/16/AVgTvF.png)
点开图片1后呈现：
![](https://s2.ax1x.com/2019/03/16/AVgbDJ.png)

但是滑到第二张图片时：
![](https://s2.ax1x.com/2019/03/16/AVgHu4.png)

注意，第二张图片本来不该显示图片标签，但是沿用了上一张图片的标签。这样导致了图片和标签错乱。

打扰了，万分感激！

**Comment by HarborZeng** [comment]
点开图片之前的caption是根据img标签的title和alt属性呈现的，点开之后caption内容是由lightGallery控制的，<https://github.com/blinkfox/hexo-theme-matery/blob/develop/source/js/matery.js#L106>，我感觉像是lightGallery的bug

**Comment by lzctuhao** [comment]
嗯嗯，谢谢大佬
