### ISSUE TITLE
代码块高亮好像不支持hexo 7.0.0

### ISSUE THREAD

**Issue by MrAriten** [blinkfox/hexo-theme-matery#898]
我在7.0.0版本下捣鼓了半天，最后是在hexo init命令执行的时候，因为网络问题没有用到最新的hexo-starter，而hexo-starter在上周从6.3.0更新到了7.0.0版本的hexp

INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
fatal: unable to access 'https://github.com/hexojs/hexo-starter.git/': Recv failure: Connection was reset
WARN  git clone failed. Copying data instead

阴差阳错安装了6.3.0的hexo，代码块才能高亮

**Comment by Talljack** [comment]
<img width="640" alt="image" src="https://github.com/blinkfox/hexo-theme-matery/assets/34439652/b91d7639-0be6-4142-8168-b60c17b4adde">

我的 7.0.0代码显示也有问题，按照文档配置的

<img width="311" alt="image" src="https://github.com/blinkfox/hexo-theme-matery/assets/34439652/ddf1451b-0204-4cd2-996c-781ed4325554">

**Comment by MrAriten** [comment]
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/34439652/282228932-b91d7639-0be6-4142-8168-b60c17b4adde.png">
> 我的 7.0.0代码显示也有问题，按照文档配置的
> 
> <img alt="image" width="311" src="https://user-images.githubusercontent.com/34439652/282228968-ddf1451b-0204-4cd2-996c-781ed4325554.png">

你hexo init的时候不要联网就行了，这样就不会安装最新的hexo

**Comment by zhszstudy** [comment]
我也是7.0版本，降级就好了


```
#全局卸载
npm uninstall hexo-cli -g
#重装
npm install -g hexo-cli@4.2.0
#查看版本
hexo version
#清除缓存
hexo clean
#运行
hexo serve
```

**Comment by Talljack** [comment]
嗯嗯 已经降级到6.3了

**Comment by zhszstudy** [comment]
> 嗯嗯 已经降级到6.3了

好家伙，刚评论完就回复，，

**Comment by Nan-ying** [comment]
> 我也是7.0版本，降级就好了
> 
> ```
> #全局卸载
> npm uninstall hexo-cli -g
> #重装
> npm install -g hexo-cli@4.2.0
> #查看版本
> hexo version
> #清除缓存
> hexo clean
> #运行
> hexo serve
> ```

这个好像还是安装的7.0.0版本，请问怎么降级呀，官网一直推荐的最新版本

**Comment by Nan-ying** [comment]
> 嗯嗯 已经降级到6.3了

请问怎么降级，我搞了半天还是7.0.0

**Comment by Nan-ying** [comment]
> > 我也是7.0版本，降级就好了
> > ```
> > #全局卸载
> > npm uninstall hexo-cli -g
> > #重装
> > npm install -g hexo-cli@4.2.0
> > #查看版本
> > hexo version
> > #清除缓存
> > hexo clean
> > #运行
> > hexo serve
> > ```
> 
> 这个好像还是安装的7.0.0版本，请问怎么降级呀，官网一直推荐的最新版本

解决了，直接将hexo init生成的文件中的package.json中的hexo版本修改一下即可降级
`{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^7.0.0", # 这里改成6.3.0
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}`

**Comment by Nan-ying** [comment]
> > 我也是7.0版本，降级就好了
> > ```
> > #全局卸载
> > npm uninstall hexo-cli -g
> > #重装
> > npm install -g hexo-cli@4.2.0
> > #查看版本
> > hexo version
> > #清除缓存
> > hexo clean
> > #运行
> > hexo serve
> > ```
> 
> 这个好像还是安装的7.0.0版本，请问怎么降级呀，官网一直推荐的最新版本

解决了，直接将hexo init生成的文件中的package.json中的hexo版本修改一下即可降级
```json
"dependencies": {
  "hexo": "^7.0.0", // 这里改成6.3.0
  "hexo-generator-archive": "^2.0.0",
  "hexo-generator-category": "^2.0.0",
  "hexo-generator-index": "^3.0.0",
  "hexo-generator-tag": "^2.0.0",
  "hexo-renderer-ejs": "^2.0.0",
  "hexo-renderer-marked": "^6.0.0",
  "hexo-renderer-stylus": "^3.0.0",
  "hexo-server": "^3.0.0",
  "hexo-theme-landscape": "^1.0.0"
}
```

**Comment by A-caibird** [comment]
> 我也是7.0版本，降级就好了
> 
> ```
> #全局卸载
> npm uninstall hexo-cli -g
> #重装
> npm install -g hexo-cli@4.2.0
> #查看版本
> hexo version
> #清除缓存
> hexo clean
> #运行
> hexo serve
> ```
这个有效的，解决了感谢

**Comment by moyin1004** [comment]
https://github.com/hexojs/hexo/issues/5283 @Talljack @936127241 @MrAriten @Nan-ying @A-caibird 
7.0新增配置项就可以了
```
syntax_highlighter: prismjs
```

**Comment by marcos-boy** [comment]
> [hexojs/hexo#5283](https://github.com/hexojs/hexo/issues/5283) @Talljack @936127241 @MrAriten @Nan-ying @A-caibird 7.0新增配置项就可以了
> 
> ```
> syntax_highlighter: prismjs
> ```

折腾一天，原来是版本问题，已解决，感谢！

**Comment by A-caibird** [comment]
> > [hexojs/hexo#5283](https://github.com/hexojs/hexo/issues/5283) @Talljack @936127241 @MrAriten @Nan-ying @A-caibird 7.0新增配置项就可以了
> > ```
> > syntax_highlighter: prismjs
> > ```
> 
> 折腾一天，原来是版本问题，已解决，感谢！

感谢,设置了一下就好了

**Comment by levi5611** [comment]
> [hexojs/hexo#5283](https://github.com/hexojs/hexo/issues/5283) @Talljack @936127241 @MrAriten @Nan-ying @A-caibird 7.0新增配置项就可以了
> 
> ```
> syntax_highlighter: prismjs
> ```

感谢感谢，一下就行了
