### ISSUE TITLE
prism插件移动端显示问题

### ISSUE THREAD

**Issue by sherlonWang** [blinkfox/hexo-theme-matery#90]
大佬，我自己搭的博客prism插件移动端显示错位，但是我看你的网站上并没有这个问题，请问你用的是哪个主题的？

**Comment by HarborZeng** [comment]
有图吗？

**Comment by sherlonWang** [comment]
我的图：
![微信图片_20190319201434](https://user-images.githubusercontent.com/44674881/54605250-c6eb6e80-4a83-11e9-9777-185300c3b163.jpg)

博主的图：

![微信图片_20190319201447](https://user-images.githubusercontent.com/44674881/54605466-4bd68800-4a84-11e9-9060-6d67be46b67d.jpg)

**Comment by sherlonWang** [comment]
@HarborZeng pc端显示是没问题的。
![pc](https://user-images.githubusercontent.com/44674881/54605650-bab3e100-4a84-11e9-8447-ba7d9eb0a65c.png)

**Comment by HarborZeng** [comment]
@sherlonWang 你这个移动端好像自动换行，我看了下好像是大佬给弄得“特性”，哈哈哈哈，你要是不喜欢，可以把<https://github.com/blinkfox/hexo-theme-matery/blob/develop/source/css/matery.css#L127>这一行代码删除：

也就是把 `white-space` 删掉

```javascript
code[class*="language-"],
pre[class*="language-"] {
    color: #e8eaf6;
    white-space: pre-wrap !important;
}
```

**Comment by sherlonWang** [comment]
@HarborZeng 哇，删掉就好了，谢谢大佬！🤓

**Comment by blinkfox** [comment]
@HarborZeng 谢谢你的回复。我看好像是解决了，那这个问题我先关了。
