### ISSUE TITLE
hexo serve在本地看页面显示是正常的，图片正常加载，但是deploy之后打开的页面格式是错乱的。

### ISSUE THREAD

**Issue by Bigwode** [blinkfox/hexo-theme-matery#907]
https://bigwode.github.io/

**Comment by appotry** [comment]
F12打开控制台，可以看到css加载失败，路径什么地方设置不对

**Comment by Bigwode** [comment]
请问主题需要修改什么路径吗？教程里并没有对应的说明呢

**Comment by Bigwode** [comment]
经检查，是url设置不对导致的，应该是https://bigwode.github.io而不是后面还要加个project。。网上的教程害人啊呜呜呜
