### ISSUE TITLE
Tag page : auto scroll to top when tag clicked

### ISSUE THREAD

**Issue by Tilix4** [blinkfox/hexo-theme-matery#91]
In the [tag page](https://blinkfox.github.io/tags/), when you click on a tag, the page scrolls back to top automatically which is not very handy to have a quick overview of them.

**Comment by HarborZeng** [comment]
Hhhhhh, can't argee more. This will happen especially when you have tremendous amount of tags.

My solution is to have the tag area scrollable:
![image](https://user-images.githubusercontent.com/8568937/54652628-719a7600-4af2-11e9-8feb-d3d60ca3f827.png)

In which case, just add this css in the `matery.css` for your concern:

```javascript
.tags-container {
    max-height: 300px;
    overflow-y: scroll;
}
```

and enbale it by attach this css name to this line <https://github.com/blinkfox/hexo-theme-matery/blob/develop/layout/_widget/tag-cloud.ejs#L27>

**Comment by HarborZeng** [comment]
this can also work for category problem

**Comment by blinkfox** [comment]
@Tilix4 I should not make any changes to these two pages for the time being. You can customize them yourself.

**Comment by blinkfox** [comment]
I will close the issue.
