### ISSUE TITLE
网站加载逻辑问题：图片最后加载

### ISSUE THREAD

**Issue by lzctuhao** [blinkfox/hexo-theme-matery#93]
您好！能否优化首页加载逻辑顺序为：图片最后加载

有时候因为某一张封面图片加载时间较长，导致动画js要等图片全部加载完成才加载，影响体验。

以下是我首页的部分瀑布流：

![](https://s2.ax1x.com/2019/03/21/Aljhut.png)

**Comment by blinkfox** [comment]
嗯，可以，后续有时间我看看如何搞这个。

**Comment by HarborZeng** [comment]
使用hexo-img-lazyload

**Comment by lzctuhao** [comment]
@HarborZeng hexo-img-lazyload插件在这个主题上无法正常运行，好像是因为渲染时会加上lightGallery，具体的不清楚

感谢提供懒加载的思路！我再看看

**Comment by HarborZeng** [comment]
@lzctuhao hexo-lazyload-image的作用原理是讲你博客里面img标签的src属性替换为一个loading image，把真实的图片地址放在data-origin属性下面。然后当你的网页翻到那张图片时（也就是图片在窗口中完全可见时），他会有一段js用data-origin的内容替换src，打到懒加载的目的。

是的，一般情况下懒加载和gallery插件会发生冲突，比如按照我上面所说，最终结果就会变成，可能只有第一张图片在gallery中打开是原图，右翻左翻都会是那张loading image，需要你掌握js，可以修改matery.js里面的内容，甚至可能换一个gallery，比如photosiwpe之类的。

**Comment by jerryc127** [comment]
你可以使用这个lozad.js

首先，在head 加上 

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
```

然后添加js
```
$(function (
    var $img = $("img");
    $img.addClass("lozad");

    $img.each(function () {
        var src_link = $(this).attr("src");   
        $(this).attr("data-src", src_link);
        $(this).removeAttr("src");

        
    })
     //lazy懶加載
  const observer = lozad(); // lazy loads elements with default selector as '.lozad'
  observer.observe();

});
```

感觉应该可行（我不是用这个主题，无法测试）

**Comment by lzctuhao** [comment]
@HarborZeng 感谢指教！受益匪浅~
@jerryc127 感谢！我试一试~

**Comment by wyx1818** [comment]
我也使用

> @HarborZeng hexo-img-lazyload插件在这个主题上无法正常运行，好像是因为渲染时会加上lightGallery，具体的不清楚
> 
> 感谢提供懒加载的思路！我再看看

解决方法修改/themes/matery/source/js/matery.js

103行
```
$('#articleContent, #myGallery').lightGallery({
            selector: '.img-item',
            // 启用字幕
            subHtmlSelectorRelative: true,
            showThumbByDefault: false
        });
```
后面加上
```
        $(document).find('img[data-original]').each(function(){
            $(this).parent().attr("href", $(this).attr("data-original"));
        });
```

**Comment by NS-Sp4ce** [comment]
> 我也使用
> 
> > @HarborZeng hexo-img-lazyload插件在这个主题上无法正常运行，好像是因为渲染时会加上lightGallery，具体的不清楚
> > 感谢提供懒加载的思路！我再看看
> 
> 解决方法修改/themes/matery/source/js/matery.js
> 
> 103行
> 
> ```
> $('#articleContent, #myGallery').lightGallery({
>             selector: '.img-item',
>             // 启用字幕
>             subHtmlSelectorRelative: true,
>             showThumbByDefault: false
>         });
> ```
> 后面加上
> 
> ```
>         $(document).find('img[data-original]').each(function(){
>             $(this).parent().attr("href", $(this).attr("data-original"));
>         });
> ```

您好，我也遇到了这个情况，使用您的代码后无效，请问能提供下具体的代码吗？感谢

**Comment by NS-Sp4ce** [comment]
折腾了下，装了个插件，https://github.com/Troy-Yang/hexo-lazyload-image 解决了
