### ISSUE TITLE
support RTL and arabic lang

### ISSUE THREAD

**Issue by MohammedShalan** [blinkfox/hexo-theme-matery#96]
post title in Arabic shown as squares, how to fix this ?

**Comment by blinkfox** [comment]
@MohammedShalan Sorry, I don't know how to write in Arabic. You can define an Arabic internationalization support in the `languages` directory, and then specify the language file name in the `language` attribute in the root `_config.yml` file.

**Comment by MohammedShalan** [comment]
thanks man, I solved it by editing layout and header file then adding `ar file` in language folder.

**Comment by blinkfox** [comment]
OK, I will close this issue.
